### ISSUE TITLE
Function `current` seems to be deprecated from usage on objects from PHP7.4 and upwards

### ISSUE THREAD

**Issue by GinoPane** [php/doc-en#1034]
Here's the link for demonstration: https://3v4l.org/fdrNR

![image](https://user-images.githubusercontent.com/3897579/137895984-e78773fb-e74c-43f4-9475-d8d6db938fce.png)

This needs to be reflected in docs and in changelogs for the relevant PHP version. I didn't find any references for this change in docs.

---

From manual page: https://php.net/function.current

**Comment by kamil-tekiela** [comment]
That's correct. See https://www.php.net/manual/en/migration81.deprecated.php#migration81.deprecated.standard 
Feel free to suggest a PR to update the relevant pages with changelog information.
