### ISSUE TITLE
Unclear when the options parameter was added

### ISSUE THREAD

**Issue by Andrew-Staves-Activ** [php/doc-en#1084]
From manual page: https://php.net/function.unserialize
---
Neither the [changelog](https://www.php.net/manual/en/function.unserialize.php#refsect1-function.unserialize-changelog) or the options [parameter](https://www.php.net/manual/en/function.unserialize.php#refsect1-function.unserialize-parameters) indicate which version it was added in. It doesn't work in PHP 5.6.40, but I don't know precisely which version introduced it. I think it would be useful for this information to be included, if possible.

Thanks.

**Comment by cmb69** [comment]
The $options parameter is available as of PHP 7.0.0. However, the PHP manual is currently supposed to document PHP 7.0.0 to PHP 8.1.0, so this information is obsolete. If you still need documentation for PHP 5, see https://php-legacy-docs.zend.com/manual/php5/en/index.

**Comment by Andrew-Staves-Activ** [comment]
Thanks, that's good to know.
