### ISSUE TITLE
A non-existent section "Backslash" appears in the paragraph

### ISSUE THREAD

**Issue by runbing** [php/doc-en#1099]
From manual page: https://php.net/regexp.reference.back-references

---

I saw the following sentence in the second paragraph of the above page:

> See the section entitled "Backslash" above for further details of the handling of digits following a backslash.

I did not find the section titled "**Backslash**". I think it is more related to the section titled "**Escape sequences**". Is this a mistake?

**Comment by cmb69** [comment]
Good catch, thank you!
