### ISSUE TITLE
preg_match_all does not mention null in return values

### ISSUE THREAD

**Issue by kamil-tekiela** [php/doc-en#1102]
From manual page: https://php.net/function.preg-match-all

---

The function can return null (https://heap.space/xref/php-src/ext/pcre/php_pcre.c?r=e089a50f#1210) but the return values section doesn't specify that.

**Comment by nikic** [comment]
The null return type was incorrect, fixed in https://github.com/php/php-src/commit/bc6ec0a109177bae7ee662c4f1d0b19b3bc3150b. Still needs to be removed from docs.
