### ISSUE TITLE
[Unit|Backed]Enum is an interface

### ISSUE THREAD

**Issue by BenMorel** [php/doc-en#1135]
The [manual for UnitEnum](https://www.php.net/manual/en/class.unitenum.php) currently shows:

```php
class UnitEnum {
    /* Methods */
    abstract public static cases(): array
}
```

When it should be:

```php
interface UnitEnum {
    /* Methods */
    public static cases(): array
}
```

Sorry for not sending a PR, I'm still struggling with getting the doc build locally.

**Comment by cmb69** [comment]
Thank you!

**Comment by mumumu** [comment]
Also, we should fix [BackedEnum](https://www.php.net/manual/en/class.backedenum.php).

```php
class BackedEnum implements UnitEnum {
    /* Methods */
    abstract public static from(string|int $value): static
    abstract public static tryFrom(string|int $value): ?static
}
```

https://github.com/php/php-src/blob/d312a0c8007ffd398cbbb3cf9340db2654513cd6/Zend/zend_enum.stub.php#L10-L15

```php
interface BackedEnum extends UnitEnum
{
    public static function from(int|string $value): static;

    public static function tryFrom(int|string $value): ?static;
}
```
