### ISSUE TITLE
2nd param of IteratorIterator::__construct() has no doc

### ISSUE THREAD

**Issue by villfa** [php/doc-en#1144]
Hi,

In the documentation the signature of **IteratorIterator::__construct()** ( https://www.php.net/manual/en/iteratoriterator.construct.php ) has 2 parameters, but only the first one is documented.

There is no explanation on what the 2nd parameter is supposed to be /to do.

**Comment by salathe** [comment]
A little bit of context from [an old description of IteratorIterator](https://github.com/php/php-src/blob/php-5.1.0/ext/spl/internal/iteratoriterator.inc#L12-L39):

> This iterator wrapper allows to convert anything that is traversable into 
> an `Iterator`. It is very important to understand that most classes that do 
> not implement `Iterator` have their reasone to. Most likely they do not allow
> the full `Iterator` feature set. If so you need to provide techniques to
> prevent missuse. If you do not you must expect exceptions or fatal erros.
>
> It is also possible to derive the class and implement `IteratorAggregate` by
> downcasting the instances returned in `getIterator`. See the following
> example (assuming `BaseClass` implements `Traversable`):
>
> ```
> class SomeClass extends BaseClass implements IteratorAggregate
> {
>   function getIterator()
>   {
>     return new IteratorIterator($this, 'BaseClass');
>   }
> }
> ```
> 
> As you can see in the example this approach requires that the class to 
> downcast to is actually a base class of the specified iterator to wrap.
> Omitting the downcast in the above example would result in an endless loop
> since `IteratorIterator::__construct()` would call `SomeClass::getIterator()`.
