### ISSUE TITLE
Covarience/Contravarience with int/float doesn't work

### ISSUE THREAD

**Issue by l-vo** [php/doc-en#1157]
From manual page: https://php.net/language.oop5.variance

---

The documentation explains that covariance and contravariance are applied on int/float types. From my tests, it seems that it doesn't work:
- https://3v4l.org/g3sGB
- https://3v4l.org/4erEf

**Comment by nikic** [comment]
Yes, this bullet point is blatantly wrong.

**Comment by l-vo** [comment]
@cmb69 thank you for the fast documentation update 🙂
