### ISSUE TITLE
strftime is deprecated since PHP 8.1

### ISSUE THREAD

**Issue by dg** [php/doc-en#1164]
From manual page: https://php.net/function.strftime

It should be also mentioned in https://www.php.net/manual/en/migration81.deprecated.php

**Comment by cmb69** [comment]
Oh, right (https://wiki.php.net/rfc/deprecations_php_8_1#strftime_and_gmstrftime).

**Comment by dg** [comment]
Thanks!

**Comment by cmb69** [comment]
Thank you for reporting! :)
