### ISSUE TITLE
array_flip allegedly can return null

### ISSUE THREAD

**Issue by Tobion** [php/doc-en#1178]
The doc about array_flip https://www.php.net/manual/en/function.array-flip.php says it can return null on failure. 
Is that true? I could not find such case in the source code.
If it's true, shouldn't the function signature be changed to reflect the nullable return value?

So either the signature is not correct or the null return value is not true.

**Comment by cmb69** [comment]
`null` would only be returned prior to PHP 8.0.0, if something else than an array was passed to the function (e.g. https://3v4l.org/jBASO). This is a common thing for internal functions to do (prior to PHP 8.0.0), so does not need to be documented here at all.

Thanks for reporting!

**Comment by Tobion** [comment]
@cmb69 which version of php is being documented for those functions?
Similarly, https://www.php.net/manual/en/function.array-combine.php has the same problem. It does not return false anymore but throws a ValueError for unequal arrays.

**Comment by salathe** [comment]
@Tobion the manual currently documents PHP 7.0.0 onwards (https://www.php.net/manual/en/about.phpversions.php)

**Comment by cmb69** [comment]
The situation with `array_combine()` is slightly different. The function also returned `null` on invalid types being passed. This is [generally documented](https://www.php.net/manual/en/functions.internal.php):

> If the parameters given to a function are not what it expects, such as passing an array where a string is expected, the return value of the function is undefined. In this case it will likely return null but this is just a convention, and cannot be relied upon. As of PHP 8.0.0, a TypeError exception is supposed to be thrown in this case.

So this previously undefined behavior now throws a `TypeError`. I'm on the fence regarding `ValueErrors`, because these are somewhat different. There is still https://github.com/php/doc-en/pull/163 around, which was an attempt to cater to all `ValueErrors` in one go, but that task might be too huge.

**Comment by Girgias** [comment]
> So this previously undefined behavior now throws a `TypeError`. I'm on the fence regarding `ValueErrors`, because these are somewhat different. There is still #163 around, which was an attempt to cater to all `ValueErrors` in one go, but that task might be too huge.

I still believe it would be a good thing to have this done at one point, but a lot of it is merging all of the similar ``ValueError`s within a module book together, and actually sorting the ones from core/standard extensions into their respective doc book/module. Which could be worked on by other people than me, but it is a pretty big task.
