### ISSUE TITLE
Incorrect format example in IntlDateFormatter->setPattern()

### ISSUE THREAD

**Issue by ve3** [php/doc-en#1181]
URL: [https://www.php.net/manual/en/intldateformatter.setpattern.php](https://www.php.net/manual/en/intldateformatter.setpattern.php)

### Change 1
This contain 2 changes.<br>
Current example for 1
```php
datefmt_set_pattern($fmt, 'yyyymmdd hh:mm:ss z');
```
Current example for 2
```php
$fmt->setPattern('yyyymmdd hh:mm:ss z');
```

All pattern format should be
```
yyyyMMdd hh:mm:ss z
```

`M` is month, while `m` is minute. (See [Reference][1])

### Change 2
The last 2 lines of the output should be..
> Now pattern of the formatter is : yyyyMMdd hh:mm:ss z
> Second Formatted output with pattern is 19691231 04:00:00 PST

[1]:https://unicode-org.github.io/icu/userguide/format_parse/datetime/

**Comment by cmb69** [comment]
Thanks for reporting!
