### ISSUE TITLE
Function constant() in PHP 8 creates FATAL error, documentation says nothing

### ISSUE THREAD

**Issue by alexNecroJack** [php/doc-en#1182]
In PHP 8* function constant() changed so that an undefined constant throws fatal error.
This change is not reported in documentation:
https://www.php.net/manual/en/function.constant.php
As someone else spotted: https://github.com/php/php-src/blob/php-8.0.0beta3/UPGRADING#L35

\* Beware, in PHP 8!!! In 7 that was not the behaviour

By the way, we need both:
constant('Undefined constant') -> null
constant('Undefined constant') -> Exception

Some of us need the null version, while (I guess) some need the exception...
It would be good to have it be adjustable

**Comment by damianwadley** [comment]
> By the way, we need both:
> constant('Undefined constant') -> null
> constant('Undefined constant') -> Exception
> 
> Some of us need the null version, while (I guess) some need the exception...
> It would be good to have it be adjustable

The behavior isn't going to change because you can very easily check if a constant exists prior to calling `constant` by using [`defined`](https://www.php.net/defined). As in

```php
$value = defined("Undefined constant") ? constant("Undefined constant") : null;
```

**Comment by alexNecroJack** [comment]
Thanks for the reply.

But I can not restrain myself from commenting, that this code,
used for every single constant I need to use looks bad:
defined("Undefined constant") ? constant("Undefined constant") : null;

So as checking every variable and array key if it exists prior to being used...
Looks like PHP is turning to Java. Too much code.

Have a good day.

**Comment by cmb69** [comment]
````.php
function my_constant(string $name) {
    return defined($name) ? constant($name) : null;
}
var_dump(my_constant("Undefined constant"));
````
