### ISSUE TITLE
Wrong result for the example using the array_splice() function

### ISSUE THREAD

**Issue by hermannatz** [php/doc-en#1189]
From manual page: https://php.net/function.array-splice
---

```php
<?php

$input = array("red", "green", "blue", "yellow");
array_splice($input, 2);
var_dump($input);
```

should output "blue" and "yellow", since $offset is specified starting at 2. Currently result is displayed as "red" and "green"

**Comment by cmb69** [comment]
This is about `array_splice()`, not `array_slice()`. The former works as shown in the example: https://3v4l.org/hDeYY

**Comment by hermannatz** [comment]
OMG! I was totally wrong. Thank you ☺️
