### ISSUE TITLE
setcookie() description is not updated

### ISSUE THREAD

**Issue by ktakeda11** [php/doc-en#1192]
setcookie() manual page (https://php.net/function.setcookie) says

> This is internally achieved by setting value to 'deleted' and expiration time to one year in past.

but it is chenged in this commit.
https://github.com/php/php-src/commit/b966897a0d7412e0ded08e762aacf52000c8287e

I test `setcookie("cookie_test");` in PHP8.1, then
```
Set-Cookie: cookie_test=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0
```

**Comment by cmb69** [comment]
Good catch. Thank you!
