### ISSUE TITLE
Errors/Exceptions section is missing.

### ISSUE THREAD

**Issue by kayw-geek** [php/doc-en#1201]
From manual page: https://php.net/function.chmod

---

**Comment by cmb69** [comment]
There is nothing special about about `chmod()` with regard to Error exceptions, and it is [already documented](https://www.php.net/manual/en/functions.internal.php):

> If the parameters given to a function are not what it expects, such as passing an array where a string is expected, the return value of the function is undefined. In this case it will likely return null but this is just a convention, and cannot be relied upon. As of PHP 8.0.0, a TypeError exception is supposed to be thrown in this case.

**Comment by salathe** [comment]
Parameter parsing is not the only time where warnings/errors can be issued from `chmod()`.

For example when the `$filename` does not exist or the user does not have the required permissions, then an `E_WARNING` is issued.

**Comment by kayw-geek** [comment]
https://github.com/php/doc-en/pull/1203
