### ISSUE TITLE
imagick flop explanation is mistake.

### ISSUE THREAD

**Issue by yoya** [php/doc-en#1204]
From manual page: https://php.net/book.imagick

# imagick manual

https://www.php.net/manual/en/book.imagick.php
- Imagick::flipImage — Creates a vertical mirror image
- Imagick::flopImage — Creates a vertical mirror image

# ImageMagick manual

https://imagemagick.org/api/magick-image.php#MagickFlipImage
- MagickFlipImage
MagickFlipImage() creates a vertical mirror image by reflecting the pixels around the central x-axis.

https://imagemagick.org/api/magick-image.php#MagickFlopImage
- MagickFlopImage
MagickFlopImage() creates a horizontal mirror image by reflecting the pixels around the central y-axis.

# amendment

- Imagick::flopImage — Creates a horizontal mirror image

**Comment by cmb69** [comment]
Thank you for reporting!

**Comment by cmb69** [comment]
Fixed via https://github.com/php/doc-en/commit/29168cf804809c56a6891a378226f450973d0c7c.
