### ISSUE TITLE
Named argument in setcookie function called $expires instead of $expires_or_options

### ISSUE THREAD

**Issue by IlyaMur** [php/doc-en#1209]
https://www.php.net/manual/en/function.setcookie.php

Named argument in `setcookie` description called `$expires`. But you need to use `$expires_or_options` instead of. 

PHP VERSION: 8.0.12
OS: Mac OS 12.0.1 (Monterey)

**Comment by cmb69** [comment]
I see your point, but in my opinion, it makes no sense to document the actual function signature, because that would just be even more confusing. In hindsight, it was probably a bad idea to overload the signature in PHP 7.3. The best we may do, is to clarify that neither signature is compatible with named arguments.

**Comment by IlyaMur** [comment]
Thank you for your reply!

> The best we may do, is to clarify that neither signature is compatible with named arguments.

I'm quite new to PHP and it was little bit confusing. First time I just got an error: `Unknown named parameter $expires`.
I had gone to PHP Doc and could not understand the reason of the trouble.

**Comment by cmb69** [comment]
Yeah, this is tricky. Consider https://3v4l.org/7O9EH; so if we change the first signature (`$expires` to `$expires_or_options`), that still would not necessarily work as expected.

Maybe @kocsismate has an idea?

**Comment by kocsismate** [comment]
IMO the `$expires_or_options` name would make sense. So at least it would be a tiny bit more meaningful for the current signature.

However, if we take the future possibilities into account, then we could stay with the current parameter name and:
- add a `setcookie_options()` (or similar) function in PHP 8.2
- deprecate the 3 parameter variant of setcookie() in PHP 8.3 (or 9.0 if we want to provide a more graceful migration path)
- remove the overloaded signature in PHP 9.0/10.0

if this scenario is feasible, then it doesn't make sense to rename the parameter back and forth.

**Comment by Girgias** [comment]
Now that named arguments are a thing I would rather we deprecate using an array to provide options and add the ``StrictSite`` option as a new optional parameter to this signature.

**Comment by kocsismate** [comment]
> Now that named arguments are a thing I would rather we deprecate using an array to provide options and add the StrictSite option as a new optional parameter to this signature.

Aha, this solution also makes sense to me. Nevertheless, we can bikeshed about the details should an RFC created.

**Comment by cmb69** [comment]
On further consideration I agree that we should just rename `$expires` to `$expires_or_options` for now. After all, according to the first signature this parameter expects an `int`, so passing an array and further parameters is something a developer is not supposed to do.

**Comment by kocsismate** [comment]
Oh, I've just realized that I misunderstood the problem: I thought that we forgot to rename the parameter to `$expires_or_options` from `$expires`. Sorry for the confusion!
