### ISSUE TITLE
Loose comparison table doesn't match PHP 8+

### ISSUE THREAD

**Issue by direc85** [php/doc-en#1214]
From manual page: https://php.net/types.comparisons

The loose comparison chart doesn't match PHP 8:

PHP 7.4:
var_dump("php" == 0);
bool(true)

PHP 8.0:
var_dump("php" == 0);
bool(false)

This reads in PHP 8 release notes, but the documentation should also be updated.

Thanks!

**Comment by cmb69** [comment]
Thanks! Looks like this is a duplicate of #1146.

**Comment by cmb69** [comment]
Well, not exactly a duplicate of the other issue, but all changes need to be addressed anyway.
