### ISSUE TITLE
`streamWrapper::stream_read` return value from doc is not consistent with doc description

### ISSUE THREAD

**Issue by lcharette** [php/doc-en#1220]
From manual page: https://php.net/streamwrapper.stream-read

---

Return values description specify : 

> If there are less than count bytes available, return as many as are available. If no more data is available, return either false or an empty string.

But method only has `string` as return value : 
`public streamWrapper::stream_read(int $count): string`

This makes it incompatible with the `false` from doc description. Not sure if the method needs to support `string|false`, or the `false` mention removed from the description.

**Comment by cmb69** [comment]
Returning `false` signals failure to read, see https://3v4l.org/iPIcl.

**Comment by lcharette** [comment]
Still, returning `false` doesn’t match `stream_read` return type…

**Comment by cmb69** [comment]
Oh, right!

**Comment by cmb69** [comment]
Fixed with https://github.com/php/doc-en/commit/906db3b3f78cfa98a7453e3910bcba95bc66d1ee.
