### ISSUE TITLE
Error for type of argument?

### ISSUE THREAD

**Issue by stevespages** [php/doc-en#1229]
From manual page: https://php.net/function.curl-setopt

---I may be confused about the documentation but in the curl_setopt description the $option argument appears to be indicated as being an integer (int) when (as far as I can understand) the $option arguments are strings eg. CURLOPT_HEADER

**Comment by cmb69** [comment]
The `CURLOPT_*` constants are ints; there respective values for `curl_setopt()` may be of different types (e.g. `CURLOPT_HEADER` expects a string). The tables on that page have "titles" like "value should be a bool for the following values of the option parameter:", so you can lookup what type the value should have. However, this are technically just inline content; it would be a bit better to use `<table>`s with real `<title>`s (although that page needs to be split anyway).

**Comment by stevespages** [comment]
Thanks for your reply. I am clearly somewhat out of my depth! I think I may have worked out the source of my confusion. In the example:

curl_setopt($ch, CURLOPT_HEADER, false);

is it the case that CURLOPT_HEADER is the name of a variable which contains an integer? I was assuming it was a string.

**Comment by cmb69** [comment]
`CURLOPT_HEADER` is a *constant*, and evaluates to an integer value. You can check yourself: `var_dump(CURLOPT_HEADER)`.

**Comment by stevespages** [comment]
Thanks. I did check and it is 42 (no less than the answer to the ultimate question of life according to Douglas Adams). Sorry to have bothered you over it but it has clarified quite a lot for me.
