### ISSUE TITLE
PDO::pgsqlCopyToArray and similar family of functions wrong default delimiter in doc

### ISSUE THREAD

**Issue by sivann** [php/doc-en#1231]
Default delimiter is shown as:
`  string $delimiter = '\t',`

while it should be:
`  string $delimiter = "\t",`

This is true for all pgsqlCopy{From,To}{Array,File} methods.
Specifying the delimiter as '\t' will result in a syntax error in the SQL, with the relevant excerpt being: "WITH DELIMITER E'\' "

**Comment by cmb69** [comment]
Ah, right. Thank you!
