### ISSUE TITLE
Name of GD DLL on Windows has changed in 8.0

### ISSUE THREAD

**Issue by domenk** [php/doc-en#1263]
Manual page https://php.net/image.installation does not mention that since PHP 8.0, name of GD DLL on Windows is `php_gd.dll`, not `php_gd2.dll`.

**Comment by cmb69** [comment]
Oh, right! So far this is only [mentioned in the migration guide](https://www.php.net/manual/en/migration80.incompatible.php#migration80.incompatible.gd).
