### ISSUE TITLE
Document zend.exception_string_param_max_len ini setting

### ISSUE THREAD

**Issue by lubosdz** [php/doc-en#1277]
### Description

Hi,

please would it be possible to dump longer object names in stack dump e.g. when exception occurs?
I mean `PRICE_TOTAL_TPL...` in following sample dump:

~~~
Stack trace:
#0 D:\xpdf\app\components\XpdfFieldInput.php(224): eval()
php/php-src#1 D:\xpdf\app\components\XpdfProcessor.php(1795): XpdfFieldInput->evalForm(Object(XpdfProcessor), 'PRICE_TOTAL_TPL...')
php/php-src#2 D:\xpdf\app\components\XpdfProcessor.php(2454): XpdfProcessor->evaluateForms()
.....
~~~

Currently it dumps **only 15 chars**, which makes it difficult to trace back if more similarly named object e.g. `PRICE_TOTAL_TPL_WITH_VAT` or `PRICE_TOTAL_TPL_WITHOUT_VAT` or `PRICE_TOTAL_TPL_SUBTOTAL` etc. 
Could it be like increased to 30 chars - or even more - for PHP 8.X ?
I apologize that I am not able to make PR since i am not C guy neither understand complex PHP-SRC :-|
Thank you for any feedback.

**Comment by lubosdz** [comment]
Waw, this was really fast, thank you.

**Comment by lubosdz** [comment]
Still, would it be possible to increase default 15 chars to eg. 30 ? 15 chars is really low.
It's OK if no, I can manually set each instance, just think a little more verbosity would be generally usefull.

**Comment by cmb69** [comment]
See https://wiki.php.net/rfc/throwable_string_param_max_len for the reasoning. Consider to file a feature request at https://github.com/php/php-src/issues.
