### ISSUE TITLE
Cannot construct DateTime object from format containing textual representation of a month

### ISSUE THREAD

**Issue by pavelskipenes** [php/doc-en#1284]
From manual page: https://php.net/datetime.formats.date

---
> ## Used symbols
>|Description|Format|Examples|
>|--|--|--|
>| m | 'january' \| 'february' \| 'march' \| 'april' \| 'may' \| 'june' \| 'july' \| 'august' \| 'september' \| 'october' \| 'november' \| 'december' \| 'jan' \| 'feb' \| 'mar' \| 'apr' \| 'may' \| 'jun' \| 'jul' \| 'aug' \| 'sep' \| 'sept' \| 'oct' \| 'nov' \| 'dec' \| "I" \| "II" \| "III" \| "IV" \| "V" \| "VI" \| "VII" \| "VIII" \| "IX" \| "X" \| "XI" \| "XII" | |

> ## Localized Notations
> | Description | Format | Examples |
> | -- | -- | -- |
> | Day and textual month | d ([ .\t-])* m | "1 July", "17 Apr", "9.May"

Given this information I concluded that 'd' corresponds to numerical representation of day of the month without leading zero for days 1 - 9.  Also that 'm' can accept textual representation described above. 

That means format "d m", should accept "1 january" for instance.

Note that in the example in "Localized Notations", months abbreviations are capitalized however in "Used Symbols" there are no mentions about that capitalized words are allowed. 

```php
$date_format = "d m";
$date = DateTime::createFromFormat($date_format, "1 january");
if ($date === false){
    // error
    print(json_encode(DateTime::getLastErrors()));
    return;
}

```
```
Interactive shell

php > $date_format = "d m";
php > $date = DateTime::createFromFormat($date_format, "1 january");
php > if ($date === false){
    print(json_encode(DateTime::getLastErrors()));
    return;
}
{"warning_count":0,"warnings":[],"error_count":2,"errors":{"2":"A two digit month could not be found"}}
php > 
```

```
$ php -v
PHP 8.0.13 (cli) (built: Nov 21 2021 22:49:59) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.13, Copyright (c) Zend Technologies
```

**Comment by cmb69** [comment]
`DateTime::createFromFormat()` supports different formats, and these are [documented in its man page](https://www.php.net/manual/en/datetime.createfromformat.php). In this case you want https://3v4l.org/dPg3t.

**Comment by pavelskipenes** [comment]
Ahh. Didn't catch that. Thanks
