### ISSUE TITLE
DatePeriod::__construct(string $isostr) - ISO string does not accept time zone offsets

### ISSUE THREAD

**Issue by aeno** [php/doc-en#1291]
Regarding https://www.php.net/manual/en/dateperiod.construct.php

---

The documentation says that ISO8601 repeating interval strings are supported, but does not reveal that time zone offsets are not supported.

Calling the documentation's example (with `Z` indicating UTC timezone) works:
```php
$iso = 'R4/2012-07-01T00:00:00Z/P7D';
$period = new DatePeriod($iso);
```

The same string with an one-hour offset throws an exception:
```php
$iso = 'R4/2012-07-01T00:00:00+0100/P7D';
$period = new DatePeriod($iso);
// throws "Uncaught Exception: DatePeriod::__construct(): Unknown or bad format (R4/2012-07-01T00:00:00+0100/P7D)"
```

Valid variations of the offset part throw an exception as well:
```php
$iso = 'R4/2012-07-01T00:00:00+01/P7D';
$iso = 'R4/2012-07-01T00:00:00+01:00/P7D';
```

This fact should be included in the [notes section](https://www.php.net/manual/en/dateperiod.construct.php#refsect1-dateperiod.construct-notes)

**Comment by cmb69** [comment]
You are right that these formats are [not supported by the implementation](https://3v4l.org/2Hmab), but I'm not 100% sure whether they are valid according to the ISO 8601 standard; I don't have a copy.

Anyhow, if we need to document that, I would suggest to put it right to the documentation of the `$isostr` parameter.

**Comment by aeno** [comment]
> I'm not 100% sure whether they are valid according to the ISO 8601 standard; I don't have a copy.

At least according to Wikipedia[^1] these should be valid.
Putting this info into the documentation of the `$isostr` parameter would be fine.

[^1]: https://en.wikipedia.org/wiki/ISO_8601#Time_offsets_from_UTC
