### ISSUE TITLE
Function "clearstatcache" clear the stat cache at any time.

### ISSUE THREAD

**Issue by cpt-sugiura** [php/doc-en#1326]
https://github.com/php/doc-en/blob/312f9d4e18a7804f7d79aaaa2dfaa245401b2330/reference/filesystem/functions/clearstatcache.xml#L81

Function "clearstatcache" clear the stat cache at any time.

clearstatcache src at PHP 8.1.1
https://github.com/php/php-src/blob/php-8.1.1/ext/standard/filestat.c#L709
https://github.com/php/php-src/blob/php-8.1.1/ext/standard/filestat.c#L685

The stat cache has not "if (filename != NULL)".

**Comment by cmb69** [comment]
Right. Thank you!
