### ISSUE TITLE
Code is all in Russian

### ISSUE THREAD

**Issue by completewebco** [php/doc-en#1338]
From manual page: https://php.net/function.addslashes

---

**Comment by saundefined** [comment]
Thanks for the issue, can you clarify what do you mean?
What language is selected at the top right section?

**Comment by completewebco** [comment]
![Screen Shot 2022-01-16 at 1 46 06 PM](https://user-images.githubusercontent.com/6548537/149673506-4caf721f-75ed-4375-8aa9-615be613d088.jpg)

**Comment by completewebco** [comment]
This is on all pages for the PHP site

**Comment by kamil-tekiela** [comment]
This is not Russian. This is mojibake. Can you tell us your operating system and web browser version?

**Comment by completewebco** [comment]
Chrome 97.0.4692.71

On an iMac with macOS Big Sur Version 11.6

Thank you

.
Jason Houston
Principal / Front End Developer / SEO Consultant
Complete Web
843-560-3110
CLICK TO SCHEDULE MEETING

**Comment by completewebco** [comment]
Looks like it is a local font conflict on my machine. Fira Sans must be corrupted on my end

**Comment by saundefined** [comment]
Seems it can be closed
