### ISSUE TITLE
strtotime returns non-sense integer given some timestamp string between Jan 17, 2022 and Jan 19, 2022

### ISSUE THREAD

**Issue by robert-h-at-cp** [php/doc-en#1343]
### Description

The following code:

```php
<?php
php > var_dump(strtotime('1642300000')); // GMT: Sunday, January 16, 2022 2:26:40 AM
php > var_dump(strtotime('1642400000')); // GMT: Monday, January 17, 2022 6:13:20 AM
php > var_dump(strtotime('1642500000')); // GMT: Tuesday, January 18, 2022 10:00:00 AM
php > var_dump(strtotime('1642600000')); // GMT: Wednesday, January 19, 2022 1:46:40 PM
php > var_dump(strtotime('1642700000')); // GMT: Thursday, January 20, 2022 5:33:20 PM
```

Resulted in this output:
```
bool(false)
int(-62165776640)
int(-62165776630)
int(-62165776620)
bool(false)
```

But I expected this output instead:
```
bool(false)
bool(false)
bool(false)
bool(false)
bool(false)
```

### PHP Version

PHP 7.4.24

**Comment by derickr** [comment]
The way how this is parsed, is as follows:

```
$ php -r 'print_r(date_parse("1642400000"));'
Array
(
    [year] => 0
    [month] => false
    [day] => false
    [hour] => 16
    [minute] => 42
    [second] => 40
```
i.e.: `his` (`164240`) followed by the year `0`.

And then contrast that with:
```
$ php -r 'print_r(date_parse("1642300000"));'
Array
(
    [year] => 1642
    [month] => 1
    [day] => 300
    [hour] => false
    [minute] => false
    [second] => false
    [fraction] => false
    [warning_count] => 1
    [warnings] => Array
        (
            [11] => The parsed date was invalid
        )
    [error_count] => 3
    [errors] => Array
        (
            [7] => Unexpected character
            [8] => Unexpected character
            [9] => Unexpected character
        )
    [is_localtime] => false
```

As @cmb says, `strtotime` (and the `DateTimeImmutable` constructor are really liberal at what to accept. All these formats are at https://www.php.net/manual/en/datetime.formats.compound.php . In this case, it detects **PostgreSQL: Year with day-of-year** which pattern is `year4 [.-]? dayofyear`. The `dayofyear` aonly allows up to 365, and hence the 400 from the previous example doesn't match this rule.

Date/Time parsing is really complicated. If you want to be strict about what you accept, then you need to use `DateTimeImmutable::createFromFormat`.

As everything is documented, I see no further action.
