### ISSUE TITLE
I am getting a mysqli error

### ISSUE THREAD

**Issue by Markus1954** [php/doc-en#1348]
From manual page: https://php.net/faq.databases

---I am reading this book called "The Joy of PHP". So far I have no joy. I have copied this code from the book. It creates a database and inserts stuff into the database. The code is below.
`$mysqli = new mysqli('mysql', 'root, verysecretr')` I get an error that says: Fatal error: Uncaught Error: Class "mysqli" not found in C:\Apache24\htdocs\Joy\CreateDB.php:7 Stack trace: #0 {main} thrown in C:\Apache24\htdocs\Joy\CreateDB.php on line 7.
I removed the semicolon in php.ini I also set the extension_dir to c:\php8\ext. I don't know what else to do to get it working. I need help.
Mark

**Comment by damianwadley** [comment]
Sounds like you don't have mysqli enabled. Did you remember to restart Apache after editing your php.ini?

If that doesn't fix it, this issue tracker isn't a great place for support questions so StackOverflow and [other online communities](https://www.php.net/support.php) might be better able to help.
