### ISSUE TITLE
"<?" no loger supported

### ISSUE THREAD

**Issue by MJosipovi** [php/doc-en#1356]
From manual page: https://php.net/migration80.incompatible
(Migration from php 7.4 to php 8)
---

I believe it should be added to the documentation that begging of php code can no longer be "<?", but rather with "<?php". I had some scripts where i did this "mistakes" and I almost got a heart attack when I saw my code printed in plain text when page was requested.

This is my first submit and English is not my first language, so please excuse me for any mistakes.

**Comment by cmb69** [comment]
Short open tags are still supported, but one needs to enable the [respective INI setting](https://www.php.net/manual/en/ini.core.php#ini.short-open-tag). There has been no particular change for PHP 8.
