### ISSUE TITLE
EOL Page missing migration guides

### ISSUE THREAD

**Issue by delboy1978uk** [php/doc-en#1364]
https://www.php.net/eol.php lists all the old versions no longer supported. However, the migration guide links listed are broken for any version below PHP 5.5. There are many sites still using these unsupported versions, so i think it's important that the info to get them migrating should still be available.

**Comment by saundefined** [comment]
You can use the legacy manual on the Zend site for [PHP 5](https://php-legacy-docs.zend.com/manual/php5/en/index) and [PHP 4](https://php-legacy-docs.zend.com/manual/php4/en/index), and also download the [manual archives](http://doc.php.net/archives/).

**Comment by tarlepp** [comment]
I think that `https://www.php.net/eol.php` page should have proper links - just make those to links to use that legacy manual links - or at least mention that legacy docs are available on another site.

**Comment by cmb69** [comment]
I think we should just fix the [links on the eol.php page](https://github.com/php/web-php/blob/master/eol.php#L8-L21), but that would then be a https://github.com/php/web-php issue. Pull request welcome!

**Comment by delboy1978uk** [comment]
The links appear to be fixed!
