### ISSUE TITLE
Gearman: setXXXCallback() needs to be called before addTaskXXX()

### ISSUE THREAD

**Issue by cracksalad** [php/doc-en#1369]
From manual page: https://php.net/gearmanclient.setcompletecallback

---

It should be noted that:

All the `GearmanClient::setXXXCallback(...)` methods (like `GearmanClient::setCompleteCallback(...)`) need to be called before calling some `GearmanClient::addTaskXXX(...)` method (like `GearmanClient::addTask(...)`). Setting the callback before calling `GearmanClient::runTasks()` is not sufficient.

Sounds stupid but such things just cost time.

**Comment by cmb69** [comment]
@rlerdorf, is that correct?

**Comment by cracksalad** [comment]
> @rlerdorf, is that correct?

Long time, no see, but I created a minimal test to proof this.

Worker:
```php
<?php
$worker = new GearmanWorker();
$worker->addServer();

$worker->addFunction('test', function(GearmanJob $job): string {
  return $job->workload();
});

while($worker->work());
```

Client:
```php
<?php
$client = new GearmanClient();
$client->addServer();

$client->addTask('test', 'foo', unique_key: '1');

$client->setCompleteCallback(function(GearmanTask $task): void {
  echo 'task #'.$task->unique().' result "'.$task->data().'"'.PHP_EOL;
});

$client->addTask('test', 'bar', unique_key: '2');

$client->runTasks();
```

Output:
```
task #2 result "bar"
```

Take home message: task number 1 does not show up in the output, i.e. the order of `addTask` and `setXXXCallback` (at least for `setCompleteCallback`) matters.
