### ISSUE TITLE
Gearman: setXXXCallback() parameter definition incomplete

### ISSUE THREAD

**Issue by cracksalad** [php/doc-en#1370]
As shown [here](https://www.php.net/manual/en/gearmanclient.addtask.php) in the second example, (at least) a complete-callback function is called with the GearmanTask instance as the first parameter and the mixed-type `$context` which is set via `GearmanClient::addTaskXXX(...)` (third parameter) as the second parameter. I just tested it and I can confirm that the `$context` is passed to the callback.
The documentation of `GearmanClient::setCompleteCallback(...)` [here](https://www.php.net/manual/en/gearmanclient.setcompletecallback.php) says nothing about the parameters of the callback.

**Comment by Girgias** [comment]
Fixed by #3861
