### ISSUE TITLE
DOMNodeList::item() returns DOMElement instead of DOMNode

### ISSUE THREAD

**Issue by phptest2** [php/doc-en#1375]
https://www.php.net/manual/de/domnodelist.item.php

current:
```
public [DOMNode](https://www.php.net/manual/de/class.domnode.php)List::item(int $index): DOMNode|DOMNameSpaceNode|null
``` 

should be:
```
public [DOMNode](https://www.php.net/manual/de/class.domnode.php)List::item(int $index): DOMElement|DOMText|null
``` 

Example 1: https://3v4l.org/7NZKo
Example 2: https://www.php.net/manual/de/domnodelist.item.php#119471

**Comment by cmb69** [comment]
From the [docs](https://www.php.net/manual/en/class.domelement.php):

> class `DOMElement` extends `DOMNode`

This also matches the [DOM specification](https://dom.spec.whatwg.org/#interface-nodelist).
