### ISSUE TITLE
Unable to build memcache plugin

### ISSUE THREAD

**Issue by paulkudla** [php/doc-en#1381]
From manual page: https://php.net/faq.build

when building

/usr/local/src/net/php-extentions/memcache-4.0.5.2

php-extentions/memcache-4.0.5.2/php7/memcache.c  -fPIC -DPIC -o php7/.libs/memcache.o
In file included from /usr/local/src/net/php-extentions/memcache-4.0.5.2/php7/memcache.c:26:
In file included from /usr/local/include/php/main/php.h:33:
In file included from /usr/local/include/php/Zend/zend.h:27:
In file included from /usr/local/include/php/Zend/zend_types.h:25:
In file included from /usr/local/include/php/Zend/zend_portability.h:43:
In file included from /usr/local/include/php/Zend/zend_config.h:1:
/usr/local/include/php/main/../main/php_config.h:2372:10: fatal error: 'ext/php_config.h' file not found
#include <ext/php_config.h>
         ^~~~~~~~~~~~~~~~~~
1 error generated.
gmake: *** [Makefile:192: php7/memcache.lo] Error 1

---

**Comment by cmb69** [comment]
This doesn't look like a documentation issue, so please report at https://github.com/websupport-sk/pecl-memcache/issues.
