### ISSUE TITLE
Missing documentation about GD requires zlib

### ISSUE THREAD

**Issue by mpepito13** [php/doc-en#1383]
From manual page: https://php.net/zlib.installation

PHP 7.4.27 cannot be compiled without zlib being installed (see error line 10051 in the attachment)

Is it a documentation issue or Makefile issue ?

[config.log](https://github.com/php/doc-en/files/8011271/config.log)

---

**Comment by cmb69** [comment]
https://www.php.net/manual/en/zlib.requirements.php mentions zlib as requirement. Isn't that sufficient?

**Comment by mpepito13** [comment]
I don't understand it the same way as you.
https://www.php.net/manual/en/zlib.requirements.php mentions that a zlib version >= 1.2.0.4 is a requirement if you want to use Zlib, not that Zlib is a requirement to compile PHP.

By the way, I don't have the error when I compile PHP 8.1.

**Comment by cmb69** [comment]
Hmm, zlib is not supposed to be enabled by default (neither for PHP 7.4 nor 8.1). What was the configure line which produced the config.log above?

**Comment by cmb69** [comment]
Hmm, zlib is a dependency of ext/gd (what is not documented) and maybe other components. Please try to build without `--enable-gd` to confirm.

**Comment by mpepito13** [comment]
Yes it works !
I need GD so I will install zlib on my own but thanks for your help
