### ISSUE TITLE
Inconsistent DOMEntity Documentation

### ISSUE THREAD

**Issue by AndrolGenhald** [php/doc-en#1385]
https://www.php.net/manual/en/class.domentity.php

Under the Properties section, all 6 properties are mentioned to be `null` in certain cases, but the Class synopsis doesn't show any of them as nullable.

The [stub](https://github.com/php/php-src/blob/PHP-8.1/ext/dom/php_dom.stub.php#L614:L642) also indicates that they are nullable.

**Comment by cmb69** [comment]
It seems that PR #1295 would fix this.

**Comment by Girgias** [comment]
Since #1295 was merged this is fixed.
