### ISSUE TITLE
PDO MySQL constant documentation issues

### ISSUE THREAD

**Issue by AndrolGenhald** [php/doc-en#1392]
The PDO MySQL constant [documentation](https://www.php.net/manual/en/ref.pdo-mysql.php) is inconsistent with the actual constants defined.

`PDO::MYSQL_ATTR_SERVER_PUBLIC_KEY` exists but is not documented.
  
`PDO::MYSQL_ATTR_LOCAL_INFILE_DIRECTORY` and `PDO::MYSQL_ATTR_INIT_COMMAND` are documented as having type `string` but are actually `int`s.

`PDO::MYSQL_ATTR_LOCAL_INFILE` is documented to be available as of PHP 8.1.0, but it's available in earlier versions. Meanwhile, `PDO::MYSQL_ATTR_LOCAL_INFILE_DIRECTORY` has no version note, but it's not available until PHP 8.1.0. This seems like the version documentation got mixed up and put on the wrong constant.

**Comment by cmb69** [comment]
Right, thanks! Additional notes:

* `MYSQL_ATTR_SERVER_PUBLIC_KEY` is available, if build against libmysql-client ≥ 5.6.5 or mysqlnd
* `MYSQL_ATTR_LOCAL_INFILE_DIRECTORY` is indeed only available as of PHP 8.1.0
* `MYSQL_ATTR_LOCAL_INFILE` is available for all relevant versions (PHP 7.0.0+)
