### ISSUE TITLE
autounlock parameter in constructor is actually int not bool?

### ISSUE THREAD

**Issue by determin1st** [php/doc-en#1397]
From manual page: https://php.net/syncreaderwriter.construct

---
i'm using PHP v8.0 with Sync extension, winOS. When i create an instance with explicitly set boolean argument (`true` or `false`), it says:

```
SyncReaderWriter::__construct(): Argument #2 ($autounlock) must be of type int, bool given
```

also, first argument, the name, if it contains `\` character, it always throws:

```
Reader-Writer object could not be created
```

otherwise, the object is created

**Comment by cmb69** [comment]
According to [the implementation](https://github.com/php/pecl-system-sync/blob/1c8b2e5306af6982a91fcf07c8ffda0358da0aa2/sync.c#L1678), the proper signature is:
````
public SyncReaderWriter::__construct(string $name = "", int $autounlock = 1)
````
I think it needs to stay that way for BC reasons (strict_types), but a bool would have made more sense. cc @cubiclesoft

> also, first argument, the name, if it contains \ character, it always throws:

That appears to be Windows specific: from [the docs](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-createsemaphorea):

> The remainder of the name can contain any character except the backslash character (\).
