### ISSUE TITLE
PDO::pgsqlGetNotify inconsistent return type

### ISSUE THREAD

**Issue by AndrolGenhald** [php/doc-en#1398]
https://www.php.net/manual/en/pdo.pgsqlgetnotify.php

The Description says it returns `array` but the Return Values section says it can return `false`.

**Comment by cmb69** [comment]
According to [the stub](https://github.com/php/php-src/blob/PHP-8.1/ext/pdo_pgsql/pgsql_driver.stub.php#L29), the return type is `array|false`.
