### ISSUE TITLE
crypt on failure returns 13 characters (one too many according the documentation..)

### ISSUE THREAD

**Issue by divinity76** [php/doc-en#1423]
### Description

quoting the docs
>Returns the hashed string or a string that is shorter than 13 characters and is guaranteed to differ from the salt on failure.

which means the following code:

```php
<?php
var_dump(strlen(crypt("garbage","garbage")) < 13);
```

should return this output
```
bool(true)
```

but instead it returns this output
```
bool(false)
```

### PHP Version

8.1.3

**Comment by divinity76** [comment]
@cmb69  holy damn now i see what you mean,
 it didn't fail, it thought the first 2 characters of salt "garbage" was the salt for CRYPT_STD_DES and ignored the rest of it 🤦‍♂️

its bad that crypt() assumes CRYPT_STD_DES when the salt length doesn't match, but that's a matter for another day

**Comment by cmb69** [comment]
Further explanation: the shortest hashes `crypt()` can produce are of type `CRYPT_STD_DES`. Their length is always 13 characters, so anything shorter always signals failure (although I think that only `*1` or `*0` are returned on failure).
