### ISSUE TITLE
json_decode documentation could be clearer

### ISSUE THREAD

**Issue by stevespages** [php/doc-en#1431]
re; https://www.php.net/manual/en/function.json-decode.php

It may seem pedantic but I think it would be really helpful to change your code example from 

`$json = '{"foo-bar": 12345}';`

to

`$jsonString = '{"foo-bar": 12345}';`

The whole point of the function is to convert a JSON String into JSON. In which case calling the name of the variable which contains the JSON String $json is misleading.

The description given for the function is 

> Takes a JSON encoded string and converts it into a PHP variable. 

I do not really understand what is meant by "converts it into a PHP variable". Could the function not be used like this:

`echo (json_decode($jsonString));`

If so, would it be converting it into a PHP variable?

I realize I am somewhat confused by this whole issue so apologies if I am barking up the wrong tree.

**Comment by cmb69** [comment]
> The whole point of the function is to convert a JSON String into JSON.

Not quite. It converts a JSON string to a PHP value. In my opinion, using `$json` as variable name is quite apt.

> I do not really understand what is meant by "converts it into a PHP variable".

Oh, yeah, that is a historic relict (still occurs not seldom in the PHP manual); actually, that should be a "PHP value".

**Comment by stevespages** [comment]
thanks for explanation. I think I see what you mean about it not converting it into JSON which presumably is not really a "thing" in PHP but converting into an appropriate PHP value which can be manipulated by PHP.

I do not really see why you think $json is more apt than $jsonString which I feel would emphasize that you are doing something to a a JSON string rather than to JSON which to me is a different thing. JSON is a form of notation which is not used when a JSON string is passed between two computer languages. What is used are 1. a JSON string and 2. the language specific values which that JSON string can be converted to. Neither of those is JSON although the whole subject area could be referred to as JSON. I am probably chasing my tail round in circles but I do think that the word JSON is a confusing one whereas JSON string is very well and clearly defined.

**Comment by cmb69** [comment]
I agree that "JSON string" is more clear, but calling the variable `$json` matches the name of the parameter, and should be sufficiently clear. But let's see what other think about this. :)

**Comment by kamil-tekiela** [comment]
`$jsonString` would be ok, but I think `$json` is better. It matches the parameter name and the text on that page. 

The "into variable" part should be changed as cmb69 said.

**Comment by stevespages** [comment]
I can see that $json is not as misleading as I originally thought because I was not fully aware that the JSON string is really properly formatted JSON. Somehow I thought it was a different representation of the data.

**Comment by kamil-tekiela** [comment]
Yes, and on the other hand calling it `$jsonString` could mean an actual string encoded as JSON. This could cause people to wonder why a string in JSON after being decoded to PHP value becomes an object/array/bool/int...

**Comment by cronlabspl** [comment]
> This could cause people to wonder why a string in JSON after being decoded to PHP value becomes an object/array/bool/int...

If naming outfilling variable disdcally render people mapless, than just change PSR routine.
