### ISSUE TITLE
missing the trailing semicolon

### ISSUE THREAD

**Issue by zhengjianhong001** [php/doc-en#1432]
From manual page: https://php.net/reflectionclass.getdoccomment
missing the trailing semicolon
---
<img width="559" alt="image" src="https://user-images.githubusercontent.com/19474012/155868285-33c2f905-d7d1-4dda-9469-01f59e1259b0.png">

**Comment by kamil-tekiela** [comment]
Why should there be a semicolon? The `?>` is already a semicolon.

**Comment by cmb69** [comment]
I think we're having trailing semicolons in almost every other example snippet, and these certainly don't hurt.
