### ISSUE TITLE
DateTime::format has lost information about escaping

### ISSUE THREAD

**Issue by Roy-Orbison** [php/doc-en#1443]
From manual page: https://php.net/datetime.format

---
I'm pretty sure that the `DateTime::format`/`date_format` doc page once had information regarding backslash escaping of literal characters, now it's only buried in the comments. Suggestion:

>The backslash character (`\`) must be used to escape both itself and any character that should appear literally in the output rather than be interpreted as a formatting character. You will need to double the `\` in string literals where PHP would interpret it as an escape sequence so, for example `$date->format("l \\a\\t ga")` might produce `Tuesday at 4pm`.

**Comment by cmb69** [comment]
The `date()` documentation already mentions:

> You can prevent a recognized character in the format string from being expanded by escaping it with a preceding backslash. If the character with a backslash is already a special sequence, you may need to also escape the backslash.

This should be rewritten to avoid the personalization ("you"), clarified, and made into an XML entity, so it could be included in the `DateTime::format()` docs.

**Comment by Roy-Orbison** [comment]
[The description][0] of the `$format` parameter of `date()` is simply a reference to `DateTimeInterface::format()`. All documentation of escaping, examples, etc., should be at least duplicated, if not only at the latter.

[0]: https://github.com/php/doc-en/blob/971e603c5de57fd81cd02a1ab553fbfc1b367038/reference/datetime/functions/date.xml#L31
