### ISSUE TITLE
missing key word

### ISSUE THREAD

**Issue by zeusaadam** [php/doc-en#1453]
From manual page: https://php.net/reserved.keywords
enum should be listed as a key word
---

**Comment by damianwadley** [comment]
Actually that's not completely accurate.

> The following words cannot be used as constants, class names, function or method names.

`enum` is a keyword in the sense that PHP recognizes it as a special T_ENUM token, however it does not have the same restrictions that other keywords have. https://3v4l.org/S9AlA

Nor does it necessarily belong on [the other page's main list](https://www.php.net/manual/en/reserved.other-reserved-words.php):

> The following words cannot be used to name a class, interface or trait, and they are also prohibited from being used in namespaces.

That page does, however, have a second list of "soft reservations". That's probably the most accurate place for `enum` to be right now... but come PHP 9, when breaking changes can be made, I suspect it may be promoted to a "[full keyword](https://wiki.php.net/rfc/enumerations#backward_incompatible_changes)".

So `enum` is a bit of a special case.
