### ISSUE TITLE
Adding information about PHP version where format character was added

### ISSUE THREAD

**Issue by fliespl** [php/doc-en#1460]
From manual page: https://php.net/datetime.format

---

Not really a bug, but probably helpful info for everyone.

I have "p" format characters is only working in PHP 8+ and not before (where it renders as "p" char instead of timezone diff).

**Comment by saundefined** [comment]
Hey, thanks for this issue.

That the `p` character was introduced in PHP 8.0.0 is documented in the [changelog section](https://www.php.net/manual/en/datetime.format.php#refsect1-datetime.format-changelog).

---

Hm... Should we add "Available as of PHP 8.0.0" significant in the table?

**Comment by fliespl** [comment]
@saundefined hard to tell. Maybe it was not obvious only for me until facing an issue and digging much more into documentation (then I realized it's in changelog, but normally you take format that you forgot out of the table since it's listed :) ).

Maybe not full column is needed but marking it as "8.0+" sup is also an option as such? https://ss.codeone.pl/ss-2022-03-14-09-29-49-1647246589-Y0r8ZN45.png

Or maybe no change is needed at all and we can just assume I was not paying enough attention? On the other hand if more new format characters were to come in next versions it might become hard to track which are available where.
