### ISSUE TITLE
passthru() returnvalue section incorrect

### ISSUE THREAD

**Issue by Ilyes512** [php/doc-en#1462]
So looking at the [passthru](https://www.php.net/manual/en/function.passthru.php) function signature it says it returns `?bool` while it should be `void`.  Or am I incorrect? 

So currently it states:

```
passthru(string $command, int &$result_code = null): ?bool
```

And I think it should be:

```
passthru(string $command, int &$result_code = null): void
```

**Comment by cmb69** [comment]
It looks like the signature is not quite correct: `passthru()` returns `null` (what should be treated like `void` by the programmer) on success, and `false` on failure to open the underlying pipe. The signature change would need to be done in [php-src](https://github.com/php/php-src/blob/27be6c34b51d7f7d05765e73b6095da8b0ac6a8e/ext/standard/basic_functions.stub.php#L1094). The docs need to be fixed regarding the return value section (which currently states "No value is returned.")

**Comment by cmb69** [comment]
> The signature change would need to be done in [php-src](https://github.com/php/php-src/blob/27be6c34b51d7f7d05765e73b6095da8b0ac6a8e/ext/standard/basic_functions.stub.php#L1094).

Nope, that is already properly done via a return type hint.
