### ISSUE TITLE
SplObjectStorage::removeAll does not return the number of removed objects

### ISSUE THREAD

**Issue by MatTheCat** [php/doc-en#1467]
See https://3v4l.org/5bLSQ

The doc says the return should be `1` but it’s `2`: the number of objects **left** in the storage.

`SplObjectStorage::removeAllExcept` has the same issue.

I can open a PR for both english and french docs if someone confirms I’m not missing something :pray:

**Comment by MatTheCat** [comment]
Thanks @cmb69 for the PR. How does i18n work in doc repositories? Should I copy this issue in every other?

**Comment by saundefined** [comment]
@MatTheCat Thanks for the issue, no worries =)
The translators will see this commit and update the translations repos.

**Comment by MatTheCat** [comment]
Nice! Thanks @saundefined
