### ISSUE TITLE
parse_url: port 0 is valid since 7.4.12 and 7.3.24

### ISSUE THREAD

**Issue by tflori** [php/doc-en#1468]
From manual page: https://php.net/function.parse-url

---

In my opinion it should be mentioned that since php 7.4.12 and php 7.3.24 port 0 is valid.

```php
var_dump(parse_url('//example.com:0'));
```

Before version 7.4.12 and 7.3.24:
```
bool(false)
```

In 7.4.12 and 7.3.24:
```
array(1) {
  ["host"]=>
  string(11) "example.com"
}
```

After version 7.4.12 and 7.3.24 (also 8.x):
```
array(2) {
  ["host"]=>
  string(11) "example.com"
  ["port"]=>
  int(0)
}
```

**Comment by cmb69** [comment]
Not accepting port 0 was a bug, and we usually don't document bug fixes. Is this particular case worth to make an exemption?

**Comment by tflori** [comment]
I would not agree that it is a bug but now I see. The thing is: either it is a basic validation of the URL or not. You can't have something on port 0 (listening on port 0 will open a random port). But port 65536 is not valid (beacause of 16bit int restriction) and returns false..  but ok, that's another discussion then :smile:
