### ISSUE TITLE
`strftime` is deprecated as of PHP 8.1 but no mention of what to use instead

### ISSUE THREAD

**Issue by ericlbarnes** [php/doc-en#1478]
From manual page: https://php.net/function.strftime

---

This page includes the message: 

> Warning This function has been DEPRECATED as of PHP 8.1.0. Relying on this function is highly discouraged.

However, it makes no mention of what one should use instead.  According to what I believe is a 3rd party site (https://php.watch/versions/8.1/strftime-gmstrftime-deprecated) it says you should use `IntlDateFormatter` or `DateTime::format` but it would be nice to have this spelled out in the official docs.

**Comment by cmb69** [comment]
Official info: https://wiki.php.net/rfc/deprecations_php_8_1#strftime_and_gmstrftime

I agree that we should point out the alternatives there.

**Comment by valvereetu** [comment]
How one is supposed to accomplish replacing e.g. `strftime("%B / %Y");` with the provided alternative functions, honoring the locale?
