### ISSUE TITLE
mb_detect_encoding undocumented behavior change

### ISSUE THREAD

**Issue by come-nc** [php/doc-en#1490]
See https://github.com/php/php-src/issues/8279#issuecomment-1084319270

`mb_detect_encoding` is not behaving as documented anymore since 8.1. It is now using heuristics to try to detect the most likely encoding, independently of the order the encoding are passed to it.
This needs to be documented both on `mb_detect_encoding` page and on the upgrading to 8.1 page.

**Comment by cmb69** [comment]
Thank you for reporting this issue. However, I'm closing this ticket in favor of #1708.
