### ISSUE TITLE
Anonymous functions changes and arrows

### ISSUE THREAD

**Issue by Eccenux** [php/doc-en#1496]
From manual page: https://php.net/functions.anonymous

---

Changelog entries are missing:

- 5.3.0 - Anonymous functions became available. 
- 5.4.0 - Static anonymous functions support was added.

Maybe also add:
- See also: Arrow functions https://www.php.net/functions.arrow

**Comment by cmb69** [comment]
The manual is currently supposed to [document PHP ≥ 7.0.0](https://www.php.net/docs.php); as such, changes made during the PHP 5 area are irrelevant. 

It might make sense to add an explicit link to arrow functions on the anonymous function page, but on the other hand, that page is literally the next page, so there is already a direct navigation link.

**Comment by Girgias** [comment]
I'm going to close this as we do not document PHP 5 any more and the link to the arrow functions seems of questionable utility as it is the next page in the manual.
