### ISSUE TITLE
Attributes reflection documentation

### ISSUE THREAD

**Issue by enumag** [php/doc-en#1508]
I'd like to start using Attributes but it seems the documentation for ReflectionAttribute and related methods is unfinished.

For instance [ReflectionClass::getAttributes()](https://www.php.net/manual/en/reflectionclass.getattributes.php) has a flags parameter with unknown purpose and values. A comment mentions a `ReflectionAttribute::IS_INSTANCEOF` constant which is not documented on the ReflectionAttribute class documentation. I assume there are more missing constants for this flag.

**Comment by cmb69** [comment]
So far, there [is only `ReflectionAttribute::IS_INSTANCEOF`](https://github.com/php/php-src/blob/cdf7240f7547b093aaee52e4fd0a2336f77e3374/ext/reflection/php_reflection.c#L1181-L1184). The meaning is [explained in the RFC](https://wiki.php.net/rfc/attributes_v2#reflection).

**Comment by Girgias** [comment]
This seems to have been fixed. Please open a new issue if not.
