### ISSUE TITLE
Documentation misses to mention the added backslashes for _POST values.

### ISSUE THREAD

**Issue by castilma** [php/doc-en#1509]
From manual page: https://php.net/reserved.variables.post

---

Assume a <form> with a <textarea> field, which gets sent via POST. When the user enters the 2 lines
```
\
"
```
and submits, the browser may sends in the http body
`podcast_xml_fields=%5C%0D%0A%22`.

The result of `echo _POST['fieldname']` is
```
\\
\"
```
and not 
```
\
"
```
So, PHP adds backslashes to the input! Why? Developers expect _POST['field'] to contain the users input, not some weirdly escaped input. For what would it need to be escaped?

Was there at some point a public decision process that resulted in this behaviour? Can someone link to it?

The Bug that I'm reporting is, that the documentation of _POST etc. should explicitly mention this shortcoming and mention `stripslashes()`.

**Comment by cmb69** [comment]
Is it possible that you're running a PHP version which still supports [`magic_quotes_gpc`](https://www.php.net/manual/en/info.configuration.php#ini.magic-quotes-gpc), and this setting is enabled?

**Comment by kamil-tekiela** [comment]
It might also be possible that you are escaping them yourself. e.g. using `mysqli_real_escape_string` or `addslashes`. I think this mistake is more common now than magic quotes. 

Anyway, this doesn't seem like a problem with documentation, since such behaviour isn't present in PHP anymore.

**Comment by castilma** [comment]
I have this problem inside wordpress.

After your replies I checked with a simple php skript and it works as expected. So it seems like wordpress is doing something nasty. Sorry for the noise.

Any idea, how I could debug this?

**Comment by cmb69** [comment]
Maybe https://wordpress.stackexchange.com/questions/21693/wordpress-and-magic-quotes helps.

**Comment by castilma** [comment]
Thanks, it seems to be intended worpress behaviour, but I've never read about that. Well, wordpress has the worst documentation ever, anyways.
