### ISSUE TITLE
htmlspecialchars appears strong typed, but isn't

### ISSUE THREAD

**Issue by pvdhurk** [php/doc-en#1516]
https://www.php.net/manual/en/function.htmlspecialchars.php

The current documentation makes it look like the first argument is strong types and therefore NULL would be fatal.
We had to define our own htmlspecialchars wrapper because we depended on single quotes not being converted and ran into the issue that we had more Fatals than before.

The first argument $string should explain that:
- Passing NULL
  - From 8.1 will raise a deprecation
- Passing array
  - Before 8.1 will raise a warning
  - From 8.1 will be fatal

PS. Not excusing our situation, but this is about correcting documentation to prevent problems in the real world

**Comment by Girgias** [comment]
This is documented at https://www.php.net/manual/en/functions.internal.php
