### ISSUE TITLE
`Object` not listed as a reserved class name

### ISSUE THREAD

**Issue by icatalina** [php/doc-en#1518]
Object not listed as a reserved class name in: https://www.php.net/manual/en/reserved.classes.php

```
PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in Object.php on line 14

Fatal error: Cannot use 'Object' as class name as it is reserved in Object.php on line 14

Errors parsing Object.php
```

**Comment by damianwadley** [comment]
"Object" is not a predefined _class_. It would not be listed on that page.

It is, however, a _reserved word_, and does appear on [that page](https://www.php.net/manual/en/reserved.other-reserved-words.php).
