### ISSUE TITLE
Missing documentation of second parameter of `imagick.writeimagefile`

### ISSUE THREAD

**Issue by nagmat84** [php/doc-en#1529]
From manual page: https://php.net/imagick.writeimagefile

According to the shown signature, the method takes a second parameter which designates the format. But this parameter is not documented and the range of valid values is unclear.

**Comment by cmb69** [comment]
I think `$format` is supposed to be a file extension (like `png` or `jpeg`), but I'm not sure about that.

**Comment by cmb69** [comment]
cc @Danack

**Comment by nagmat84** [comment]
You are nearly right.

In the meantime, I had a look into the C source code of the PHP extension. The list of valid format specifiers depends on the compiled feature set of imagick and can be queried at runtime via `Imagick::queryFormats`.

In 90% of all cases the format specifier resembles a well-known file extension and something common like "jpg" is probably always recognized for sure. For many formats more than one format specifier is defined as an alias, i.e. "jpg", "jpeg", "JPG" and "JPEG" will work. But beware, the comparison is case-sensitive, i.e. if a certain spelling is not registered with the format, it does not work. So, the authoritative answer is given by `Imagick::queryFormats`.

Anyway, that should be in the docs.

**Comment by cmb69** [comment]
Ah, thank you!
