### ISSUE TITLE
mysqli_stmt::execute() expects exactly 0 parameters

### ISSUE THREAD

**Issue by theking2** [php/doc-en#1532]
From manual page: https://php.net/mysqli-stmt.execute

Tested in PHP 7.4.26

mysqli_stmt::execute() does not expect a parameter
mysqli_stmt_execute() expects exactly 1 parameter

Test programm
```
<?php declare(strict_types=1);

$db = new mysqli('localhost', 'test', 'test', 'test');
$stmt = $db-> prepare('INSERT INTO `test` (`id`, `name`, `date`, `unsigned`) VALUES (NULL, ?, ?, ?) ');
$stmt-> execute(['John Doe', '2020-01-01', 1]);
mysqli_stmt_execute( $stmt, [ 'John Doe', '2020-01-01', 1 ] );
```

```
CREATE TABLE  `test` (
  `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` varchar(255)  NOT NULL,
  `date` date NOT NULL,
  `unsigned` int(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`)
);
```

Error message:
`Fatal error: Uncaught ArgumentCountError: mysqli_stmt_execute() expects exactly 1 parameter, 2 given in D:\Projekte\test-execute\index.php:6 Stack trace: #0 D:\Projekte\test-execute\index.php(6): mysqli_stmt_execute(Object(mysqli_stmt), Array) #1 {main} thrown in D:\Projekte\test-execute\index.php on line 6`
---

**Comment by theking2** [comment]
Sorry the line about 8.1.0 is rather obscurly placed. But in 8.1.0 this problem is not there.

Suggest to make this more prominent.

**Comment by cmb69** [comment]
Well, the behavior of the most recent PHP version is documented, and everything that has changed from previous version is listed in the changelog. This is how it is supposed to be (and done elsewhere in the manual, unless the pages are not yet up to date).
