### ISSUE TITLE
array_merge Description do not say anything about null array.

### ISSUE THREAD

**Issue by aarkaynegi** [php/doc-en#1535]
From manual page: https://php.net/function.array-merge

--- Description do not say anything about null array.

**Comment by damianwadley** [comment]
Neither does this issue.

It doesn't say _what_ about "null arrays"?

**Comment by cmb69** [comment]
I'm closing this ticket due to lack of requested feedback. @aarkaynegi, feel free to re-open if you can clarify what that problem you're seeing actually is.
