### ISSUE TITLE
Enable zts to use pthread features, but make failure

### ISSUE THREAD

**Issue by benson8767** [php/doc-en#1544]
php version
![image](https://user-images.githubusercontent.com/37609456/165280773-8cd48996-b808-4f2a-ae97-0c434b8b82ad.png)

sudo ./configure --enable-zts
![image](https://user-images.githubusercontent.com/37609456/165279755-b824355c-df3b-48fe-b2db-46117a0cdac6.png)

sudo make
there are some errors as below:
![image](https://user-images.githubusercontent.com/37609456/165280390-2a3c8807-7be6-4b1b-bf99-98f6a8dc6488.png)

thanks for help!

**Comment by cmb69** [comment]
There is no ext/opcache/jit directory prior to PHP 8.0.0. Apparently, there is something wrong with your php-src setup.

Anyhow, such questions are better asked on StackOverflow or any of the other [support channels](https://www.php.net/support). It is certainly not a documentation issue.
