### ISSUE TITLE
Passing null to non-nullable parameters of built-in functions

### ISSUE THREAD

**Issue by saundefined** [php/doc-en#1554]
Should this change be documented in each function?

@cmb69 @Girgias what do you think?

**Comment by kocsismate** [comment]
> Should this change be documented in each function?

I'm not Christoph or George ^^ but I think it's not really feasible or practical to add a notice to every other manual page. I'm not exactly sure if there is a better place, but maybe this behavior could be documented at https://www.php.net/manual/en/functions.arguments.php.

**Comment by damianwadley** [comment]
...or https://www.php.net/manual/en/functions.internal.php.

**Comment by saundefined** [comment]
Thank you both :)

I think `functions.internal` is the suitable place, I suggest the PR #1555 with the addition of this note.
That do you think?
