### ISSUE TITLE
str_repeat(): Argument #2 ($times) must be greater than or equal to 0

### ISSUE THREAD

**Issue by anthonyeden** [php/doc-en#1558]
From manual page: https://php.net/function.str-repeat

---

On PHP 8, calling str_repeat with arg #2 < 0 throws this exception:

    PHP Fatal error:  Uncaught ValueError: str_repeat(): Argument #2 ($times) must be greater than or equal to 0

The docs do not currently reflect this. They currently state "If the times is set to 0, the function will return an empty string.".

**Comment by cmb69** [comment]
The relevant part of the documentation is:

> $times has to be greater than or equal to 0.

Prior to PHP 8.0.0, a negative `$times` raised `E_WARNING` (and returned `null`, but that's better regarded as undefined behavior); as of PHP 8.0.0, a `ValueError` is thrown instead. This is not particularly special for `str_repeat()`, but rather affects all (or most) functions which warned about unsupported values.

We need to document this, but I wouldn't be happy to document this for every single function individually.

**Comment by anthonyeden** [comment]
Fair enough. I just think PHP's docs are usually quite good in showing the return values in an error state, and noting a ValueError exception would be very useful here.

**Comment by kamil-tekiela** [comment]
I am closing this issue since the documentation already states:

> times has to be greater than or equal to 0.

In PHP, passing invalid parameters throws Value Error, so everything checks out.
