### ISSUE TITLE
Enums don't support class hoisting

### ISSUE THREAD

**Issue by jpheldson** [php/doc-en#1564]
### Description

Unlike class definitions, it seems that enum definitions currently need to come dynamically before they are used.  So far as I could find this is not in the documentation, and leads to very un-intuitive behavior.

The following code:

```php
<?php

$f = new Foo();
var_export($f->returnEnum());

enum FooEnum {
    case Bar;
    case Qux;
}

// If I had put the call to Foo::returnEnum() here, it would have worked!

class Foo {
    public function returnEnum(): FooEnum
    {
        return FooEnum::Bar;
    }
}
```

Resulted in this output:
```
Fatal error: Uncaught Error: Class "FooEnum" not found in /home/tmp/u.php:14
Stack trace:
#0 /home/tmp/u.php(4): Foo->returnEnum()
php/php-src#1 {main}
  thrown in /home/tmp/u.php on line 16
```

But I expected this output instead:
```
FooEnum::Bar
```

### PHP Version

PHP 8.1.2

### Operating System

FreeBSD 12.3-RELEASE r371270 NFSN64  amd64

**Comment by cmb69** [comment]
> Maybe we can convert this to a documentation issue, […]

But how should the docs explain the complex actual behavior, except to point to [nikic's blog post](https://www.npopov.com/2021/10/20/Early-binding-in-PHP.html)?

If a simplified explanation is sufficient, we [already have](https://www.php.net/manual/en/language.oop5.inheritance.php):
> Unless autoloading is used, the classes must be defined before they are used. If a class extends another, then the parent class must be declared before the child class structure. This rule applies to classes that inherit other classes and interfaces.

This is, however, not sufficient for recent PHP versions.

**Comment by jpheldson** [comment]
I know in my case, something like @iluuu1994's original reply as a notice in the documentation for Enums would have saved me a lot of time.

**Comment by iluuu1994** [comment]
@cmb69 Maybe we just add that enums and classes with __toString() aren't supported without going in much more detail, and potentially adding a link to Nikitas blog (I'm not sure if we do links to other sources).

**Comment by tiffany-taylor** [comment]
> (I'm not sure if we do links to other sources).

There are links to external sources, but it is limited. Hard to say if this is a valid case for that.

**Comment by cmb69** [comment]
I think it is okay to link to that blog post; in the long run  it would be nice to have respective info on phpinternalsbook.com.
