### ISSUE TITLE
No info on return value of ctype_alnum() in case of empty string

### ISSUE THREAD

**Issue by estebanthebad** [php/doc-en#1568]
From manual page: https://php.net/function.ctype-alnum

---
The page doesn't say anything about what the return value in case of an empty string is.

To be more specific, the return value in this case is `FALSE`, which is very counter intutitive as there is no character which is not alphanumeric. But well, one could argue that the point of view is, if the whole string is alphanumeric and that it is not, because there are no alphanumeric characters in it. But the doc only says "Returns true if every character in text is either a letter or a digit, .. ". So it is open to interpretation and the interpretation depends on the point of view.

In any case imo the docs should be specific about this case.

**Comment by cmb69** [comment]
Right, the result on a empty string is suprising to me: https://3v4l.org/IEtdi.

**Comment by Girgias** [comment]
> Right, the result on a empty string is suprising to me: https://3v4l.org/IEtdi.

Weirdly enough I'm of the opposite opinion, it makes a lot of sense to me that an empty string is not considered alphanumeric.

But in any case this should indeed be documented.
