### ISSUE TITLE
f/sscanf() functions do not mention assignment suppression feature

### ISSUE THREAD

**Issue by mickmackusa** [php/doc-en#1571]
On https://www.php.net/manual/en/function.sscanf.php

The format parameter details do not mention the assignment suppression flag.
Assignment suppression has been a feature of sscanf() since it was added in PHP4.0.1.

Presentation-wise, should the sscanf() page have a pretty table for the flags like https://www.php.net/manual/en/function.fscanf.php ?

I've never used fscanf(), but if the comment @ https://github.com/php/php-src/blob/0b7fd17c2bb12a89048c307858f77db7a77e145c/ext/standard/scanf.c#:~:text=This%20is%20the%20internal,both%20sscanf()%20and%20fscanf() is true, then perhaps https://www.php.net/manual/en/function.fscanf.php should be updated in the same manner.

**Comment by cmb69** [comment]
Thanks for reporting!

> Presentation-wise, should the sscanf() page have a pretty table for the flags like https://www.php.net/manual/en/function.fscanf.php ?

The detailed information on the `fscanf()` page is wrong; that is the `?printf()` format specification which is slightly different from `?scanf()`. I don't think it makes much sense to duplicate all these details; the currrent `sscanf()` man page looks good to me.

Anyhow, `fscanf()` and `SplFileObject::fscanf()` also support the assignment suppression specifier.
