### ISSUE TITLE
Not specifying the connection parameter for pg_query_params() etc. is deprecated

### ISSUE THREAD

**Issue by Nicate** [php/doc-en#1572]
If you do not specify a connection parameter, pg_query_params() and the like will print the following warning if error reporting is enabled:

`Deprecated: pg_query_params(): Automatic fetching of PostgreSQL connection is deprecated in <...> on line <...>`

This is not reflected in the docs.

**Comment by cmb69** [comment]
Indeed, this is only [mentioned in the migration guide](https://www.php.net/manual/en/migration81.deprecated.php#migration81.deprecated.pgsql) so far.
