### ISSUE TITLE
Require documentation changelog for default error mode of the mysqli extension

### ISSUE THREAD

**Issue by philliphegarty** [php/doc-en#1573]
### Description

The following code:

Create a Mysql table, testtable with two columns - Domain INT(3), Dataname VARCHAR(10)
Create an index - create unique index idx1 on testtable(Domain, Dataname)

Using mysqli - INSERT INTO testtable (Domain, Dataname) VALUES (1, 'FRED');      // Works - unique
                         INSERT INTO testtable (Domain, Dataname) VALUES (2, 'JOHN');     // Works - unique
                         INSERT INTO testtable (Domain, Dataname) VALUES (2, 'FRED');      // Works - unique
                         INSERT INTO testtable (Domain, Dataname) VALUES (1, 'JOHN');      // Works - unique
                         INSERT INTO testtable (Domain, Dataname) VALUES (1, 'FRED');      // Fails - with unhandled Exception

Resulted in this output:
       See above

But I expected this output instead:
       Expected returned resource to be false, because the SQL would result in a duplicate

### PHP Version

PHP 8.1.4

### Operating System

MacOS Monterey 12.3.1

**Comment by kamil-tekiela** [comment]
I believe this is complete. https://www.php.net/manual/en/mysqli-driver.report-mode.php#refsect1-mysqli-driver.report-mode-changelog
