### ISSUE TITLE
Keyword documentation contradicts itself

### ISSUE THREAD

**Issue by TomBrunner** [php/doc-en#1574]
"The following words **cannot be used as** constants, class names, function or **method names**.They are, however, **allowed** as property, constant, and **method names of classes**, interfaces and traits,..."

Link: https://www.php.net/manual/en/reserved.keywords.php

as to my knowledge methods are functions, but within classes. This documentation seems to contradict itself.
(also mentioned as such in https://www.php.net/manual/en/language.oop5.basic.php)

It does appear to be allowed as method names in classes.
![image](https://user-images.githubusercontent.com/2787944/167154786-bfd734a5-ee96-4b60-a9ca-4a445a826c89.png)

**Comment by cmb69** [comment]
Indeed. Thanks for reporting!
