### ISSUE TITLE
`get_parent_class` may return false

### ISSUE THREAD

**Issue by rela589n** [php/doc-en#1575]
Hello!

In documentation it is stated that `get_parent_class` returns `string`:

```php
get_parent_class(object|string $object_or_class = ?): string
```

But for case if there's no parent, it returns `false`.
Hence, correct signature should be like this:

```php
get_parent_class(object|string $object_or_class = ?): string|false
```

Consider this example as a test:
```php
class A {
    
}

var_dump(get_parent_class(new A));
```

For all versions of php the output is `bool(false)`.

**Comment by cmb69** [comment]
Indeed. Thanks for reporting!
