### ISSUE TITLE
New opcache.record_warnings setting is undocumented

### ISSUE THREAD

**Issue by cxcorp** [php/doc-en#1576]
The OPcache [Runtime Configuration](https://www.php.net/manual/en/opcache.configuration.php) reference page is missing `opcache.record_warnings`, which was introduced in PHP 8.0, and [is still present in 8.1.5](https://github.com/php/php-src/blob/1f44c7e91ccf068de7e541051bbff87591214049/ext/opcache/zend_accelerator_module.c#L255).

The PHP 7.4 to 8.0 migration guide [makes note of this new setting](https://www.php.net/manual/en/migration80.new-features.php#migration80.new-features.opcache) in the following way:

> If the `opcache.record_warnings` ini setting is enabled, OPcache will record compile-time warnings and replay them on the next include, even if it is served from cache.

**Comment by cmb69** [comment]
Thank you!
