### ISSUE TITLE
ICU date format doc link is outdated

### ISSUE THREAD

**Issue by ziaratban** [php/doc-en#1577]
From manual page: https://php.net/intldateformatter.formatobject

---

New link :
https://unicode-org.github.io/icu/userguide/format_parse/datetime/#datetime-format-syntax

**Comment by cmb69** [comment]
Thank you!

**Comment by cmb69** [comment]
Fixed as https://github.com/php/doc-base/commit/b3c7eb022a7d48e23568c440a3a493e3d080d14a.
