### ISSUE TITLE
Changed error behavior in array_chunk in php 8

### ISSUE THREAD

**Issue by FoGezz** [php/doc-en#1586]
https://www.php.net/manual/ru/function.array-chunk.php

When 2rd argument '$length' is less then 1, in PHP < 8.0 it caused E_WARNING. 
In PHP 8 it causes https://www.php.net/manual/ru/class.valueerror.php

```
<?php

try {
	array_chunk([1,2,3], 0);
} catch (\Throwable $e) {
	print_r($e);
}
```

<img width="1235" alt="image" src="https://user-images.githubusercontent.com/15945499/169038838-a7337c42-b8b9-4c4b-b914-e0c8521f4ce4.png">

**Comment by cmb69** [comment]
Indeed.
