### ISSUE TITLE
session.gc_maxlifetime default value missing

### ISSUE THREAD

**Issue by php4fan** [php/doc-en#1591]
From manual page: https://php.net/session.configuration

---

https://www.php.net/manual/en/session.configuration.php#ini.session.gc-maxlifetime

The documentation of `session.gc_maxlifetime` does not say what the default value is.

**Comment by cmb69** [comment]
All default values are listed in the table at the top of [that page](https://www.php.net/manual/en/session.configuration.php) as usual. Are you perhaps looking at a translation?

**Comment by php4fan** [comment]
> All default values are listed in the table at the top of [that page](https://www.php.net/manual/en/session.configuration.php) as usual

Right, but almost **all** of the default of every other constant, except this one and a couple others, are also repeated in the description, so you don't have to scroll up and go back to the table.

Example:

![image](https://user-images.githubusercontent.com/13969584/169650807-fd3ca2ea-65a1-4ce6-907d-0d1cd2fb4faf.png)

**Comment by cmb69** [comment]
I'm not a fan of duplicated info, but leave this ticket open for others to comment.

**Comment by php4fan** [comment]
Well, there's duplicated info all over the place. That seems to be the standard throughout the documentation, and for good reasons. It makes no sense to avoid this one instance.

If you want to avoid the _hard-coded_ duplicates in the documentation _source code_, then you should devise a mechanism for the default to be defined in one place and then referenced in multiple places. Which I'm actually surprised to see is not a thing already.

**Comment by devnexen** [comment]
Closed as [aaabaa98](https://github.com/php/doc-en/commit/aaabaa98a82308ed1e135730982210ba8e024fe6)
