### ISSUE TITLE
datetime instance is changed when used in function argument ...  

### ISSUE THREAD

**Issue by srcmaker** [php/doc-en#1598]
From manual page: https://php.net/class.datetime

---
file test.php
---------------------------------------------------------------------------

function add3m($dtime){
    $dtime->add(new DateInterval('P03M'));
    return $dtime;
}

$now = new DateTime();
$after3m = add3m($now);

echo $now->format('Y-m-d H:i:s').PHP_EOL;
echo $after3m->format('Y-m-d H:i:s').PHP_EOL;

------------------------------------------------------------------------------

if you execute above file on cli, you see the same result.
$now gained 3 months by the add3m function like $after3m.

**Comment by cmb69** [comment]
That is how mutable objects behave. Consult any of the available [support channels](https://www.php.net/support) for further help.
