### ISSUE TITLE
DOMDocumentFragment::appendXML generates a warning with an "&" in an html-query-string.

### ISSUE THREAD

**Issue by henhenphp** [php/doc-en#1616]
From manual page: https://php.net/domdocumentfragment.appendxml

---
My environment is PHP 8.1.6 & Windows 10.

Try below.

$html_text = &#039;&lt;!DOCTYPE html&gt;&lt;html&gt;&lt;head&gt;&lt;/head&gt;&lt;body&gt;test&lt;/body&gt;&lt;/html&gt;&#039;;
$doc = new DOMDocument();
$doc-&gt;loadHTML($html_text, LIBXML_NOERROR);
$f = $doc-&gt;createDocumentFragment();

$data0 = &#039;&lt;a href="https://foo.net/index.php">no_query</a&gt;&#039;;
$data1 = &#039;&lt;a href="https://foo.net/index.php?lang=en">lang</a&gt;&#039;;
$data2 = &#039;&lt;a href="https://foo.net/index.php?lang=en&page=book.dom.php">lang_page</a&gt;&#039;;

$f-&gt;appendXML($data0); // no error
$f-&gt;appendXML($data1); // no error
$f-&gt;appendXML($data2); // warning

echo $doc-&gt;saveHTML();

As an extra request for this submitting page,
showing html tags is very difficult because some needs escape, but others not.

**Comment by cmb69** [comment]
Not quite sure if you actually intented to file this as a documentation bug, but in any way, I don't see a bug here. The documentation states "Append raw XML data", and an unescaped `&` is invalid XML.
