### ISSUE TITLE
Call to undefined method 

### ISSUE THREAD

**Issue by ziaratban** [php/doc-en#1617]
From manual page: https://php.net/class.mongodb-driver-monitoring-commandstartedevent

---

`Uncaught Error: Call to undefined method MongoDB\Driver\Monitoring\CommandStartedEvent::getServiceId() `

@jmikola

**Comment by jmikola** [comment]
Indeed, that was introduced in https://github.com/mongodb/mongo-php-driver/commit/594e83bad496a2753341a6af42183b54ee04bf6f ([PHPC-1976](https://jira.mongodb.org/browse/PHPC-1976)) and released in `ext-mongodb` 1.11.0.
