### ISSUE TITLE
array_fill() is missing boundary for $count

### ISSUE THREAD

**Issue by Geompse** [php/doc-en#1632]
From manual page: https://php.net/function.array-fill
Current version:
```
count
Number of elements to insert. Must be greater than or equal to zero
```
---

Since PHP 7 parameter $count of function array_fill() is limited to 0x7fffffff.

- PHP<7.0.0: (no warning)
- PHP>=7.0.0&&PHP<7.0.6: "Fatal error: Possible integer overflow in memory allocation (2147483648 * 32 + 32)"
- PHP>=7.0.6 && PHP<8.0.0: "Warning: array_fill(): Too many elements"
- PHP>=8.0.0: "array_fill(): Argument #​2 ($count) is too large"

Confirmed in source code: https://github.com/php/php-src/blob/e948d3c9c83231491b7b1e3fe1d8faa12efd0123/ext/standard/array.c#L2601

Confirmed in tests (please ignore memory exhaustion messages): https://3v4l.org/uJ3tU

---

Suggestion:
```
count
Number of elements to insert. Must be greater than or equal to zero. Since PHP 7, must be lower than or equal to 0x7fffffff (2147483647).
```

**Comment by cmb69** [comment]
Okay, let's ignore the behavior prior to PHP 7.0.6 (behavior prior to PHP 7.0.0 is irrelevant for the manual anyway).
