### ISSUE TITLE
document or ditch binary strings?

### ISSUE THREAD

**Issue by SpacePossum** [php/doc-en#1635]
Hi all,

Since PHP6 didn't see daylight I wonder, should we document its "relic concepts"?

The `binary string` concept has been removed (or not released) to some extend (  [is_binary](https://web.archive.org/web/20090403051843/http://us2.php.net/manual/en/function.is-binary.php) is not in the PHP API for example), 
however the `cast-lookalike` in the form of  `<?php $text = b"foo";`. is still valid PHP (it lints and runs on all the currents and including PHP8.2 nightly's).

So should we document `<?php $text = b"foo";` or could we deprecate the syntax and remove on PHP, any thoughts? :)

**Comment by mumumu** [comment]
> This came up recently somewhere else, but I can't find it.

Maybe, https://github.com/php/doc-en/pull/1626 ?

**Comment by SpacePossum** [comment]
ok, thanks all! thanks for link with more info, much appreciated :+1: 
I hope to see this syntax deprecated and removed in PHP9 :crossed_fingers: , but here is not the best spot to discuss
