### ISSUE TITLE
fpm delay deal with the request

### ISSUE THREAD

**Issue by immers** [php/doc-en#1638]
Hi all,
    I have a question ask for help. when i use php-fpm-5.3.6 with nginx  to accept  http request,  I find my request is delay 20ms before php-fpm to deal.   how i can do to resolve the problem?

<img width="1352" alt="ask" src="https://user-images.githubusercontent.com/23031978/174809335-9e69a044-0bd7-4cdd-9569-0a1f070af518.png">

**Comment by cmb69** [comment]
Please refer to any of the [available support channels](https://www.php.net/support), or some other support channels like StackOverflow. Thank you!
