### ISSUE TITLE
SimpleXMLIterator::current can no longer return null

### ISSUE THREAD

**Issue by AndrolGenhald** [php/doc-en#1640]
I haven't fully verified this in php-src, but based on [this test](https://3v4l.org/oLv9S) it appears that the null return was changed to an error.

The Description and Return Values sections [here](https://www.php.net/manual/en/simplexmliterator.current.php) mention null, and it also seems like the return value should be changed from `mixed` to `SimpleXMLIterator`, unless the description is wrong there as well.

If the return type is changed, it should also be changed [here](https://www.php.net/manual/en/class.simplexmliterator.php).

**Comment by cmb69** [comment]
Oh, it seems the documentation of SimpleXML is not up to date with PHP 8 at all, where the [iterator functionality has basically been moved to `SimpleXMLElement`](https://www.php.net/manual/en/migration80.other-changes.php#migration80.other-changes.extensions.simplexml).

**Comment by Girgias** [comment]
This looks like it has been fixed, please open a new issue if not.
