### ISSUE TITLE
grapheme_substr has incorrect return type

### ISSUE THREAD

**Issue by taka-oyama** [php/doc-en#1653]
From manual page: https://php.net/function.grapheme-substr

Doc says it returns `string|false` but that seems to have changed to `string` in PHP 8.0.

[substr](https://www.php.net/manual/en/function.substr.php) has the correct docs.

**Comment by cmb69** [comment]
Indeed, `grapheme_substr()` has been changed according to `substr()` (so the last sentence of the `$length` description is no longer true), but it still can return `false` on some conditions; see https://github.com/php/php-src/blob/master/ext/intl/grapheme/grapheme_string.c#L330-L538 (search for `RETURN_FALSE`).

**Comment by taka-oyama** [comment]
Thank you for pointing that out.
I will make sure to look through the source next time!

**Comment by cmb69** [comment]
> I will make sure to look through the source next time!

Ususally, you don't have to check the implementation, but rather only the stub file; in this case https://github.com/php/php-src/blob/42c57123e951dd025db84454cf6f80ca8e812429/ext/intl/php_intl.stub.php#L275.
