### ISSUE TITLE
fwrite() raises E_WARNING on failure

### ISSUE THREAD

**Issue by 8ctopus** [php/doc-en#1673]
From manual page: https://php.net/function.fwrite

The `fwrite` function throws an exception in some cases, the documentation should be updated to reflect this. Here's an example:

```php
$descriptorSpec = [
    // stdin
    0 => ["pipe", "r"],
    // stdout
    1 => ["pipe", "w"],
    // stderr
    2 => ["pipe", "w"],
];

// open process
$process = proc_open("wkhtmltopdf --enable-local-file-access --page-size {$options['paper']} --orientation {$options['orientation']} - -", $descriptorSpec, $pipes, null, null, null);

if (!is_resource($process)) {
    throw new Exception('wkhtmltopdf open process');
}

// write to stdin
fwrite($pipes[0], $this->renderHtml());
fclose($pipes[0]);
```

Exception `fwrite(): Write of 8089 bytes failed with errno=22 Invalid argument` occurs if wkhtmltopdf does not exist.

```
PHP 8.1.4 (cli) (built: Mar 16 2022 09:32:18) (NTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.1.4, Copyright (c) Zend Technologies
    with Xdebug v3.1.3, Copyright (c) 2002-2022, by Derick Rethans
```

**Comment by cmb69** [comment]
The exception is due to "with Xdebug v3.1.3". Without, that would just be a warning, but that should be mentioned in the docs nonetheless.

> if (!is_resource($process)) {

For forward compatibility, I suggest to check instead:

> if ($process === false) {

**Comment by 8ctopus** [comment]
@cmb69 Hello Christoph, thank you for the reply. Very interesting, I didn't know that Xdebug would throw exceptions in some cases. I'll look more closely into that.

**Comment by cmb69** [comment]
Hmm, actually I'm not sure whether Xdebug can convert warnings to exceptions; it allows to break program execution on warnings, though. But anyway, fwrite`()` is not supposed to throw; maybe there is some `error_handler` involved which does this.
