### ISSUE TITLE
typo - func_get_args() example #1

### ISSUE THREAD

**Issue by ajaxStardust** [php/doc-en#1676]
In the example code

`func_get_arg(1)`

the "s" is missing (e.g. func_get_arg_s_ ).

**Comment by damianwadley** [comment]
Uh, no. [func_get_arg](https://www.php.net/manual/en/function.func-get-arg.php) gets a single argument, [func_get_args](https://www.php.net/manual/en/function.func-get-args.php) gets all the arguments in an array. They're two different functions.
