### ISSUE TITLE
Undocumented change of pg_fetch_all

### ISSUE THREAD

**Issue by emkey08** [php/doc-en#1679]
From manual page: https://php.net/function.pg-fetch-all

Since PHP 8 (or maybe 8.1 - not sure), the return type of `pg_fetch_all` is `array`. However, in previous PHP versions, it actually was `array|false`, and `false` was returned in the very common case where a query didn't match any rows (like e.g. when doing a `SELECT *` on an empty table). Since PHP 8 (or 8.1), an empty array is returned instead of `false` in this case.

This change of return types should be documented within the changelog of `pg_fetch_all`, since this is a very important difference to know when using older PHP versions.

**Comment by cmb69** [comment]
Oh, right, this is only documented in the [migration guide](https://www.php.net/manual/en/migration80.incompatible.php#migration80.incompatible.pgsql) so far:

> pg_fetch_all()] will now return an empty array instead of false for result sets with zero rows.
