### ISSUE TITLE
Error in basic do {} while() example

### ISSUE THREAD

**Issue by gilbertoalbino** [php/doc-en#1681]
From manual page: https://php.net/control-structures.do.while

Where it reads:
_... There is just one syntax for do-while loops:_

```
<?php
$i = 0;
do {
    echo $i;
} while ($i > 0);
?>
```

Shouldn't it be?:

```
<?php
$i = 0;
do {
    echo $i;
} while ($i < 0);
?>
```

**Comment by Girgias** [comment]
Both of these code segments are identical

**Comment by gilbertoalbino** [comment]
@Girgias they are not!
The first (incorrect in the docs) is an infinite loop.
The last (corrected version) does what the text in the docs declares about do always running once. In the docs it is an infinite loop.
