### ISSUE TITLE
date function not clearly defined

### ISSUE THREAD

**Issue by raydleemsc** [php/doc-en#1698]
From manual page: https://php.net/function.date
"Returns a string formatted according to the given format string using the given integer timestamp (Unix timestamp) or the current time if no timestamp is given. In other words, timestamp is optional and defaults to the value of [time()](https://www.php.net/manual/en/function.time.php)."

From manual page: https://php.net/function.time
"Returns the current time measured in the number of seconds since the Unix Epoch (January 1 1970 00:00:00 GMT)."

"current time" and "current local time" are contradictory and liable to lead to confusion, but since the function time() is the default, both are wrong.

---

**Comment by damianwadley** [comment]
"current _local_ time" incorrectly implies there's some sort of significance to it being "local", so sure, that could be fixed. But I don't follow why "current time" is also wrong?

**Comment by raydleemsc** [comment]
Just in the sense that current time is not specific enough to describe the result of the time function.

**Comment by damianwadley** [comment]
Can you try to explain some more? How could it be more specific? What would you suggest as the fix?

**Comment by derickr** [comment]
I see no issue here, nor is "local" mentioned in the original phrasing in the manual as quoted here. I'm closing this.
