### ISSUE TITLE
SplFixedArray: invalid class synopsis

### ISSUE THREAD

**Issue by WinterSilence** [php/doc-en#1702]
[Reflection for PHP 7.4-8.1](https://3v4l.org/9Ko0l)
Synopsis not contains JsonSerializable and IteratorAggregate methods + Iterator methods not marked as deprecated/removed

**Comment by cmb69** [comment]
Hmm, looks good to me:

![Screenshot 2022-07-18 113408](https://user-images.githubusercontent.com/2306138/179484102-56546079-aeca-4e76-8610-64ac3148c2c8.gif)

![Screenshot 2022-07-18 113454](https://user-images.githubusercontent.com/2306138/179484219-e1373764-2bb8-4c51-8176-c70518e0a4e4.gif)

**Comment by WinterSilence** [comment]
@cmb69 look methods

**Comment by cmb69** [comment]
Ah, indeed. Thank you!

**Comment by Girgias** [comment]
@kocsismate would this be fixed by the stubs script?

**Comment by kocsismate** [comment]
> would this be fixed by the stubs script?

No, unfortunately, gen_stub.php cannot add new methodsynopses, but just correct them. Since a few days, it can validate though if something is missing (https://github.com/php/php-src/pull/9491):

```
Warning: Missing method synopsis for SplFixedArray::__serialize()
Warning: Missing method synopsis for SplFixedArray::__unserialize()
Warning: Missing method synopsis for SplFixedArray::getIterator()
Warning: Missing method synopsis for SplFixedArray::jsonSerialize()
```
