### ISSUE TITLE
Document requirements for ArrayObject $iteratorClass

### ISSUE THREAD

**Issue by AndrolGenhald** [php/doc-en#1707]
https://www.php.net/manual/en/arrayobject.construct.php

Under the Parameters section it says:

> iteratorClass
>     Specify the class that will be used for iteration of the [ArrayObject](https://www.php.net/manual/en/class.arrayobject.php) object. The class must implement [Iterator](https://www.php.net/manual/en/class.iterator.php).

I [tried](https://3v4l.org/fB9Zu) using a class that implements `Iterator` and it tells me that it has to be derived from `ArrayIterator`. This should be documented.

**Comment by cmb69** [comment]
Thanks for reporting!
