### ISSUE TITLE
Errata on CURLOPT_PROXY_SERVICE_NAME on curl_setopt documentation

### ISSUE THREAD

**Issue by ProceduralMan** [php/doc-en#1719]
Documentation says option is available since cURL 7.34.0

Official documentation says available since 7.43.0 for HTTP proxies, 7.49.0 for SOCKS5 proxies

Reference: [Official easy_setopt](https://curl.se/libcurl/c/CURLOPT_PROXY_SERVICE_NAME.html)

**Comment by cmb69** [comment]
Thank you!
