### ISSUE TITLE
ldap_set_option ($ds vs. null)

### ISSUE THREAD

**Issue by RichardNeill** [php/doc-en#1722]
The documentation for ldap_set_option() states that the first parameter should be an LDAP Connection object from ldap_connect().
However, this isn't always true. Here are 2 cases I found:

* For debugging, we should do this, ''before'' invoking ldap_connect():
``` ldap_set_option(NULL, LDAP_OPT_DEBUG_LEVEL,7); ```

* If we want to disable the TLS cert check, (as one might if doing an ldaps over ssh-port-forward during development), then we must also do:
```ldap_set_option(NULL, LDAP_OPT_X_TLS_REQUIRE_CERT,0);```
and not wait till after ldap_connect() and do:
```ldap_set_option($ds, LDAP_OPT_X_TLS_REQUIRE_CERT,0);```
which does not actually work.

**Comment by damianwadley** [comment]
[ldap_set_option](https://linux.die.net/man/3/ldap_set_option) can apply options globally or to individual connections. Settings like LDAP_OPT_DEBUG_LEVEL can be more useful globally, especially if you want debugging of the process of creating a connection. Others like LDAP_OPT_X_TLS_REQUIRE_CERT could make sense for individual connections, however PHP condenses a series of function calls like [ldap_init](https://linux.die.net/man/3/ldap_init) and [ldap_init_SSL](https://docs.oracle.com/cd/B28196_01/idmanage.1014/b15997/capi.htm#i721535) into one call to `ldap_connect`, so you might have to set something globally in order for it to take effect on a new connection.

**Comment by RichardNeill** [comment]
Thanks. That's exactly right. We need to fix that the PHP documentation for ldap_set_option() doesn't mention the idea that the first parameter can be (or in some cases must be) null, and instead, implies that you can't set an option until after you've done ldap_connect().

**Comment by damianwadley** [comment]
> the PHP documentation for ldap_set_option() doesn't mention the idea that the first parameter can be (or in some cases must be) null,

**Comment by QcFe** [comment]
I'm using PHP 8.2 and there are several inconsistencies in this all. First, _ldap_connect_ does not actually perform connection. It basically just inits the whole thing. First connection is done by _ldap_bind_. This is actually stated [here](https://www.php.net/manual/en/function.ldap-connect.php) and turning on debugging perfectly shows this behavior. 
Said, so, it would all make sense to be able to call _ldap_set_option_ on a "connection" object, however it wouldn't work (for sure it doesn't as of PHP 8.2), especially with TLS related options. But it seems many other options you could not be set if not globally. And the actual issue with documentation is there is no reference about which parameters _have to_ be specified together with a connection and which _haven't_.
