### ISSUE TITLE
DomDocument - same object id relates to different class

### ISSUE THREAD

**Issue by jifer** [php/doc-en#1733]
### Description

The following code:

```php
<?php

final class DD extends \DOMDocument {
	public static function create() {
		$dom = new self();
		$root = $dom->createElement('rootelement');
		$dom->appendChild($root);

		$firstChild = $dom->firstChild;

		var_dump(
			spl_object_id($firstChild->ownerDocument), // int(1)
			get_class($firstChild->ownerDocument), // string(2) "DD" - this is correct
		);

		return $firstChild;
	}
	
	public function myMethod(){}
}


$dd = DD::create();
var_dump(
	spl_object_id($dd->ownerDocument), // int(1)
	get_class($dd->ownerDocument), // string(11) "DOMDocument" - this is incorrect
	// $dd->ownerDocument->myMethod() // This will rise exception as myMethod doesn not exist on \DomDocument
);
```

Resulted in this output:
```
int(1)
string(2) "DD"
int(1)
string(11) "DOMDocument"
```

But I expected this output instead:
```
int(1)
string(2) "DD"
int(1)
string(2) "DD"
```

Both var_dumps operates on same object (`dom->firstChild->ownerDocument`) but when out of class scope it returns main class (`DomDocument`) instead of extension class (`DD`).
It seems I can reproduce it only when creating object via static method.
https://onlinephp.io/c/5d173

### PHP Version

8.2.0beta1, 8.1.9, 7.4.30

**Comment by jifer** [comment]
I create `DomDocument (X)`, next I'm adding `DomElement (A)` created using `DomDocument (X)` to that same `DomDocument (X)`. So it is obvieus that `DomElement (A)` is owned by `DomDocument (X)`. But due to some fancy internal mechanism `DomElement (A)` has completly new owner and it is some new, not known to me `DomDocument (Y)`.
Yeap... this sounds exactly like something expected.

**Comment by KapitanOczywisty** [comment]
@jifer All `DOM*` classes are just a representation for the internal XML structure, if all references to any `DOM*` object are removed, then that object is simply destroyed and freed from memory. XML structure is always the source of truth.

Simpler example:
```php
<?php

class DOMElement2 extends DOMElement {
    public $test = 0;
}

$dom = new DomDocument();
$dom->registerNodeClass('DOMElement', 'DOMElement2');
$root = $dom->createElement('rootelement');
$dom->appendChild($root);
$root->test = 100;
var_dump($dom->saveHTML(), $root->test, $dom->firstChild->test);
unset($root);
var_dump($dom->saveHTML(), $dom->firstChild->test);
```

```
string(28) "<rootelement></rootelement>
"
int(100)
int(100)
string(28) "<rootelement></rootelement>
"
int(0)
```

**Comment by cmb69** [comment]
> if all references to any `DOM*` object are removed, then that object is simply destroyed and freed from memory.

Right. And that implies that you can prevent the freeing by keeping a reference to the node.

**Comment by jifer** [comment]
Don't get me wrong - I do understand your explanation. I could even agree with reason to do that (free memory while processing DOM structure). But from OOP this is not what would anyone expect. If my main object has child and that child has reference to that parent object it should be that exact parent object.

That will be my new favorite example on job interviews - if someone will answer what object/class is returned - they are hired right away! :smiley:

If you insist that nothing should be done with that (no fix, no need to document this behavior) please close the topic.
Thank you and have nice day!

**Comment by KapitanOczywisty** [comment]
> But from OOP this is not what would anyone expect.

Still DOM library has weirder quirks than that :) Object transience is [already documented](https://www.php.net/manual/en/domdocument.registernodeclass.php#domdocument.registernodeclass.example.transient), so nothing more to do.
