### ISSUE TITLE
Obsolete reference on CURLOPT_MAXCONNECTS on curl_setopt documentation

### ISSUE THREAD

**Issue by ProceduralMan** [php/doc-en#1740]
From manual page: https://php.net/function.curl-setopt

---

Documentation says "When the limit is reached, CURLOPT_CLOSEPOLICY is used to determine which connection to close. "

Official documentation says "When reaching the maximum limit, curl closes the oldest one in the cache to prevent increasing the number of open connections."

Reference: [Official easy_setopt](https://curl.se/libcurl/c/CURLOPT_MAXCONNECTS.html)

Also, [header file](https://github.com/curl/curl/blob/master/include/curl/curl.h) marks the option CURLOPT_CLOSEPOLICY as obsolete on line 698

KR

**Comment by cmb69** [comment]
Right. Thanks for reporting. The PHP constant `CURLOPT_CLOSEPOLICY` and the related constants have been removed as of PHP 5.6.0 anyway.
