### ISSUE TITLE
crypt() update docu for no longer optional $salt 

### ISSUE THREAD

**Issue by Crizz0** [php/doc-en#1752]
From manual page: https://php.net/function.crypt

---
According to this: https://www.php.net/manual/en/function.crypt.php#refsect1-function.crypt-changelog the crypt function needs a bit more precise wording in sentences like:
> The salt parameter is optional. 

maybe something:
> The salt parameter is optional (< PHP 8.0). 

or something like this.

**Comment by cmb69** [comment]
Thank you!
