### ISSUE TITLE
Array destructuring documentation and list()

### ISSUE THREAD

**Issue by ollieread** [php/doc-en#1753]
There doesn't seem to be a page on array destructuring in the docs, but when google for "php array destructuring" the only php.net link that appears, is for `list()`.

![CleanShot 2022-08-17 at 11 47 37](https://user-images.githubusercontent.com/469515/185100494-76c7ad98-aa15-49d0-b15c-89efbb157e3f.png)

Interestingly, this displays the following text, that doesn't appear on the page, that I can fine.

> This enables destructuring of arrays with non-integer or non-sequential keys.

If I am understanding this correctly, the shorthand syntax of 

```php
[$one, $two] = $array;
```

Is identical to

```php
list($one, $two) = $array;
```

If this is the case, the `list()` page should be updated.

(RFC for feature: https://wiki.php.net/rfc/short_list_syntax)

**Comment by Girgias** [comment]
Fixed by #3957
