### ISSUE TITLE
array_fill documentation, when start_index is negative.

### ISSUE THREAD

**Issue by seeketh** [php/doc-en#1758]
On array_fill() manual page https://www.php.net/manual/en/function.array-fill.php, at the start_index parameter description it reads

> If start_index is negative, the first index of the returned array will be start_index and the following indices will start from zero (see [example](https://www.php.net/manual/en/function.array-fill.php#function.array-fill.example.basic)).

Example given

```
$b = array_fill(-2, 4, 'pear');
print_r($b);
```
Output from the documentation

```
Array
(
    [-2] => pear
    [0] => pear
    [1] => pear
    [2] => pear
)
```
Running the same example on PHP 8.1.7 (cli) (built: Jun  9 2022 14:21:07) (NTS), I get different indexing.

```
Array
(
    [-2] => pear
    [-1] => pear
    [0] => pear
    [1] => pear
)
```
Am I missing something here, or should the documentation get updated?

**Comment by Girgias** [comment]
Fixed by ce882c196dce81bf6bd4d94af4fa4110ddc49ef4
