### ISSUE TITLE
PHP Documentation not available at the url

### ISSUE THREAD

**Issue by optimizerpro** [php/doc-en#1763]
From manual page: https://php.net/intro.java

---
PHP Documentation not available at the url as i was looking for the php java integration documentation, referenced from many places to the given link.

**Comment by damianwadley** [comment]
Thanks to archive.org, I can see that page formed part of the documentation for an ext/java extension.

I managed to track down another page which states the extension was removed from PHP as of 5.0. It moved to PECL, and I don't even see it there anymore either.

Any resource telling you to go to that URL is _very_ out of date - in fact, anything that does not use "www.php.net" is going to be quite old - and you can safely assume that if the extension still exists somewhere that it is completely and utterly incompatible with modern PHP.

**Comment by damianwadley** [comment]
For reference: https://web.archive.org/web/20140715185743/http://us1.php.net/manual/en/intro.java.php
