### ISSUE TITLE
do-while y while tiene un comportamiento inusual cuando se suma 0.1 a la variable de control 

### ISSUE THREAD

**Issue by Luis-devs** [php/doc-en#1777]
`$x=0;

    do {
        echo "Valor de x: $x<br>";
        $x=$x+0.1;
    } while ($x<5);
    echo"<br>Valor final x: $x<br>";

/*
-Salida esperada
Valor de x: 0
Valor de x: 0.1
Valor de x: 0.2
Valor de x: 0.3
Valor de x: 0.4
Valor de x: 0.5
Valor de x: 0.6
Valor de x: 0.7
Valor de x: 0.8
Valor de x: 0.9
Valor de x: 1
Valor de x: 1.1
Valor de x: 1.2
Valor de x: 1.3
Valor de x: 1.4
Valor de x: 1.5
Valor de x: 1.6
Valor de x: 1.7
Valor de x: 1.8
Valor de x: 1.9
Valor de x: 2
Valor de x: 2.1
Valor de x: 2.2
Valor de x: 2.3
Valor de x: 2.4
Valor de x: 2.5
Valor de x: 2.6
Valor de x: 2.7
Valor de x: 2.8
Valor de x: 2.9
Valor de x: 3
Valor de x: 3.1
Valor de x: 3.2
Valor de x: 3.3
Valor de x: 3.4
Valor de x: 3.5
Valor de x: 3.6
Valor de x: 3.7
Valor de x: 3.8
Valor de x: 3.9
Valor de x: 4
Valor de x: 4.1
Valor de x: 4.2
Valor de x: 4.3
Valor de x: 4.4
Valor de x: 4.5
Valor de x: 4.6
Valor de x: 4.7
Valor de x: 4.8
Valor de x: 4.9

Valor final x: 5

-Salida ejecutada
Valor de x: 0
Valor de x: 0.1
Valor de x: 0.2
Valor de x: 0.3
Valor de x: 0.4
Valor de x: 0.5
Valor de x: 0.6
Valor de x: 0.7
Valor de x: 0.8
Valor de x: 0.9
Valor de x: 1
Valor de x: 1.1
Valor de x: 1.2
Valor de x: 1.3
Valor de x: 1.4
Valor de x: 1.5
Valor de x: 1.6
Valor de x: 1.7
Valor de x: 1.8
Valor de x: 1.9
Valor de x: 2
Valor de x: 2.1
Valor de x: 2.2
Valor de x: 2.3
Valor de x: 2.4
Valor de x: 2.5
Valor de x: 2.6
Valor de x: 2.7
Valor de x: 2.8
Valor de x: 2.9
Valor de x: 3
Valor de x: 3.1
Valor de x: 3.2
Valor de x: 3.3
Valor de x: 3.4
Valor de x: 3.5
Valor de x: 3.6
Valor de x: 3.7
Valor de x: 3.8
Valor de x: 3.9
Valor de x: 4
Valor de x: 4.1
Valor de x: 4.2
Valor de x: 4.3
Valor de x: 4.4
Valor de x: 4.5
Valor de x: 4.6
Valor de x: 4.7
Valor de x: 4.8
Valor de x: 4.9
Valor de x: 5

Valor final x: 5.1
*/

//Con while
   $x=0;
    while($x<5){
        echo "Valor de x: $x<br>";
        $x=$x+0.1;
    }
    echo"<br>Valor final x: $x<br>";

/*
-Salida esperada
Valor de x: 0
Valor de x: 0.1
Valor de x: 0.2
Valor de x: 0.3
Valor de x: 0.4
Valor de x: 0.5
Valor de x: 0.6
Valor de x: 0.7
Valor de x: 0.8
Valor de x: 0.9
Valor de x: 1
Valor de x: 1.1
Valor de x: 1.2
Valor de x: 1.3
Valor de x: 1.4
Valor de x: 1.5
Valor de x: 1.6
Valor de x: 1.7
Valor de x: 1.8
Valor de x: 1.9
Valor de x: 2
Valor de x: 2.1
Valor de x: 2.2
Valor de x: 2.3
Valor de x: 2.4
Valor de x: 2.5
Valor de x: 2.6
Valor de x: 2.7
Valor de x: 2.8
Valor de x: 2.9
Valor de x: 3
Valor de x: 3.1
Valor de x: 3.2
Valor de x: 3.3
Valor de x: 3.4
Valor de x: 3.5
Valor de x: 3.6
Valor de x: 3.7
Valor de x: 3.8
Valor de x: 3.9
Valor de x: 4
Valor de x: 4.1
Valor de x: 4.2
Valor de x: 4.3
Valor de x: 4.4
Valor de x: 4.5
Valor de x: 4.6
Valor de x: 4.7
Valor de x: 4.8
Valor de x: 4.9

Valor final x: 5

-Salida ejecutada
Valor de x: 0
Valor de x: 0.1
Valor de x: 0.2
Valor de x: 0.3
Valor de x: 0.4
Valor de x: 0.5
Valor de x: 0.6
Valor de x: 0.7
Valor de x: 0.8
Valor de x: 0.9
Valor de x: 1
Valor de x: 1.1
Valor de x: 1.2
Valor de x: 1.3
Valor de x: 1.4
Valor de x: 1.5
Valor de x: 1.6
Valor de x: 1.7
Valor de x: 1.8
Valor de x: 1.9
Valor de x: 2
Valor de x: 2.1
Valor de x: 2.2
Valor de x: 2.3
Valor de x: 2.4
Valor de x: 2.5
Valor de x: 2.6
Valor de x: 2.7
Valor de x: 2.8
Valor de x: 2.9
Valor de x: 3
Valor de x: 3.1
Valor de x: 3.2
Valor de x: 3.3
Valor de x: 3.4
Valor de x: 3.5
Valor de x: 3.6
Valor de x: 3.7
Valor de x: 3.8
Valor de x: 3.9
Valor de x: 4
Valor de x: 4.1
Valor de x: 4.2
Valor de x: 4.3
Valor de x: 4.4
Valor de x: 4.5
Valor de x: 4.6
Valor de x: 4.7
Valor de x: 4.8
Valor de x: 4.9
Valor de x: 5

Valor final x: 5.1
*/
`

**Comment by damianwadley** [comment]
Floating point values have a limited precision. Hence a value might not have the same string representation after any processing. That also includes writing a floating point value in your script and directly printing it without any mathematical operations.

If you would like to know more about "floats" and what IEEE 754 is, read this: http://www.floating-point-gui.de/
