### ISSUE TITLE
name time zone Kiev

### ISSUE THREAD

**Issue by DaZOr93** [php/doc-en#1790]
Fix name time zone Kiev
From manual page: https://php.net/timezones.europe

---

**Comment by saundefined** [comment]
Thanks for the issue,
timezone updated in 5a4f758ca6a49ee5b9ed01c337e5c077d0c26ca1

Actual name is `Europe/Kyiv`, the name `Europe/Kiev` can be used for backward compatibility.

**Comment by cmb69** [comment]
That has already been updated in the EN docs; is this about a translation?

**Comment by DaZOr93** [comment]
> Thanks for the issue, timezone updated in [5a4f758](https://github.com/php/doc-en/commit/5a4f758ca6a49ee5b9ed01c337e5c077d0c26ca1)
> 
> Actual name is `Europe/Kyiv`, the name `Europe/Kiev` can be used for backward compatibility.

I'm probably just confused. I'm using Laravel 9, and somewhere I saw that the timezone value is the same as in php, but with 'timezone' => 'Europe/Kyiv', I got an error, but Europe/Kiev works fine

**Comment by Girgias** [comment]
> 

Likely because this is only a recent change so you need an up to date PHP version (maybe only the latest one supports this?)
