### ISSUE TITLE
sleep() missing false return type

### ISSUE THREAD

**Issue by ChrisHSandN** [php/doc-en#1802]
From manual page: https://php.net/function.sleep

---

The function definition lists just `int` as the return type
```php
sleep(int $seconds): int
```

[Return Values](https://www.php.net/manual/en/function.fwrite.php#refsect1-function.fwrite-returnvalues) states
> Returns zero on success, or false on error.

**Comment by damianwadley** [comment]
As of PHP 8 it does only return `int` - the error case (providing a negative `$seconds`) now throws an exception.
