### ISSUE TITLE
How to understand "or doesn't terminate"

### ISSUE THREAD

**Issue by mowangjuanzi** [php/doc-en#1831]
in https://www.php.net/manual/en/migration81.new-features.php

> ## Never type
> A new return only type never has been added. This indicates that a function either [exit()](https://www.php.net/manual/en/function.exit.php), throws an exception, or doesn't terminate.

Can anyone provide an example of `or doesn't terminate`?

**Comment by damianwadley** [comment]
An infinite loop is the simplest an example of code that does not terminate:
```php
function doesnt_terminate(): never {
    while (true) { }
    echo "this statement will not execute";
}
```

**Comment by mowangjuanzi** [comment]
> An infinite loop is the simplest example of code that does not terminate:
> 
> ```
> function doesnt_terminate(): never {
>     while (true) { }
>     echo "this statement will not execute";
> }
> ```

I see.Thank you.
