### ISSUE TITLE
Documentation socket_addrinfo_lookup some inaccurate description

### ISSUE THREAD

**Issue by AtlanticF** [php/doc-en#1833]
Manual page: https://www.php.net/manual/en/function.socket-addrinfo-lookup.php#refsect1-function.socket-addrinfo-lookup-parameters

1. The explain for `service` parameter:

> The service to connect to. If service is a name, it is translated to the corresponding port number.

`If service is a name` is not precise to explain the parameter. I think it's better interpreted is: `If service is a service name in services`.
`services(5)` linux man page: https://man7.org/linux/man-pages/man5/services.5.html

2. The explain for `hints` parmaeter:

> Hints provide criteria for selecting addresses returned. You may specify the hints as defined by getadrinfo.

The last word: `getadrinfo`, should be replaced with "getaddrinfo"

**Comment by AtlanticF** [comment]
@cmb69 Hi  cmb，can you take a moment to look at this？Thanks a lot.

**Comment by cmb69** [comment]
> `If service is a name` is not precise to explain the parameter. I think it's better interpreted is: `If service is a service name in services`.
> `services(5)` linux man page: https://man7.org/linux/man-pages/man5/services.5.html

Hmm, what about operating systems other than Linux (or is services(5) a general POSIX thing)?

> The last word: `getadrinfo`, should be replaced with "getaddrinfo"

Right!

**Comment by cmb69** [comment]
> (or is services(5) a general POSIX thing)?

@devnexen, would you know?

**Comment by devnexen** [comment]
I can tell macOs, BSD have it too.

**Comment by AtlanticF** [comment]
> (or is services(5) a general POSIX thing)?

@cmb69  I can not find the `services(5)` definition in POSIX Std. It looks like a special implements on GNU/Linux.

I find the `getaddrinfo` specification: https://pubs.opengroup.org/onlinepubs/9699919799.2016edition/functions/getaddrinfo.html, but there's no specifically description for the argument `servname`.

Can we use "If service is a network service name" replace with "If service is a name"?

**Comment by cmb69** [comment]
Maybe we should target that from the other side, namely by stating something like: "If service is a numeric string, it designates the port. Otherwise it designates a network service name, which is mapped to a port by the operating system."
