### ISSUE TITLE
Wrong description on User Contributed Notes #127676

### ISSUE THREAD

**Issue by filvi** [php/doc-en#1850]
From manual page: https://php.net/simplexmlelement.xpath

---

# Error in the script written
Hi I wrote a piece of code in the User Contributed Notes accessible at the current link [https://www.php.net/manual/en/simplexmlelement.xpath.php#127676](https://www.php.net/manual/en/simplexmlelement.xpath.php#127676)

I pasted the wrong code there. Now I inserted the corrected version. I don't know how to delete it if you can help or delete my old code would be great 👍

**Comment by cmb69** [comment]
I have just deleted your previous note. Thanks for mentioning!
