### ISSUE TITLE
Numeric arrays wrong result 

### ISSUE THREAD

**Issue by ilyadrv** [php/doc-en#1872]
From manual page: https://php.net/function.http-build-query

```
urldecode(http_build_query(['var' => ['a','b','c']])) 
results
var[0]=a&var[1]=b&var[2]=c

expected
var[]=a&var[]=b&var[]=c
or
var=a&var=b&var=c
```
---

**Comment by cmb69** [comment]
Well, that is documented at https://www.php.net/function.http-build-query, second example. Are you suggesting this would be a bug?

**Comment by Girgias** [comment]
Closing as stale
