### ISSUE TITLE
socket_set_option() is for setting options

### ISSUE THREAD

**Issue by AtlanticF** [php/doc-en#1888]
Manual page: https://www.php.net/manual/en/function.socket-set-option.php#refsect1-function.socket-set-option-parameters

The explain for **level** parameter:

> The level parameter specifies the protocol level at which the option resides. For example, to retrieve options at the socket level, a level parameter of SOL_SOCKET would be used. ...

In this description `For example, to retrieve options at the socket level`, I think `to retrieve options` should be replace with `set options`, because this function is to **set** value instead of **get** value on the options.

**Comment by cmb69** [comment]
Thanks for reporting!
