### ISSUE TITLE
code error

### ISSUE THREAD

**Issue by mowangjuanzi** [php/doc-en#1893]
https://github.com/php/doc-en/blob/master/reference/misc/functions/halt-compiler.xml#L59

```diff
-__halt_compiler(); the installation data (eg. tar, gz, PHP, etc.)
+__halt_compiler();
+
+ // the installation data (eg. tar, gz, PHP, etc.)
```

is that so?

**Comment by damianwadley** [comment]
Yes and no: the "installation data" begins _immediately_ after the `__halt_compiler();` token. With
```php
__halt_compiler(); the installation data (eg. tar, gz, PHP, etc.)
```
the "installation data" is `\x20\x74\x68\x65...` - that is, it begins with that initial space. Writing
```php
__halt_compiler();

the installation data (eg. tar, gz, PHP, etc.)
```
changes the data to be two newlines (either `\x0d\x0a` or `\x0a`) followed by `\x74\x68\x65...`.

**Comment by mowangjuanzi** [comment]
So this is ok?

**Comment by Girgias** [comment]
Closing as stale and seemingly correct docs.
