### ISSUE TITLE
Narrow currency symbols

### ISSUE THREAD

**Issue by repli2dev** [php/doc-en#1897]
### Description

Current PHP versions support currency formatting showing "standard" currency symbols for various locales, such as `Kč`, `$` or `CA$`, however in some context it is bit unexpected for people to see the `CA$` as they expect what they see everyday `$`...

In terminology of the ICU library this is called a `narrow` unit symbol (see [docs](https://unicode-org.github.io/icu/userguide/format_parse/numbers/skeletons.html)).

Could the support for this be added?

**Comment by repli2dev** [comment]
@cmb69 agree, I could prepare the PR, though not sure what should be sufficient.

Suggestion: add to **See also** at https://www.php.net/manual/en/numberformatter.formatcurrency.php and https://www.php.net/manual/en/numberformatter.format.php

**Comment by cmb69** [comment]
> Suggestion: add to **See also** at https://www.php.net/manual/en/numberformatter.formatcurrency.php and https://www.php.net/manual/en/numberformatter.format.php

That would be a start, but I also suggest to add a respective example to https://www.php.net/manual/en/messageformatter.formatmessage.php.

**Comment by repli2dev** [comment]
@cmb69 thx for hint here's the PL.
