### ISSUE TITLE
Date example for "p" is misleading

### ISSUE THREAD

**Issue by Justinas-Jurciukonis** [php/doc-en#1899]
From manual page: https://php.net/datetime.format

---

Under `DateTime::format` _format_ table of possible formats there is newly added `p`.

p | The same as P, but returns Z instead of +00:00            (available as of PHP 8.0.0) | Example: +02:00
-- | -- | --

but example seems to be copied from `P`.

Should be changed to indicate possible value differences

p | The same as P, but returns Z instead of +00:00            (available as of PHP 8.0.0) | Example: Z or +02:00
-- | -- | --

**Comment by cmb69** [comment]
I don't think the example is incorrect, but rather that it can be improved.
