### ISSUE TITLE
Why `HTTP_ORIGIN` is not in the `$_SERVER` documentation?

### ISSUE THREAD

**Issue by stebogit** [php/doc-en#1901]
I noticed `HTTP_ORIGIN` is not listed in the [`$_SERVER` documentation](https://www.php.net/manual/en/reserved.variables.server.php). Since [`Origin`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Origin) is an important header for security, I think `HTTP_ORIGIN` should be mentioned in the docs.

Ref [SO](https://stackoverflow.com/questions/74118610/why-http-origin-is-not-in-the-server-documentation).

**Comment by damianwadley** [comment]
Actually I'd say the entire list of `HTTP_*` keys should get thrown out in favor of a single statement at the top that says something like

> In addition to the elements listed below, PHP will create additional elements with values from request headers. These entries will be named `HTTP_` followed by the header name, capitalized and with underscores instead of hyphens. For example, the `Accept-Language` header would be available as `HTTP_ACCEPT_LANGUAGE`.
