### ISSUE TITLE
A note on the session_unset() page regarding older deprecated code.

### ISSUE THREAD

**Issue by colshrapnel** [php/doc-en#1906]
On the [session_unset() page](https://www.php.net/manual/en/function.session-unset.php) there is a note, saying

> **Note:**
> Only use **session_unset()** for older deprecated code that does not use `$_SESSION`

I suppose it was a standard note that was added to all deprecated functions such as `session_register()`. Eventually such functions got removed, but `session_unset()` remains. Given there is no "older deprecated code" in the language anymore, I suppose this note is no longer relevant and could be removed? I mean, given the function stays, it means it's OK to use it?

**Comment by Girgias** [comment]
This function is equivalent to ``$_SESSION = []`` and from what I understand was meant to be used with ``$HTTP_SESSION_VARS``
