### ISSUE TITLE
It is not clear which current version is described in this documentation.

### ISSUE THREAD

**Issue by wb027** [php/doc-en#1908]
From manual page: https://php.net/index

---
I think it's a good idea to show the current version in the header at the top of every page.
Thanks for the great manual.

**Comment by Girgias** [comment]
The documentation documents the all versions from the current and previous major versions (i.e. from 7.x to 8.x) on the same page, so there is no point in having a current version number.

**Comment by cmb69** [comment]
> The documentation documents the all versions from the current and previous major versions (i.e. from 7.x to 8.x) on the same page, so there is no point in having a current version number.

Yep. And this is (indirectly) hinted at on https://www.php.net/docs.php:

> The PHP 4 and PHP 5 documentation has been removed from the manual, […]

In my opinion, this is sufficient, and adding the version info ("valid for PHP 7 and 8") on every page would be just noise.

**Comment by wb027** [comment]
> The documentation documents the all versions from the current and previous major versions (i.e. from 7.x to 8.x) on the same page, so there is no point in having a current version number.

Thanks, I know it. However, new versions are released quite often. When you're not a professional programmer, you don't keep track of updates all the time and you don't know the latest number.
It would be convenient to keep this information in front of your eyes. And best of all is the range of versions, for example 7.0-8.2. There is a lot of free space on the top bar.
On my personal site, I would do exactly that. :)
