### ISSUE TITLE
Hacktoberfest participation - doc-pt_br

### ISSUE THREAD

**Issue by rafaelbernard** [php/doc-en#1917]
Hello, PHP-mates!

I hope you are all doing fine. The doc-pt_br groups has been discussed about being a participant of [Hacktoberfest](https://hacktoberfest.com/) and [we all agreed that this can be very helpful for the project](https://github.com/php/doc-pt_br/issues/183), as we are an easy entry, we need contributors and still a lot of work to do. Hence, a perfect project to participate in.

We are not able to add `#hacktoberfest` as a topic to https://github.com/php/doc-pt_br. Can anyone with the rights do it on our behalf?

Best regards,
Rafael

**Comment by rafaelbernard** [comment]
Maybe also helpful for other PHP documentation projects. )))

**Comment by cmb69** [comment]
Done.
