### ISSUE TITLE
Doc comment must start with /** followed by whitespace

### ISSUE THREAD

**Issue by savedario** [php/doc-en#1919]
From manual page: https://php.net/reflectionclass.getdoccomment

---
A Doc comment, or DocBlock, MUST start with /** and nothing else after it.
E.g.:
```
/**x
 * Something
 */
class Foo
{
}

$ref = new ReflectionClass('Foo');
var_dump($ref->getDocComment());
```
outputs:
```
bool(false)
```

**Comment by cmb69** [comment]
Not sure what you are reporting. Is there a typo in the example? The EN version looks okay (the whitespace shouldn't matter: https://3v4l.org/PCHJr); or is this about some translation?

**Comment by savedario** [comment]
If this is not a bug, at least there's an inconsistency between the method's behaviour and its description.
If the above example had:
/**
the Doc comment would be detected.
Just trying to save someone else the 2 hours spent discovering this.

**Comment by savedario** [comment]
> Doc comments start with /**
is not enough.

**Comment by cmb69** [comment]
Ah, thank you, now I understand!
