### ISSUE TITLE
'undefined function dl()'

### ISSUE THREAD

**Issue by odsantos** [php/doc-en#1950]
From manual page: https://php.net/function.extension-loaded

---

Hi,

This example in the page above,

```
<?php
if (!extension_loaded('gd')) {
    if (!dl('gd.so')) {
        exit;
    }
}
?>
```

Yields the following error:

"Fatal error: Uncaught Error: Call to undefined function dl() in ..."

Please, is it related to the fact of `dl()` being deprecated, as reported by checking compatibility software?

Thanks.

**Comment by cmb69** [comment]
From the [`dl()` documentation](https://www.php.net/manual/en/function.dl.php):

> This function is only available for the CLI and embed SAPIs, and the CGI SAPI when run from the command line.

So in a Webserver context, `dl()` is not available.
