### ISSUE TITLE
Described method `hasPrototype` doesn't exist in PHP 8.1.11

### ISSUE THREAD

**Issue by blazeyo** [php/doc-en#1993]
From manual page: https://php.net/class.reflectionmethod

---

It looks like there is no method called `hasPrototype` in PHP 8.1.11

**Comment by damianwadley** [comment]
That's right.

https://www.php.net/manual/en/reflectionmethod.hasprototype.php

> ReflectionMethod::hasPrototype
> (PHP 8 >= 8.2.0)
>
> ReflectionMethod::hasPrototype — Returns whether a method has a prototype

**Comment by blazeyo** [comment]
Wow, that was fast! :). Thanks the answer. You are right of course, I must have been looking at the getPrototype page when checking the version.
