### ISSUE TITLE
Please add timeZone and language HINDI

### ISSUE THREAD

**Issue by bcapd7363q** [php/doc-en#2012]
From manual page: https://php.net/timezones.indian

---
<html><body>

Country: | state:
-- | --
India| Telangana
17°22'N / 78°28'E |default_latitude/default_longitude
06:20↑ 109° East /17:40↑ 251° West | sunrise_zenith/sunset_zenith
Indian Rupee (INR) |  ₹ 1000
English, Telugu, Urdu | mbstring.language
+91 | 9937090484@JIO

</body>
</html>Country: 	[India](https://www.timeanddate.com/worldclock/india)
State: 	[Telangana](https://www.timeanddate.com/worldclock/india/telangana)
Lat/Long: 	17°22'N / 78°28'E
Elevation: 	507 m
Currency: 	Indian Rupee (INR)
Languages: 	English, Telugu, Urdu
Country Code: 	+91

**Comment by damianwadley** [comment]
That is not how timezones work. PHP also does not control timezone data.

https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
https://en.wikipedia.org/wiki/Tz_database

I don't know what you're asking for regarding the Hindi language, but PHP does not control internationalization data either.

https://cldr.unicode.org/
