### ISSUE TITLE
Doesn't work on PHP 8.1

### ISSUE THREAD

**Issue by pmsmiers** [php/doc-en#2028]
From manual page: https://php.net/book.trader

I'm waiting a long time now for someone who can update this version so it works with PHP 8.1 (8.1.12 at this moment).
I'm using Ubuntu with PHP 8.0 and it works great but I really like to move to PHP 8.1

**Comment by Girgias** [comment]
This is not a doc issue, please open an issue on the relevant project: https://github.com/php/pecl-math-trader
