### ISSUE TITLE
White page

### ISSUE THREAD

**Issue by Naoufal69** [php/doc-en#2031]
From manual page: https://php.net/function.ming-setscale
There is nothing on this page
---

**Comment by cmb69** [comment]
Hmm, that is supposed to redirect to https://www.php.net/manual-lookup.php?pattern=function.ming-setscale&lang=en&scope=404quickref. Which language have you set? (check the `LAST_LANG` cookie)

**Comment by Girgias** [comment]
The redirect works for me aswell: https://www.php.net/manual-lookup.php?pattern=function.ming-setscale&lang=en&scope=404quickref is where I land

**Comment by Girgias** [comment]
Stale + can't reproduce
