### ISSUE TITLE
imagesavealpha - Does this also work for WebP files?

### ISSUE THREAD

**Issue by porg** [php/doc-en#2041]
From manual page: https://php.net/function.imagesavealpha

> imagesavealpha() sets the flag which determines whether to retain full alpha channel information (as opposed to single-color transparency) when saving PNG images.

---

- Is this also supported for WebP files?
- The manual revision seems to be from a time where PNG was the only image file format on the web to support alpha channels.
- Would appreciate an official update to the docs here
- The Wordpress image team would like to know this for its decision making, see:
[Criteria for Responsive Images of WebP: Preserve Alpha + Preserve Lossless + Smaller in size than original](https://core.trac.wordpress.org/ticket/57238#comment:1)

**Comment by cmb69** [comment]
Ugh, apparently saving as WebP *always* saves the alpha channel, even if `imagesavealpha($im, false)` is called. AVIF has the same issue.

So the documentation is actually correct, but I think not heeding `imagesavealpha()` is actually an implementation bug (albeit fixing it would break code which relies on the current behavior).

**Comment by porg** [comment]
> In case of WebP and AVIV files an alpha channel is always saved regardless of the true/false argument.

An explicit mention like this in the documentation would help! Could you add it?

**Comment by cmb69** [comment]
> 2\. When will this update go live in the online manual?

We deploy every four hours, so this shouldn't take long.
