### ISSUE TITLE
PHP 8 - Seems like is_a() function doesn't work properly 

### ISSUE THREAD

**Issue by SteeveMbr1** [php/doc-en#2045]
From manual page: https://php.net/function.is-a

---

I have this issue :

`var_dump(is_a(Entity::class, Entity::class));`
return
`bool(false)`

**Comment by damianwadley** [comment]
https://www.php.net/manual/en/function.is-a.php
> allow_string
> If this parameter set to false, string class name as object_or_class is not allowed. This also prevents from calling autoloader if the class doesn't exist.
