### ISSUE TITLE
setcookie() datetime format change in 8.2 is undocumented

### ISSUE THREAD

**Issue by ReedyBear** [php/doc-en#2049]
In php 8.1 and below, the cookie `expires` datetime format sent to the browser is `D, d-M-Y H:i:s e`. In php 8.2, it is `D, d M Y H:i:s e`

This is discussed in issue https://github.com/php/php-src/issues/9200

This change is not documented in [`setcookie()`](https://www.php.net/manual/en/function.setcookie.php) or [php 8.2 backward incompatible changes](https://www.php.net/manual/en/migration82.incompatible.php)

**Comment by cmb69** [comment]
Hmm, I'm not sure this change is really worth to be documented. After all, the `setcookie()` documentation already mentions RFC 6265, and we're still conforming to that.

What's your particular use-case to consider this a breaking change?

**Comment by ReedyBear** [comment]
In a test, I'm making a request using curl & receive a cookie. I parse the 'expires' datetime string from the cookie. The php 8.2 upgrade broke this, and now I have extra logic so the test is backward compatabile. So now I date_create_from_format('D, d-M-Y H:i:s e', $cookie_expires_value) & if that returns false, I date_create_from_format with the 8.2 format 'D, d M Y H:i:s e'.

**Comment by cmb69** [comment]
Okay, let's document it then; it's not hard to do, and may save others some time.
