### ISSUE TITLE
DateTime::createFromFormat() does not accept DateTime

### ISSUE THREAD

**Issue by ProceduralMan** [php/doc-en#2071]
From manual page: https://php.net/datetime.createfromformat

---

Manual says [date_create_from_format](https://www.php.net/manual/en/function.date-create-from-format.php)(string $format, string $datetime, ?[DateTimeZone](https://www.php.net/manual/en/class.datetimezone.php) $timezone = null): [DateTime](https://www.php.net/manual/en/class.datetime.php)|false gets a DateTime object as its first argument

But the primitive clearly show a $format string as it 's first one...

Cheers!

**Comment by ProceduralMan** [comment]
Also, the format link does not work... it is pointing to https://www.php.net/images/bg-texture-00.svg

**Comment by cmb69** [comment]
> Manual says [date_create_from_format](https://www.php.net/manual/en/function.date-create-from-format.php)(string $format, string $datetime, ?[DateTimeZone](https://www.php.net/manual/en/class.datetimezone.php) $timezone = null): [DateTime](https://www.php.net/manual/en/class.datetime.php)|false gets a DateTime object as its first argument

That is indeed nonsense.

> Also, the format link does not work... it is pointing to https://www.php.net/images/bg-texture-00.svg

I cannot reproduce this. These "links" are only relevant for JS, and should scroll to the respective parameters, if these parameters are defined on the page. If there is no definition, the "links" should be no-ops. Is this perhaps related to your language (bg)?

**Comment by ProceduralMan** [comment]
Hi cmb69 thanks for commenting!

I am looking at the english manual on Firefox... can it be a firefox issue?

Yeah, it definitively is... Chrome/Chromium still see the **stronged** parameters as links (mouse pointer changes from arrow to hand) but do not allow you to get the link (Firefox does)

> These "links" are only relevant for JS, and should scroll to the respective parameters, if these parameters are defined on the page.

Ok, as on the related page they are not cited elsewhere I coul not see the use but looking at https://www.php.net/manual/en/function.mb-strcut.php I have been able to see the logic of those inner links. I was thining they should send me to the formats explanantion page or the datetime definitionb page but they are page-internal ones...

Just forget about the links

**Comment by cmb69** [comment]
> I am looking at the english manual on Firefox... can it be a firefox issue?
> 
> Yeah, it definitively is... Chrome/Chromium still see the **stronged** parameters as links (mouse pointer changes from arrow to hand) but do not allow you to get the link (Firefox does)

Hmm, this works for me in Firefox like in Chrome, but I think we should not change the cursor if the text is not linked in any way (i.e. since the linking is done via JS, the cursor should only be set via JS as well).
