### ISSUE TITLE
SplFixedArray shows Iterator methods from PHP 7

### ISSUE THREAD

**Issue by othercorey** [php/doc-en#2083]
`SplFixedArray` extends `IteratorAggregate` in PHP 8 and no longer implements the `Iterator` functions:

* current
* key
* next
* rewind
* valid

https://www.php.net/manual/en/class.splfixedarray

**Comment by othercorey** [comment]
I can update this next time I have this repo synced if not fixed by then.

**Comment by cmb69** [comment]
As it is now, the documentation is simply wrong. I wonder, though, how we can solve this, so the docs are correct for PHP 7 and 8. Maybe it is sufficient to document PHP 8, and to have only the changelog entry (implements Iterator → implements IteratorAggregate); might still be confusing for those still using PHP 7.

**Comment by othercorey** [comment]
I think only way is an 8.0 changelog on the class showing the change.

**Comment by jhdxr** [comment]
> I wonder, though, how we can solve this, so the docs are correct for PHP 7 and 8.

I think we can make the php 8 one as main/default, while have a separate one for php7, like what we did for `implode`, but this time it's a whole class instead of one function.

**Comment by Girgias** [comment]
Closing as there is a changelog now, please open a new issue if someone considers this to still need fixing.

**Comment by mvorisek** [comment]
https://www.php.net/manual/en/class.splfixedarray.php site should show that for each removed method and also on each removed method site like https://www.php.net/manual/en/splfixedarray.key.php
