### ISSUE TITLE
mysqli default charset

### ISSUE THREAD

**Issue by the6thBook** [php/doc-en#2088]
From manual page: https://php.net/mysqlinfo.concepts.charset

Can we get directions on how to set the default charset for mysqli?  
It seems like we should be able to set in php.ini:
mysqli.set_charset_name="utf8"

Or get this added?

I have the database variable "character_set_client" set to "utf8", but it seems like php mysqli always defaults to latin1.

Thanks!

---

**Comment by damianwadley** [comment]
I'm not sure I follow. You were clearly looking at the manual page for character sets, whose very first paragraph is

> Ideally a proper character set will be set at the server level, and doing this is described within the [» Character Set Configuration](http://dev.mysql.com/doc/mysql/en/charset-configuration.html) section of the MySQL Server manual. Alternatively, each MySQL API offers a method to set the character set at runtime.

and then goes on to give example code for the latter. What sort of "directions" are you looking for?

**Comment by the6thBook** [comment]
> I'm not sure I follow. You were clearly looking at the manual page for character sets, whose very first paragraph is
> 
> > Ideally a proper character set will be set at the server level, and doing this is described within the [» Character Set Configuration](http://dev.mysql.com/doc/mysql/en/charset-configuration.html) section of the MySQL Server manual. Alternatively, each MySQL API offers a method to set the character set at runtime.
> 
> and then goes on to give example code for the latter. What sort of "directions" are you looking for?

I have these set on the mysql server level.  However, when I connect with mysqli in php and run  get_charset() always returns "latin1" on RHEL and ubuntu always returns "utf8mb4" no matter what is set on the mysql server.

https://www.php.net/manual/en/mysqli.construct.php  states:
"Note:
    MySQLnd always assumes the server default charset. This charset is sent during connection hand-shake/authentication, which mysqlnd will use.
    Libmysqlclient uses the default charset set in the my.cnf or by an explicit call to [mysqli_options()](https://www.php.net/manual/en/mysqli.options.php) prior to calling [mysqli_real_connect()](https://www.php.net/manual/en/mysqli.real-connect.php), but after [mysqli_init()](https://www.php.net/manual/en/mysqli.init.php)."

However, my.cnf doesn't seem to effect php mysqli.  I've tried both:
[client]
default-character-set="latin1"
and
[mysql]
default-character-set="latin1"

It only seems to effect the mysql client program and not php mysqli.  Of course I can set it with mysqli->set_charset() or wrap the mysqli, but this seems like overhead instead of just having it set somewhere like php.ini.

**Comment by cmb69** [comment]
Check whether these mysqli builds use mysqlnd or libmysql-client (see PHP info, `Client API library version`). That could explain the different behavior.

**Comment by the6thBook** [comment]
> Check whether these mysqli builds use mysqlnd or libmysql-client (see PHP info, `Client API library version`). That could explain the different behavior.

Both show mysqlnd
echo mysqli_get_client_info();
mysqlnd 7.4.3

So again, the php documentation states:
"MySQLnd always assumes the server default charset. "

It seems like mysqlnd assumes its own charset based on whoever compiled it and not what the mysql servers values are.

**Comment by kamil-tekiela** [comment]
Maybe the sentence isn't worded the best, but it does explain how it works:

> MySQLnd always assumes the server default charset. This charset is sent during connection hand-shake/authentication, which mysqlnd will use.

So mysqlnd WILL NOT read contents of my.cnf file. It will accept the charset that the server sends. How to set the default global charset on your server is out of scope for PHP manual. 

While we appreciate this report, I am going to make a decision that there is no need to improve this particular part of the documentation. But if you or anyone else has an idea of how to make it even better, PRs are welcome.
