### ISSUE TITLE
Some Bug in ! (not operators)

### ISSUE THREAD

**Issue by infoh7052** [php/doc-en#2099]
Recently I was learning about operators in the page but I saw that the information given in this page is not operators that real project may not work error gives 

`,?php
 // not operators

          echo "<h3> xor Operators </h3>";

          echo "<br>";
  
          $myVar = (true ! true);
          echo "<br>";
          echo var_dump($myVar);
          echo "<br>";
          $myVar = (false ! true);
          echo "<br>";
          echo var_dump($myVar);
          echo "<br>";
          $myVar = (false ! false);
          echo "<br>";
          echo var_dump($myVar);
          echo "<br>";
          $myVar = (true ! false);
          echo "<br>";
          echo var_dump($myVar);
          echo "<br>";

?>`

 From manual page: https://php.net/language.operators.logical

---

**Comment by damianwadley** [comment]
`!` is not a binary operator, meaning it does not go in between two operands (expressions). It is a unary operator, meaning it goes in front of a single operand.

```php
$myVar = (! true);
```

Also it is incorrect to try to output the return value of `var_dump` because that function has no return value.
