### ISSUE TITLE
NGINX is misconfigured for 404 pages

### ISSUE THREAD

**Issue by afilina** [php/doc-en#2106]
This conversation from the mailing list about a misconfigured NGINX did not yield any action:
https://marc.info/?l=phpdoc&m=161875795124552&w=2

Can I assist in fixing the NGINX configuration in any way?

This is blocking at least one PR: https://github.com/php/doc-en/pull/551#pullrequestreview-645761987

**Comment by heiglandreas** [comment]
My setup does 't work anymore. I first need to solve that to be able to log in again. Might not be in the next 24 hours. As soon as it wirks again I'll contact @afilina and we can then fix that (if I'm able to fix it in the first place re.access rights)

**Comment by heiglandreas** [comment]
So it looks like my 2FA setup is broken. Will need to fix that first...

**Comment by Girgias** [comment]
This is an infra issue not doc-en.
