### ISSUE TITLE
The example code of mb_strimwidth contains invisible characters and causes error when being used

### ISSUE THREAD

**Issue by ianthedev** [php/doc-en#2109]
The [example code of `mb_strimwidth`](https://www.php.net/manual/en/function.mb-strimwidth.php#refsect1-function.mb-strimwidth-examples) contains invisible characters. If users copy that code and use the code for test or development, a syntax error occurs.

Here is an [online demo](https://www.tehplayground.com/eHBImYdfBSakMbyD).

**Comment by damianwadley** [comment]
Are you using Firefox?

**Comment by ianthedev** [comment]
> Are you using Firefox?

Yes.

**Comment by damianwadley** [comment]
Then that makes this a duplicate of https://github.com/php/phd/issues/71.
