### ISSUE TITLE
Typo in unpacking

### ISSUE THREAD

**Issue by ks74** [php/doc-en#2115]
From manual page: https://php.net/language.types.array
---

In "Array unpacking", this:
An array prefixed by ... will be expanded in place during the definition of the array.
should be changed to this:
An array prefixed by ... will be expanded in place during the definition of another array.

Because the defined array is not the unpacked one.

**Comment by cmb69** [comment]
Yeah, this is a bit misleading, but I don't like to mention "another array". Instead I'll go with the wording in the [respective RFC](https://wiki.php.net/rfc/spread_operator_for_array).

**Comment by ks74** [comment]
That's fine, I only suggested one way to fix it.
