### ISSUE TITLE
ReflectionFunction has isStatic, but missing in docs

### ISSUE THREAD

**Issue by henze-housepedia** [php/doc-en#2136]
https://www.php.net/manual/en/class.reflectionfunction.php.

ReflectionFunction has isStatic, but is missing in the docs. there is no mention of it, nor a page on it's own.

**Comment by henzeb** [comment]
In ReflectionFunctionAbstract it is not mentioned either.

Will that be fixed?

**Comment by cmb69** [comment]
It takes some hours until the fix is available on the php.net Website.

**Comment by henzeb** [comment]
I know, I just didn't see a related PR. I may have overlooked though.
