### ISSUE TITLE
Traits Conflict Resolution Example Error

### ISSUE THREAD

**Issue by Sunthief** [php/doc-en#2142]
From manual page: https://php.net/language.oop5.traits
---
Example # 13 Conflict Resolution:
```
trait PropertiesTrait {
    public $same = true;
    public $different1 = false;
    public bool $different2;
    readonly public bool $different3;
}

class PropertiesExample {
    use PropertiesTrait;
    public $same = true;
    public $different1 = true; // Fatal error
    public string $different2; // Fatal error
    readonly public bool $different3; // Fatal error
}
```
The last example `readonly public bool $different3; // Fatal error`  does in fact not create a fatal error as both properties in the trait and class are exactly the same and thus compatible.

**Comment by cmb69** [comment]
Indeed, that comment is wrong. I assume the intention was to have the `readonly` only on the class or on the trait. @Girgias?

**Comment by Girgias** [comment]
Ah yes otherwise this doesn't make a lot of sense.
