### ISSUE TITLE
var_export() added leading backslashes in PHP 8.2

### ISSUE THREAD

**Issue by sbarex** [php/doc-en#2145]
### Description

The official documentation says:
> **When var_export() exports objects, the leading backslash is not included in the class name of namespaced classes for maximum compatibility.**

This is correct until PHP 8.1.13. With PHP 8.2.0 the leading backslash **is included**.

The following code:

```php
<?php
namespace Test1;
class MyClass {
}

$test = new MyClass();

echo var_export($test, true);

```

Resulted in this output:
```php
\Test1\MyClass::__set_state(array(
))
```

But I expected this output instead:
```php
Test1\MyClass::__set_state(array(
))
```

### PHP Version

PHP 8.2.0

### Operating System

MacOS 13.1 intel

**Comment by iluuu1994** [comment]
Oops, looks like I forgot the NEWS entry, sorry!

**Comment by cmb69** [comment]
> Oops, looks like I forgot the NEWS entry, sorry!

No worries! The doc team doesn't look at NEWS anyway. Anything that needs to be documented, should have an entry in UPGRADING as well.
