### ISSUE TITLE
STREAM_CRYPTO_METHOD_TLSv1_3_CLIENT and STREAM_CRYPTO_METHOD_TLSv1_3_SERVER are undocumented

### ISSUE THREAD

**Issue by alexhenrie** [php/doc-en#2148]
`STREAM_CRYPTO_METHOD_TLSv1_3_CLIENT` and `STREAM_CRYPTO_METHOD_TLSv1_3_SERVER` were [added](https://github.com/php/php-src/commit/5c05f5e6d3d31a03c152fe90697bdc3e33193ced) in PHP 7.4.0, but are not mentioned in the [stream_socket_enable_crypto documentation](https://www.php.net/manual/en/function.stream-socket-enable-crypto.php) ([stream-socket-enable-crypto.xml](https://github.com/php/doc-en/blob/master/reference/stream/functions/stream-socket-enable-crypto.xml))

**Comment by cmb69** [comment]
Thank you!

**Comment by alexhenrie** [comment]
You're welcome! Thanks for the quick fix!
