### ISSUE TITLE
`stdClass` is spelled in different cases: `StdClass` / `stdclass`

### ISSUE THREAD

**Issue by nsfisis** [php/doc-en#2156]
Because class names in PHP are case-insensitive, `StdClass` and `stdclass` are exactly the same as `stdClass`. In the official manual, however, it is better to use consistent case.

```
$ git grep -hio stdclass | sort | uniq -c
  46 StdClass
 207 stdClass
  21 stdclass
```

**Comment by cmb69** [comment]
Indeed. Thanks for reporting!

> 21 stdclass

Most of these are parts of IDs, and these are supposed to be lowercased.
