### ISSUE TITLE
microtime missing user contributed notes

### ISSUE THREAD

**Issue by ChrisHSandN** [php/doc-en#2167]
Sometime between [August 2022](https://web.archive.org/web/20220816183441/https://www.php.net/manual/en/function.microtime.php)  and [October 2022](https://web.archive.org/web/20221001132811/https://www.php.net/manual/en/function.microtime.php) all the comments seem to have disappeared off the microtime docs page: https://www.php.net/manual/en/function.microtime.php

Admittedly, the php.net comments do need to be used carefully!  However it would be a real shame if a bug was sporadically wiping them and losing the useful snippets of information they often hold.

**Comment by cmb69** [comment]
The notes have deliberately been purged, and the [useful information has been incorporated into the manual proper](https://github.com/php/doc-en/commit/5c951013ca04161992efed8b86fb40f55669958e). This is actually how these user notes are supposed to be handled (although the doc team has hard time to catch up, due to the sheer amount of notes).

If you think that any particular note contained relevant information, which is not covered in the manual proper, please list that. Ideally, submit a pull request.

**Comment by ChrisHSandN** [comment]
Sometimes the notes point out errata or extra points which make sense to amalgamate into the docs but often they contain comments and code snippets which are useful but have no real place being put in the official docs.

Taking the top rated purged notes from this page as an example, the following knowledge has been lost:

1. A useful technique for calculating execution time with only a single variable.
2. A warning about how PHP uses `gettimebyday(2)` and this relies on the underlying server clock time.
3. A note that the string returned by `microtime()` can omit the decimal place and trailing digits under whole second conditions.
4. A warning to ensure your precision is set high enough when dealing with the floating point arithmetic.

The only change made to the docs when the notes were purged was the sentence:
> expressed in seconds as a decimal fraction

**Comment by cmb69** [comment]
@derickr, thoughts about adding more of the purged user notes into the manual proper?

**Comment by ollieread** [comment]
@cmb69 is there a way to programmatically collect the notes? I would be more than happy to sink some time into collating them and trying to identify what is useful, or at least, put forward a collection for others to review.

**Comment by derickr** [comment]
On Wed, 11 Jan 2023, Christoph M. Becker wrote:

> @derickr, thoughts about adding more of the purged user notes into the manual proper?

I added everything that I thought was useful. The notes were never meant 
to store or collect user snippets, and that's why I have removed them.

cheers,
Derick

**Comment by ChrisHSandN** [comment]
I appreciate that the comment section might not have been conceived that way but it’s universally how it seems to be used.

In my humble developer’s opinion, a well stocked “notes” section (even if it contains some dubious quality code snippets) is more useful than one which has been emptied for the sake of neatness. The voting system ensures that the most useful float to the top.

**Comment by derickr** [comment]
I don't think there is anything to be done here, so I am closing this.
