### ISSUE TITLE
Remove opcache.fast_shutdown from OPcache installation page

### ISSUE THREAD

**Issue by jnoordsij** [php/doc-en#2172]
Browsing through the docs, I noticed `opcache.fast_shutdown=1` being listed as recommended on the [OPcache installation page](https://www.php.net/manual/en/opcache.installation.php). After looking it up however, I found out this directive [has been removed since PHP 7.2.0](https://www.php.net/manual/en/opcache.configuration.php#ini.opcache.fast-shutdown). So it may as well be removed from the recommended settings.

Note: I'm not sure if this is kept around intentionally to still have it around for people using unmaintained PHP versions. If that is the case, feel free to disregard this until documentation for older versions is dropped.

**Comment by cmb69** [comment]
Indeed, the PHP manual is currently supposed to document PHP 7 and 8, and it doesn't harm to specifiy unsupported options in php.ini. That said, I think it makes still sense to point that out, and that should make it easier to remember to remove it, when the manual no longer documents that PHP versions.
