### ISSUE TITLE
Default flags for html* functions seem to have been updated in error

### ISSUE THREAD

**Issue by afilina** [php/doc-en#2178]
I'm confused about PR [1052](https://github.com/php/doc-en/pull/1052/files#diff-8a0ce0b44a3ec7d565f2d32e069d3250df65dbba8b9f22f73e63eb780b53c3f8L11-R14) which documents default flags as `ENT_QUOTES | ENT_SUBSTITUTE | ENT_HTML401` when the latest changes in [php-src](https://github.com/php/php-src/commit/50eca61f68815005f3b0f808578cc1ce3b4297f0#diff-43921c3b23decd3f0564bb082af2a9f8905daa7705757541c505f501ecd8e2c5R1316-R1322) seem to indicate `ENT_QUOTES | ENT_SUBSTITUTE`. The linked commit is the latest for that file. Where does `ENT_HTML401` come from?

Further references also refer to only `ENT_QUOTES | ENT_SUBSTITUTE`:
- [Upgrade guide](https://github.com/php/php-src/blob/28a1a6be0873a109cb02ba32784bf046b87a02e4/UPGRADING#L149-L154)

**Comment by cmb69** [comment]
[`ENT_HTML401 === 0`](https://3v4l.org/nrMiF); https://github.com/php/php-src/pull/7514 added that to the stubs, and the docs are usually generated from those. Maybe we should fix the changelog accordingly.

**Comment by afilina** [comment]
Ah, I haven't considered that its value could be 0, thus making it [part of the flags](https://3v4l.org/DEqrQ) without explicitly specifying in php-src. That makes sense.

The signature and changelog on these pages is therefore correct, but not the upgrading notes. I can update the upgrading notes.
