### ISSUE TITLE
ValueErrors thrown by shmop_*() are not documented

### ISSUE THREAD

**Issue by othercorey** [php/doc-en#2184]
In https://github.com/php/php-src/commit/d54bc295409663abc6ef940e24c35896e56e3372, the return false on error was converted to an exception.

This looks like more than the usual null to exception conversion so likely needs a changelog entry.

**Comment by cmb69** [comment]
Indeed, `ValueError`s should be explicitly documented. There is still the possibility that the function returns `false` for some other cases.

**Comment by othercorey** [comment]
The return type is string not string|false so I'm not sure how it could still return false.

**Comment by cmb69** [comment]
> The return type is string not string|false so I'm not sure how it could still return false.

Oh, this was about `shmop_open()`. `shmop_read()` and `shmop_write()` can't return false.
