### ISSUE TITLE
Can't get php for windows 10

### ISSUE THREAD

**Issue by DanKatz-old** [php/doc-en#2200]
From manual page: https://php.net/migration82.windows-support

--My name is Dan Katz.  I live in Sydney, Australia.  I'm trying to install PHP on my Windows 10 PC for development purposes.

I followed the instructions I've found in several places, to download, unzip, store, and configure PHP.

All this seems to go well.  However, when I type php on my command console, it tells me that the version of PHP I'm running is not compatible with the version of Windows that I'm running.

I've tried PHP 8.2.1 and 8.1.14, thread-safe and non-thread-safe, all with the same result.  I am definitely downloading the correct spec's for my pc, i.e., vs16 and x64. 

I can right click on the php.exe, and Microsoft lets me 'troubleshoot compatability'.  When I do this, I see that the PHP program is configured to run on Windows 8.  I'm on Windows 10.

 I would hugely appreciate any help you can give me on this.  I'm probably missing something obvious, but I can't figure out what it might be.

Thanks and Cheers,  Dan Katz-

**Comment by damianwadley** [comment]
Sorry but this isn't a place for support questions. There are [a variety of other places](https://www.php.net/support.php) that can help you, and of course there's always StackOverflow.

But I can tell you that PHP works just fine on Windows 10, so I'm not sure what message you're getting or why.
