### ISSUE TITLE
mb_encoding_aliases() missing changelog entry for ValueError

### ISSUE THREAD

**Issue by othercorey** [php/doc-en#2205]
Looks like the return false was converted into a ValueError in https://github.com/php/php-src/commit/90eeca2531296648a264f3fdc9a3e7e8e281b24e although the code has changed some since then. Because this adds a ValueError, should include a changelog entry.

I don't think the E_WARNING info is correct anymore either.

**Comment by cmb69** [comment]
Thank you!
