### ISSUE TITLE
Changed behaviour of DOMDocument::loadHTML() when using libxml >=2.9.14

### ISSUE THREAD

**Issue by ppp0** [php/doc-en#2219]
This is not a bug but stems from changes in [libxml2](https://gitlab.gnome.org/GNOME/libxml2)

We noticed this by chance

### Reproduce
```php
$document = new DOMDocument();
libxml_use_internal_errors(true);
$document->loadHTML('<%%%%===**>>> foo');
$errors = libxml_get_errors();

var_dump($errors);
```

With libxml2 prior to 2.9.14, `$errors` is expected to contain a `LibXMLError` object with message `htmlParseStartTag: invalid element name`

Starting with v2.9.14, `$errors` is an empty array.

This is due to [code changes](https://gitlab.gnome.org/GNOME/libxml2/-/issues/339#note_1392134) with the aim to prevent code injection attacks, but which introduce this modified behaviour.

Opening here to propose that it should be mentioned in php's [libxml docs](https://www.php.net/manual/en/book.libxml.php), unless [this change](https://gitlab.gnome.org/GNOME/libxml2/-/commit/4fd69f3e27e4ef2f8fafa091e723497017c40646) is reverted, which is very unlikely to happen

**Comment by cmb69** [comment]
> This is our expected behaviour since a long time (likely before libxml2 v2.9.14, too)

But this is different: you get an error and the invalid tag is swallowed; however, with the newer libxml, only the first character is swallowed (and there is no error).

**Comment by ppp0** [comment]
For us it's too dangerous. We will stick to libxml2 v2.9.13 which didn't show this behaviour. It means compiling php ourselves, though - on Alpine. Other distros seem to be using an older libxml2

**Comment by nielsdos** [comment]
libxml has a history of doing ad-hoc patches for html support. Documenting all of the subtle changes seems futile because it would require us to think about side-effects of libxml changes (and we don't maintain that). Since the manual nowadays has a big red warning that it can only do HTML4 parsing, and that HTML5 parsing is on its way with PHP 8.4, I'm not sure how to address this ticket.

**Comment by jimwins** [comment]
Agreed that it's not up to the PHP documentation to detail `libxml` changes. How about just adding a sentence to the warning on `DOMDocument::loadHTML` and `DOMDocument:loadHTMLFile`:

> The behavior when parsing HTML can depend on the version of `libxml` that is being used, particularly with regards to edge conditions and error handling.

When PHP 8.4 is documented, we can further add:

> For parsing that conforms to the HTML5 specification, use `DOM\HTMLDocument::createFromString()` or `DOM\HTMLDocument::createFromFile()`.

**Comment by nielsdos** [comment]
Yes that seems like a good idea.
