### ISSUE TITLE
strrpos Off-by-One Error in Parameters

### ISSUE THREAD

**Issue by miqrogroove** [php/doc-en#2220]
This phrase in the current documentation of `strrpos` is not true:

> If negative, the search is performed right to left skipping the last offset bytes

Let's look at an example where the offset is negative five.  PHP **does not** skip the last five bytes.  PHP **begins** at the 5th byte from the end, finds the needle if it begins anywhere at or left of the 5th byte from the end, and does so even if that needle is more than one byte and occupies the entire right side of the string from that point.  Unlike positive values, which are zero-based, negative values are one-based so that the last byte is `-1` and the 5th from last byte is `-5`.

```
$hay = 'Hello World';
$needle = 'World';
var_export(strrpos( $hay, $needle, -5 ));
```

In every version of PHP, this routine will return the position of `$needle` at the zero-based value of `6`.  We can see that the offset value of `-5` does not cause the last five bytes to be skipped.

Were the current documentation accurate, it would instead return `false`.

**Comment by cmb69** [comment]
This is inherently hard to document, and while I agree that the current description may be improveable, I don't think it is really wrong. Compare that with `substr( $hay, -5 )` (which is `"World"`, what explains the negative offset). From there, the string is searched from right to left, so it immediately finds `"World"`). "Skipping" is not "ignoring".

If you have an idea how to improve the description, please provide a PR.

**Comment by miqrogroove** [comment]
Edited "ignored" to "skipped" in top post.  Semantics.  Again, if PHP were "skipping" the last five bytes, then a haystack ending with a 5-byte needle would result in a `false` return from this function.

The attached PR is an improvement from my perspective.

**Comment by miqrogroove** [comment]
@kamil-tekiela Thank you for approving my other PR.  Could you offer any advice about getting traction on this particular issue regarding strrpos docs?

**Comment by kamil-tekiela** [comment]
What about if we say something like this:

> If negative, the search starts offset bytes from the right instead of from the beginning of the string. The search is performed right to left searching for the first occurrence of needle from the selected byte.

**Comment by miqrogroove** [comment]
It's a larger change.  I like it.  PR updated.

**Comment by miqrogroove** [comment]
@kamil-tekiela How do you feel about a commit for this?
