### ISSUE TITLE
Strict typing note is not reflecting in the behaviour

### ISSUE THREAD

**Issue by kubawerlos** [php/doc-en#2241]
Strict typing docs ([website](https://www.php.net/manual/en/language.types.declarations.php#language.types.declarations.strict), [code](https://github.com/php/doc-en/blob/161dde4fe721309398dd324edbf02aec409f127b/language/types/declarations.xml#L644-L649)) has this note:

> Strict typing applies to function calls made from within the file with strict typing enabled, not to the functions declared within that file. If a file without strict typing enabled makes a call to a function that was defined in a file with strict typing, the caller's preference (coercive typing) will be respected, and the value will be coerced.

So according to that, having a file `function.php` with content:
```php
<?php
declare(strict_types=1);
function test(int $x)
{
    var_dump($x);
}
```
and the other file `test.php` with content:
```php
<?php
require_once 'function.php';
test('hello');
```
calling `php test.php` should be fine.

However, it is [failing](https://github.com/werlos/php_strict_types_test/actions/runs/3974402220).

**Comment by cmb69** [comment]
Well, you can't coerce the string `hello` to an integer as of PHP 8.0.0 anyway (see https://3v4l.org/p2lW5).

**Comment by kubawerlos** [comment]
Well, actually you cannot do that in any PHP version.

Anyway, shame on me - I thought using `string` argument for `int` parameter will result in under-the-hood casting (as `(int) 'hello')` [is](https://3v4l.org/jAujD) `0`), but apparently not.

After [swapping](https://github.com/werlos/php_strict_types_test/commit/b572901723430b2a35c7dcd2ebd0e639c438ded9) types, it is working as documented.
