### ISSUE TITLE
Wrong parameters names for mysqli::real_connect

### ISSUE THREAD

**Issue by drmad** [php/doc-en#2242]
Like [bug 81232](https://bugs.php.net/bug.php?id=81232), parameters names for `mysqli::real_connect()` are wrong, and leads to confusion when using named parameters.

From file `ext/mysqli/mysqli.stub.php` in the source:

```
    public function real_connect(
        ?string $hostname = null,
        ?string $username = null,
        #[\SensitiveParameter] ?string $password = null,
        ?string $database = null,
        ?int $port = null,
        ?string $socket = null,
        int $flags = 0
    ): bool {}
```

From [https://www.php.net/manual/en/mysqli.real-connect.php](https://www.php.net/manual/en/mysqli.real-connect.php):

```
 public mysqli::real_connect(
    string $host = ?,
    string $username = ?,
    string $passwd = ?,
    string $dbname = ?,
    int $port = ?,
    string $socket = ?,
    int $flags = ?
): bool
```

`$hostname`, `$password`, and `$database` are wrong in the documentation.

**Comment by cmb69** [comment]
Oh, you're right. @kocsismate, did we miss these, or is there maybe a PR pending for review/merge?

**Comment by kocsismate** [comment]
> Oh, you're right. kocsismate, did we miss these, or is there maybe a PR pending for review/merge?

Uh, nice catch! I definitely missed these. I'll try to fix them soon.

**Comment by bobmagicii** [comment]
i ran into this myself this week - don't want to usurp but ill rip this out if you're cool since its been since jan.
