### ISSUE TITLE
ErrorException Documentation Insufficient

### ISSUE THREAD

**Issue by Sunthief** [php/doc-en#2273]
From manual page: https://php.net/class.errorexception
---
I think the description of this class is insufficient. As a learner, I initially did not understand what it is supposed to do (translate errors into error exceptions). My suggestions is to add the information from this paragraph (https://www.php.net/manual/en/language.exceptions.php#language.exceptions.notes) to the description of the class as well. Just a minor thing, but it might help someone like me.

**Comment by kamil-tekiela** [comment]
This page already includes a usage example https://www.php.net/manual/en/class.errorexception.php#errorexception.examples Is this not enough?

**Comment by Sunthief** [comment]
Personally I'd say another sentence or two in the introduction would be good, but as I said, it's a minor thing, so I understand you'd say it's unnecessary.

**Comment by Girgias** [comment]
This seems unnecessary.
