### ISSUE TITLE
Misleading wording in Time/Date docs, lack of any explanatory capability

### ISSUE THREAD

**Issue by CrazySquareRoot** [php/doc-en#2276]
From **strtotime** function docs:

"The function expects to be given a string containing an English date format and will try to parse that format into a Unix timestamp (the number of seconds since January 1 1970 00:00:00 UTC), relative to the timestamp given in baseTimestamp, or the **current time if baseTimestamp is not supplied**."

And then: "**Each parameter of this function uses the default time zone unless a time zone is specified in that parameter [1].** Be careful not to use different time zones in each parameter unless that is intended. See [date_default_timezone_get()](https://www.php.net/manual/en/function.date-default-timezone-get.php) on the various ways to define the default time zone."

From **date** function docs:

"Returns a string formatted according to the given format string using the given integer timestamp (Unix timestamp) or the **current time if no timestamp is given**. In other words, **timestamp is optional and defaults to the value of [time()]**(https://www.php.net/manual/en/function.time.php)."

It gets even better:

**Warning Unix timestamps do not handle timezones.** (see [1] above)

Those are just examples!!!

-----------------------
Maybe it's about time to decide if "current time" means return value of **time** function call (which, as far as I know and according to docs, is timezone independent) taken at the face value (GMT), without any timezone settings considerations, and treated as such in all internal calculations or something completely different. Is there a difference if we have default argument value instead of supplied one? How these functions operate? At which point they take timezone settings into account (if at all)? Params parsing? Later? When? How it may affect the result? Is it really so hard to clearly explain such basic things? I don't think so. For my taste it's just inexplicable laziness or putting people who don't have the very first clue about the matter to write docs to explain it! Dosc for both of this functions (and many more associated) are just complete gibberish. As a result, half of the internet thinks result of time() call is timezone-setting dependent! 

This kind of cavalier attitude is, unfortunately, ubiquitous in php docs. Such foundational topics as "dates and time" should have flawless and exhaustive documentation. Instead we have brief descriptions and sparse examples seasoned with contradictory wording. I happen to agree with the statement - if you can't write clear documentation, you don't have a clue what you're coding. You're just lucky it didn't end up in complete mess already.

**Comment by kamil-tekiela** [comment]
I agree that the sentence in `strtotime()` is unclear and should be reworded/removed. I have no clue what the author actually tried to say, so I would be for removing it. 

Please feel free to submit a pull request. PHP is an open-source project supported by volunteers. If you see something, be it in the language or in the documentation, that needs fixing, don't hesitate to submit a PR with the fix. Another volunteer will review it and merge it. 

While this issue is valid, the rant at the end is completely inappropriate.
