### ISSUE TITLE
Empty Page

### ISSUE THREAD

**Issue by elmahdiben119** [php/doc-en#2280]
From manual page: https://php.net/http.install

---

**Comment by damianwadley** [comment]
There isn't a page for "http.install". What was linking to it?

**Comment by elmahdiben119** [comment]
https://php.uz/manual/en/http.install.php this is the link I'm looking for how to install ext-http on windows.

**Comment by damianwadley** [comment]
We do not own or maintain php.uz.

Like I just happened to tell someone earlier today, "ext-http" apparently means https://pecl.php.net/package/pecl_http. You can download a DLL from there. It's also available on GitHub at https://github.com/m6w6/ext-http, and there's a link to documentation at https://mdref.m6w6.name/http.
