### ISSUE TITLE
IntlDateFormatter returns wrong year for UK locale

### ISSUE THREAD

**Issue by uaoleg** [php/doc-en#2282]
From manual page: https://php.net/class.intldateformatter

---

```
$formatter = new \IntlDateFormatter(
    'uk',
    \IntlDateFormatter::NONE,
    \IntlDateFormatter::NONE,
    null,
    null,
    'Y'
);
echo $formatter->format(1672144912);
```
Expected is `2022` but actual is `2023`. 
Reproduced for `uk` locale only, for all timestamps from `2022-12-26` to `2022-12-31`.

**Comment by damianwadley** [comment]
`Y` is the ISO 8601 year, which is not the same as the calendar year. You want `y` or `yyyy`.
https://unicode-org.github.io/icu/userguide/format_parse/datetime/#datetime-format-syntax
https://en.wikipedia.org/wiki/ISO_week_date

**Comment by uaoleg** [comment]
Damian thanks for explanation!

Just a bit more information below.

According to: http://userguide.icu-project.org/formatparse/datetime

Y stand for year of "Week of Year"(whatever it means) and y is regular year reference we got used to. So to get current year replace YYYY with yyyy and it should do the job

https://stackoverflow.com/a/59115137/676479
