### ISSUE TITLE
gmp_clrbit and gmp_setbit incorrectly state int|string are allowed

### ISSUE THREAD

**Issue by othercorey** [php/doc-en#2288]
These two functions requires a GMP object and do not convert numbers into a temp object.

The documentation is using `&gmp.parameter;` which states:

> A [GMP](https://www.php.net/manual/en/class.gmp.php) object, an int or a numeric string.

It should just be "A GMP object." 

Not sure how links should be added directly into function references.

**Comment by Girgias** [comment]
This link is generated using the ``<classname>`` tag.
