### ISSUE TITLE
 Fatal error: Uncaught Error: Unsupported operand types in

### ISSUE THREAD

**Issue by braddalton** [php/doc-en#2297]
- minus no longer works in PHP 8 https://www.php.net/manual/en/language.operators.php

**Comment by damianwadley** [comment]
Doubt it.

Want to try providing some more information?

**Comment by cmb69** [comment]
This is likely about operations like https://3v4l.org/je9OL. This is not specific for `-`, but is covered by <https://www.php.net/manual/en/language.types.numeric-strings.php> anyway.

I think this ticket can be closed.

**Comment by Girgias** [comment]
Not enough information provided.
