### ISSUE TITLE
Where to alert webmasters about comments?

### ISSUE THREAD

**Issue by jegelstaff** [php/doc-en#2303]
Hello,

A few days ago I wrote a comment for the docs, but in checking and double checking things, I ended up with a few pages open at once and I went and submitted the comment to the wrong page.

The comment is here on the strpos page: https://www.php.net/manual/en/function.strpos.php#128207

I meant to submit it to the strstr page instead. 🙁

I see no way to edit/flag/delete the comment from the front end, and no way to contact any admin people who could deal with this. So here I am asking/suggesting someone with access to the back end move that over, if possible? Or delete and I'll resubmit?

Sorry for such a niggling issue. Thanks for the phenomenal docs!

--Julian

**Comment by salathe** [comment]
I have edited the note to point to the `strstr()` page. The change should be reflected on the website within an hour or two.

Thanks!
