### ISSUE TITLE
Same value (247) for 2 constants MYSQLI_TYPE_ENUM and MYSQLI_TYPE_INTERVAL

### ISSUE THREAD

**Issue by fildaniels** [php/doc-en#2308]
From manual page: https://php.net/book.mysqli

I noticed that these two distinct constants have the same value. Is it normal ?

Thank you

**Comment by kamil-tekiela** [comment]
Yes, that's correct. 
- `MYSQLI_TYPE_INTERVAL` is an alias of `MYSQLI_TYPE_ENUM`.
- `MYSQLI_TYPE_CHAR` is an alias of `MYSQLI_TYPE_TINY`
- `MYSQLI_NUM_FLAG` is an alias of `MYSQLI_GROUP_FLAG`. (this one I do not understand and I am not trying to understand anymore)
