### ISSUE TITLE
Is callable a built-in type?

### ISSUE THREAD

**Issue by zer0uno** [php/doc-en#2313]
Here https://www.php.net/manual/en/language.types.intro.php callable is said to be a built-in type, while here https://www.php.net/manual/en/language.types.type-system.php callable is not under the built-in type list, instead it has its own definition.
So, should we consider callable a built-in type or not?

**Comment by damianwadley** [comment]
There could probably be some edits in there to at least make sure the two pages talk about the types consistently, but

"Built-in" has the same problem as "keyword" in that they're both more subtle than just that: base types, composite types, soft keywords vs. hard keywords... However the common definition of "built-in" means that the language supplies it for you, which is definitely the case for `callable` and others like `iterable`, so yes: it's definitely a built-in type.

**Comment by othercorey** [comment]
`callable` is considered built-in by reflection as well unlike Closure which is also "provided" but is a type of object.

https://3v4l.org/IBCfN#v8.1.16
