### ISSUE TITLE
The documentation does not reflect changes in the SAPI protocol

### ISSUE THREAD

**Issue by le-cha-sever** [php/doc-en#2315]
The program is written in Delphi (32bit).
The program calls php5ts.dll. Everything works perfectly. The new version of the program calls php8ts.dll. Work is terminated with an error when making a call to php_module_startup. The documentation does not reflect any changes in the use of the SAPI protocol. Or is it an implementation error?

**Comment by damianwadley** [comment]
doc-en doesn't cover these sorts of matters. Check the [PHP Internals Book](https://www.phpinternalsbook.com/) if you haven't yet, otherwise one or both of the two internals mailing lists might be able to help - but only if you can give more detail than just "terminated with an error".

**Comment by le-cha-sever** [comment]
Thank you.
What 2 mailing lists do you mean?
Unfortunately I can't give more details - the suggested way to get a core dump doesn't work with Delphi.
So far I can say the following:
The php_module_startup function had 3 parameters in PHP5 . Now it has 2 parameters.
I'll keep looking for differences.
