### ISSUE TITLE
strlen accepts different types than in the documentation

### ISSUE THREAD

**Issue by CJDennis** [php/doc-en#2332]
From manual page: https://php.net/function.strlen

---

`strlen()` no longer accepts arrays. If `strlen()` is passed `null`, it raises a deprecation warning. The documentation should be updated to reflect both of these.

```
>php -r "var_dump(strlen([]));"

Fatal error: Uncaught TypeError: strlen(): Argument #1 ($str) must be of type string, array given in Command line code:1
Stack trace:
#0 {main}
  thrown in Command line code on line 1
```

```
>php -r "var_dump(strlen(null));"

Deprecated: strlen(): Passing null to parameter #1 ($string) of type string is deprecated in Command line code on line 1
int(0)
```

Oddly, passing an array claims the parameter is called `$str`, but passing `null` claims the parameter is called `$string`!

**Comment by kamil-tekiela** [comment]
The manual page has been fixed too. Thanks!
