### ISSUE TITLE
Mistake in timezone Europe/Kyiv

### ISSUE THREAD

**Issue by yborshch** [php/doc-en#2346]
From manual page: https://php.net/timezones.europe
If copy timezone from site we will catch "DateTimeZone::__construct(): Unknown or bad timezone (Europe/Kyiv)"
Please change to 'Europe/Kiev'
---

**Comment by damianwadley** [comment]
https://www.php.net/manual/en/timezones.php
> Note: This list is based upon the timezone database version 2022.7.

PHP uses your system's timezone database, and they renamed the timezone to Kyiv within the last year. Update your system's timezone database if you can.
