### ISSUE TITLE
Timezone modifcation

### ISSUE THREAD

**Issue by Farhad-Ghasemi** [php/doc-en#2375]
From manual page: https://php.net/timezones

---
Due to recent changes Asia/Tehran time zone DST canceled and iran clock just using IRST (Iran Standard Time) 
Please modify this time zone to change to UTC+03:30 .
Regards

**Comment by damianwadley** [comment]
We do not control how timezones are defined.

And I don't see anything in the news about Asia/Tehran removing DST.
