### ISSUE TITLE
curl_multi_init may return false (like curl_init)

### ISSUE THREAD

**Issue by InvisibleSmiley** [php/doc-en#2382]
From manual page: https://php.net/function.curl-multi-init

---

https://www.php.net/manual/en/function.curl-multi-init.php#refsect1-function.curl-multi-init-returnvalues
states that the result can be false

https://www.php.net/manual/en/function.curl-multi-init.php#refsect1-function.curl-multi-init-description
does not reflect that

PHPStan seems to rely on the latter definition.

For comparison, here Description and Return Values match:
https://www.php.net/manual/en/function.curl-init.php

**Comment by othercorey** [comment]
Looks like the return description is wrong:

https://github.com/php/php-src/blob/master/ext/curl/multi.c#L60

**Comment by Girgias** [comment]
Fixed by: #2591
