### ISSUE TITLE
Erroneous suggestions to use ArrayIterator

### ISSUE THREAD

**Issue by jrchamp** [php/doc-en#2394]
I asked a question about a change in the context of the change, which @Girgias [unintentionally bullied](https://bulliesout.com/need-support/young-people/the-accidental-bully/). So I'm going to ask the question again as a fresh issue.

              This says to use ArrayIterator, but ArrayIterator doesn't work with these functions either. So then, what is this supposed to mean?

_Originally posted by @jrchamp in https://github.com/php/doc-en/pull/1123#discussion_r1150992271_
            
This documentation note applies to the `current()`, `reset()`, etc. family of functions (that the Iterator interface has matching implementations for). To me, the suggestion implies that you can use ArrayIterator or a subclass of it if you want to be able to use those global functions instead of the Iterator interface methods. If that was the intent of the note, then the note is incorrect (because it does not work).

While we're here clarifying the documentation, it should be noted that while that family of functions stopped working for general objects in PHP 8.1 (with a deprecation message), the functions silently (no deprecation message) stopped working for SPL objects in PHP 7.4 (which is noted in the PHP 7.4 backwards-incompatible changes documentation, but not in the function notes).

**Comment by damianwadley** [comment]
"Calling this function on objects is deprecated. Either use get_mangled_object_vars on the object first, or use ArrayIterator."

> To me, the suggestion implies that you can use ArrayIterator or a subclass of it if you want to be able to use those global functions instead of the Iterator interface methods. If that was the intent of the note, then the note is incorrect (because it does not work).

To me, it says that if I wanted to do iteration on an object's properties using this family of functions, I should either (a) use them but on the array returned by get_(mangled_)object_vars and not the object itself, or (b) do iteration differently by using ArrayIterator [and its methods](https://3v4l.org/CPC2k) _instead of_ those functions.

However, I am also familiar with the deprecation itself, as well as the nature of arrays and ArrayIterator, so I may very well be reading it with a different mindset than you.

If you have a suggestion for how to improve the phrasing then feel free to submit a PR. After all, if you're the one who is misunderstanding (no offense) then you're also the best one to know how to fix it.


And was Girgias a bit blunt? Sure. But he's not wrong: creating an issue really is the most effective way to start talking about a problem in the docs.

**Comment by jrchamp** [comment]
Thanks @damianwadley,

I am indeed the person who does not understand the note, so I would be happy to help reduce the ambiguity. As I am not as familiar with the process and the ways in which the documentation is linked to each other, I will need to rely on people who do understand the documentation platform during the PR review.

Your version of "To me" explicitly clarifies that ArrayIterator is not an option to "use with these functions", but is instead an alternative approach with its own methods. That detail is important, because it can otherwise be read instead to mean that you must first pass the object into a function that returns an array or use a magic SPL class (and as we know, some internal classes have - at least historically - been allowed to do things that other classes cannot).

At a minimum, I would suggest: "Calling this function on objects is deprecated. Either convert the object to an array using get_mangled_object_vars first, or use the methods provided by ArrayIterator instead."

From my perspective, suggesting ArrayIterator goes far beyond what is strictly necessary for the most important of these methods, particularly as the Iterator interface defines most of them which ArrayIterator implements. Here's a simplistic implementation of all 6 using the Iterator interface:

- `current()` => `return Iterator->current();`
- `key()` => `return Iterator->key();`
- `next()` => `Iterator->next(); return Iterator->current();`
- `reset()` => `Iterator->rewind(); return Iterator->current();`
- `prev()` => `$key = Iterator->key(); Iterator->rewind(); while (Iterator->key() !== $key) { $prev_key = Iterator->key(); Iterator->next(); } Iterator->rewind(); while (Iterator->key() !== $prev_key) { Iterator->next(); } return Iterator->current();`
- `end()` => `Iterator->rewind(); while (Iterator->valid()) { $end_key = Iterator->key(); Iterator->next(); } Iterator->rewind(); while (Iterator->key() !== $end_key) { Iterator->next(); } return Iterator->current();`

The implementations for `prev()` and `end()` are not pretty or efficient. However, those two original functions are probably not as useful as the other four given that they are not part of any of the interfaces that make up ArrayIterator.

The best I can think of at this time for those two is to use the SeekableIterator interface:
- `prev()` => `$key = Iterator->key(); Iterator->rewind(); $offset = -1; while (Iterator->key() !== $key) { $offset++; Iterator->next(); } Iterator->seek($offset); return Iterator->current();`
- `end()` => `Iterator->rewind(); $offset = -1; while (Iterator->valid()) { $offset++; Iterator->next(); } Iterator->seek($offset); return Iterator->current();`

With that in mind, I am instead suggesting: "Calling this function on objects is deprecated. Either convert the object to an array using get_mangled_object_vars first, or use the methods provided by a class that implements the Iterator interface, such as ArrayIterator, instead."

Going back to the other issue... Blunt, in this context could mean [direct and/or insensitive](https://www.merriam-webster.com/dictionary/blunt) and I agree that it was both. The idiom is specifically defined as [adding force to an angry statement](https://www.merriam-webster.com/dictionary/for%20the%20love%20of%20God). It was unnecessary to communicate the point directly and was instead intentionally insensitive in order to express exasperation at my behavior. Open source communities often struggle with being an inclusive/inviting, so it's best to avoid these unnecessary words - especially idioms.
