### ISSUE TITLE
Does `json_encode` could actually fail and return `false`?

### ISSUE THREAD

**Issue by kocoten1992** [php/doc-en#2417]
Hi, I'm using phpstan and it complain about [json_encode](https://www.php.net/manual/en/function.json-encode.php) could return `false`. I've been thinking - is that true though? I can't think of an example where `json_encode` could fail (and return `false` as boolean).

If so, may I submit a PR to fix this?

**Comment by bukka** [comment]
Yes it can fail and return false on invalid UTF-8 (e.g. `var_dump(json_encode("\x61\xf0\x80\x80\x41"))`), objects with recursion, encoding resource type and possibly some other things.
