### ISSUE TITLE
mysqli_connect throws fatal error

### ISSUE THREAD

**Issue by timbrimelow** [php/doc-en#2424]
From manual page: https://php.net/class.mysqli
 just letting you know that my entire web presence is down because the new version of PHP is saying to me constantly

[Thu Apr 13 16:33:03.967328 2023] [lsapi:error] [pid 37469:tid 47997232551680] [client 115.70.240.177:0] [host www.wimmeracomputers.com.au] Backend fatal error: PHP Fatal error:  Uncaught Error: Call to undefined function mysqli_connect() in /home/wiwi2472/public_html/db_connection.php:8\nStack trace:\n#0 /home/wiwi2472/public_html/index_test.php(3): OpenCon()\n#1 {main}\n  thrown in /home/wiwi2472/public_html/db_connection.php on line 8\n---

I have tried to fix this error for hours now.  Must be something wrong with PHP.  Following all recommended ways of fixing it and it says call to UNDEFINED FUNCTION!!!!! mysql_connect() is .... how can mysql_connect be an undefined function.

**Comment by damianwadley** [comment]
https://www.google.com/search?q=php+Call+to+undefined+function+mysqli_connect
