### ISSUE TITLE
Prior to PHP 8.1 2nd and 3rd parameter of IntlDateFormatter::__construct / IntlDateFormatter::create are not optional

### ISSUE THREAD

**Issue by mz-aimcom** [php/doc-en#2425]
From manual page: https://php.net/intldateformatter.create

---

In my tests parameters no. 2 `$dateType` and no. 3 `$timeType` are not optional in PHP before version 8.1.

Tested in PHP 8.0.28 and 7.4.33.

**Comment by kocsismate** [comment]
Caused by https://github.com/php/php-src/commit/331eddadc8d1876e9dfe45c9784e75ef2930bb3e
