### ISSUE TITLE
pcntl_rfork only available on BSD

### ISSUE THREAD

**Issue by danladrian** [php/doc-en#2428]
As I've seen in the [documentation](https://www.php.net/manual/es/function.pcntl-rfork.php) from php version (PHP 8 >= 8.1.0) there should exists the funcion **pcntl_rfork** but there is none. 

I've search to see if you have to build php with a specific flag or so to have this enabled but didn't found anything about that.

As I've search the source code I've found that the motive is because there is no **HAVE_RFORK** constant defined so the funcion will never be defined.

I don't know if this is a code bug or a doc bug so i've created it here first.

**Comment by damianwadley** [comment]
Per [the original commit](https://github.com/php/php-src/commit/28382aa1ec2f0dc0d736e4dbc18dfbfbbd02cee8), rfork(3) is only provided by BSD variants - regular Linux doesn't have it.

It's not explicitly stated in the pcntl docs as far as I've seen, but it's implied that all of these functions are only available if they're present on your system.

**Comment by damianwadley** [comment]
The docs do _not_ say so. That is why I did not close this issue.
