### ISSUE TITLE
How to set MST as timezone with auto adjust daylight savings in php?

### ISSUE THREAD

**Issue by rahulthackkar** [php/doc-en#2433]
Hello Team,

# I am trying to setup MST as timezone with automatic daylight saving in php for Location : Great Falls, Montana, United States.

So concern here is what value of timezone I should set for MST ,
 which is running right now at (UTC -6) (From 12th March 2023),
 it will be switched to (UTC -7) when winter time starts (From 5th November 2023).

It is giving expected time If I set 

`date_default_timezone_set('MST');`

But, in https://www.php.net/manual/en/timezones.others.php, it is mentioned that, I should not use this abbreviated form of timezone, it will be deprecated. 

**Version : PHP 7.4.33**

## Do I need to switch timezone twice in a year, or any other provision to make it lifetime dynamic?

Can anyone please help me on this, it is highly appreciated.

**Comment by damianwadley** [comment]
https://www.php.net/manual/en/timezones.america.php

"MST" could mean any number of things. If you want something that respects DST rules then you have to decide which set of rules you want to follow. Fortunately, in the US the rules are currently more or less the same everywhere - with exceptions like Arizona - but historically there are a number of differences.

I'll spare you the history lessons and say that you probably want "America/Denver".

**Comment by rahulthackkar** [comment]
MST means mountain standard time.
It should be UTC -7 for  period without daylight saving time.
and it should be UTC-6 when daylight saving mode ON.
typically I want to set one timezone in my application that automatically run with taking care of DST for location Great Falls

**Comment by MorganLOCode** [comment]
MST refers to Mountain Standard Time (UTC-7:00); there are also Mountain Daylight Time (UTC-6:00) and Mountain Time (UTC-7:00 or UTC-6:00 depending on the time of year).

> "Mountain Standard Time (MST) is a standard time zone in use from the first Sunday in November to the second Sunday in March—when Daylight Saving Time (DST) is not in effect. Mountain Daylight Time (MDT) is used during the remainder of the year. ... In everyday usage, MST is often referred to as Mountain Time (MT) or the Mountain Time Zone. This can add a bit of confusion as the term Mountain Time does not differentiate between standard time and Daylight Saving Time, so Mountain Time switches between MST and MDT in areas that use DST during part of the year."
https://www.timeanddate.com/time/zones/mst

**Comment by rahulthackkar** [comment]
Hi @MorganLOCode ,
Thanks for your contribution.
When I set America/Denver as timezone, will it care automatically switching between MST and MDT?
I mean right now it is UTC -6, will it give time (date('Y-m-d H:i:s)) according to UTC -7 after DST ends on after Sun, 5 Nov, 02:00 2023?
Just to confirm.

**Comment by damianwadley** [comment]
Yes, named timezones like America/Denver respect DST transitions. It's the main reason why they exist: so you don't have to worry about managing UTC offsets yourself.

**Comment by rahulthackkar** [comment]
Thanks a lot for your help.
