### ISSUE TITLE
Clarification on American vs European date formats

### ISSUE THREAD

**Issue by gennie** [php/doc-en#2446]
From manual page: https://php.net/function.strtotime

---

We encountered seemingly-inconsistent behavior between European and American style dates (i.e. mm-dd-yyyy and dd-mm-yyyy); after some searching, we discovered that the [Spanish translation of this manual page](https://www.php.net/manual/es/function.strtotime.php) includes the following note:

> Dates in the formats m/d/y or d-m-y are unambiguous by looking at the separator between the various components: if the separator is a slash (/), the North American format m/d/y is assumed; while if the separator is a hyphen (-) or a period (.), the European format d-m-y is assumed. If, however, the year is given in a two-digit format and the separator is a hyphen (-), the date string is parsed as y-m-d. 

This clarification would be very useful to include on the English version of the manual page as well.

**Comment by damianwadley** [comment]
The English documentation is the source and other languages translate from there; the comment was removed during #1669 and the Spanish page (and others) have not caught up to the change yet.

The intention is that you follow the link in the $datetime description to the [Supported Date and Time Formats](https://www.php.net/manual/en/datetime.formats.php) page, and from there to [Date Formats](https://www.php.net/manual/en/datetime.formats.date.php), where the "Localized Notations" table shows the assorted variations of possible date formats.

Seems this was preferred as the actual rules for those formats were "[more bonkers](https://github.com/php/doc-en/pull/1669#issuecomment-1172483664)" than the note suggested.

Your thoughts?

CC @Crell

**Comment by Crell** [comment]
Yes, the translation pages should catch up with English and more prominently link to the existing parsing rules definition.  The old text was, IIRC, not *quite* accurate, as the logic is truly screwy.

**Comment by Girgias** [comment]
This is a doc-es issue, closing.
