### ISSUE TITLE
setcookie() parameters is not updated

### ISSUE THREAD

**Issue by llaville** [php/doc-en#2470]
Hello,

Recently on my project, a user noticed me about the [Same site Cookie](https://wiki.php.net/rfc/same-site-cookie) feature that came with PHP 7.3.0

Signature has changed (see commit https://github.com/php/php-src/commit/2b58ab23c6ad3301b31a2015f5faa31801147dfd#diff-4b2936dd5dc18d1e25683c53f1aeb6c4f79df6d05999c9425abb2de9a2086567) but documentation page of `setcookie` function did not reflect it !

**Comment by damianwadley** [comment]
Are you referring to the signature of `php_setcookie`? That is not the `setcookie` function but an internal "helper" function.

`setcookie` itself is defined further down starting on lines ~252:
```diff
- /* {{{ proto bool setcookie(string name [, string value [, int expires [, string path [, string domain [, bool secure[, bool httponly[, string samesite]]]]]]])
+ /* {{{ proto bool setcookie(string name [, string value [, int expires [, string path [, string domain [, bool secure[, bool httponly]]]]]])
+                   setcookie(string name [, string value [, array options]])
```
The new signature is (a) name/value/expires/path/domain/secure/httponly, or (b) name/value/options, and the documentation matches it.

**Comment by llaville** [comment]
@damianwadley Sorry to reply so lately. I've misunderstood the [RFC](https://wiki.php.net/rfc/same-site-cookie). 
The documentation is up-to-date with current implementation, I'll then close this report !
