### ISSUE TITLE
“Captcha” is invoked every few minutes

### ISSUE THREAD

**Issue by erikmh** [php/doc-en#2471]
Perhaps one time in three, when I load a page from the current English PHP documentation site, I’m asked to decipher an interstitial CAPTCHA.

This occurs whether I’m following a link from a search-engine list of search results, searching directly on the site using the site’s search box, or even just following a link from one page of the documentation to another.

It also occurs no matter what web browser I use. My browsers are set to accept cookies (but not third-party cookies, if that’s relevant).

I would expect *at most* to be asked to fill in one CAPTCHA daily.

**Comment by damianwadley** [comment]
Huh. Apparently php.net switched to Myra Security years ago... TIL.
And I just got a CAPTCHA prompt myself too. Never had one before.

Anyway, this is a [web-php issue](https://github.com/php/web-php/issues) as doc-en is just for the language documentation. I can't move this issue there but someone else might.

It's possible Myra is reacting to a perceived threat. Did this start recently for you? Are you maybe on a network that has you changing IP addresses frequently? I'd suggest to just give it a couple days to settle back down.

**Comment by damianwadley** [comment]
I'm going to close this since it's being being talked about elsewhere.
https://externals.io/message/120272
https://marc.info/?t=168398847900001&r=1&w=2
