### ISSUE TITLE
implode() throw error with null argument.

### ISSUE THREAD

**Issue by klebann** [php/doc-en#2500]
From manual page: https://php.net/function.implode

code:
`implode(', ', null)`

Throw:
`implode(): Argument #1 ($pieces) must be of type array, string given`

 PHP version:
`PHP 8.2.6 (cli)`

Definition:
![image](https://github.com/php/doc-en/assets/22200025/c6425c90-6864-4721-916f-b98ed7327f23)

In definition it is allowed to pass null|array as $array argument.

**Comment by damianwadley** [comment]
$array can be null, yes, but only if you use the `implode(array $array): string` syntax given in the documentation.

If the first argument is a string, which is the proper way to use this function, then the second argument must be an array. It can be an empty array, but it must be an array.
