### ISSUE TITLE
removed assert.quiet_eval and ASSERT_QUIET_EVAL still mentioned as if nothing happened in some places

### ISSUE THREAD

**Issue by claudepache** [php/doc-en#2506]
The `assert.quiet_eval` ini setting and ASSERT_QUIET_EVAL constant have been removed in PHP 8.0, as duly noted in: https://www.php.net/manual/en/function.assert.php

However, (at least) the two following documentation pages fail to mention their removal:

* https://www.php.net/manual/en/info.configuration.php
* https://www.php.net/manual/en/function.assert-options.php

**Comment by claudepache** [comment]
Additionally, the ASSERT_EXCEPTION option introduced in PHP 7.0 fails to be mentioned in
https://www.php.net/manual/en/function.assert-options.php

**Comment by Girgias** [comment]
I've got #2467 that handles some of these issues, which is how I got to write the RFC in the first place.
