### ISSUE TITLE
json_decode return values documentation

### ISSUE THREAD

**Issue by NanoCaiordo** [php/doc-en#2513]
From manual page: https://php.net/function.json-decode

---
The Return Values section instead of 

> Values true, false and null are returned as true, false and null respectively.

Should be written as

> JSON encoded values true, false and null are returned as true, false and null respectively.

**Comment by Girgias** [comment]
Hello,

Could you provide a PR for the wording you would like?

**Comment by NanoCaiordo** [comment]
<p class="para">
   Returns the value from an encoded <code class="parameter">json</code> in the appropriate
   PHP type. Encoded values <code class="literal">true</code>, <code class="literal">false</code> and
   <code class="literal">null</code> are returned as <strong><code>true</code></strong>, <strong><code>false</code></strong> and <strong><code>null</code></strong>
   respectively. <strong><code>null</code></strong> is returned if the <code class="parameter">json</code> cannot
   be decoded or if the encoded data is deeper than the nesting limit.
  </p>
