### ISSUE TITLE
Call to undefined function mb_convert_encoding()

### ISSUE THREAD

**Issue by boboshaq** [php/doc-en#2531]
From manual page: https://php.net/function.mb-convert-encoding

---
When I try use function: mb_convert_encoding() I have an error:
PHP Fatal error:  Uncaught Error: Call to undefined function mb_convert_encoding() in [...]

My php version is: 
PHP Version7.4.3-4ubuntu2.18

**Comment by damianwadley** [comment]
You need to install the mbstring extension via the php-mbstring package.
https://packages.ubuntu.com/focal/php-mbstring
