### ISSUE TITLE
Documentation example of getrusage is missing "ru_stime.tv_sec"

### ISSUE THREAD

**Issue by marcelgleis** [php/doc-en#2575]
The first example in https://www.php.net/manual/en/function.getrusage.php misses the data `ru_stime.tv_sec`

Please append to the #1 example:
`echo $dat["ru_stime.tv_sec"]; // system time used (seconds)`

**Comment by Girgias** [comment]
Could you provide a PR?

**Comment by marcelgleis** [comment]
Yes, here you are: https://github.com/php/doc-en/pull/2579

**Comment by marcelgleis** [comment]
As the PR is merged => I'll close this issue
