### ISSUE TITLE
Default value of `assert.exception` is still "0" at info.configuration.php

### ISSUE THREAD

**Issue by sasezaki** [php/doc-en#2621]
Hi. I'm wondering that default value of `assert.exception` is still "0" at info.configuration.php.

https://www.php.net/manual/en/info.configuration.php

> <html>
<body>

assert.exception | "0" | PHP_INI_ALL
-- | -- | --

</body>
</html>

Recently,  PR of #1881 is closed with #2467 .
But, reference/info/ini.xml 's value is still old "0".

**Comment by Girgias** [comment]
Ah indeed, this got missed in my rework. Would also need some changelog as prior to PHP 8.0.0 it was 0
