### ISSUE TITLE
Example #1 array_diff_assoc() example [second arrays last value should have a key "1"]

### ISSUE THREAD

**Issue by DEarTh27** [php/doc-en#2631]
From manual page: https://php.net/function.array-diff-assoc

---

In this example you see the "a" => "green" pair is present in both arrays and thus it is not in the output from the function. Unlike this, the pair 0 => "red" is in the output because in the second argument "red" has key which is 1.

```
<?php
$array1 = array("a" => "green", "b" => "brown", "c" => "blue", "red");
$array2 = array("a" => "green", "yellow", "red");
$result = array_diff_assoc($array1, $array2);
print_r($result);
?>
```

**Comment by damianwadley** [comment]
Since your report is just a copy-and-paste of the example's description and (part of) its code, how about clarifying what you think should be changed?

**Comment by DEarTh27** [comment]
`$array2 = array("a" => "green", "yellow", "red"); `

Should be

`$array2 = array("a" => "green", "yellow", "1" => "red"); `

As per the description.

**Comment by salathe** [comment]
In `$array2`, the item with value `"red"` already had a key of `1` automatically assigned. 
What's the problem?

**Comment by salathe** [comment]
Again, please explain the problem.

Before and after the related code change (#2634) for this example, both `$array2` arrays are identical.

What do you want to achieve? Does that require changing the example code?

**Comment by DEarTh27** [comment]
Seems like a misunderstanding. May be we can add description to say that "In $array2, the item with value "red" already had a key of 1." "**That is automatically assigned**"
