### ISSUE TITLE
Examples in the Warning section are the same

### ISSUE THREAD

**Issue by nikolaynikolaevn** [php/doc-en#2635]
From manual page: https://php.net/control-structures.alternative-syntax

---

I fail to see the difference between the two examples in the red Warning section.

**Comment by Girgias** [comment]
Probably should be changed to:
```php
<?php switch ($foo): ?>

<?php case 1: ?>
...
<?php endswitch ?>
```

I expect this example to have some trailing whitespace initially that got removed at one point.
