### ISSUE TITLE
Missing documentation about when false is returned

### ISSUE THREAD

**Issue by sylfabre** [php/doc-en#2649]
From manual page: https://php.net/function.mktime

---

The page reads that the `mktime()` function may return `false` but this case is not documented

**Comment by damianwadley** [comment]
Returns false if the calculated timestamp would be out of bounds for a PHP integer.
https://github.com/php/php-src/blob/php-8.2.9/ext/date/php_date.c#L1186

Guessing it's a 32-bit thing, as at 2**63 it just overflows.
```php
var_dump(gmdate("Y-m-d H:i:s", PHP_INT_MAX)); // string(27) "292277026596-12-04 15:30:07"
var_dump(gmmktime(15, 30, 7 + 1, 12, 4, 292277026596)); // int(-9223372036854775808)
```

**Comment by alexandre-daubois** [comment]
I was able to reproduce the `false` value in the live preview of 3v4l.org (not able to reproduce with the non-live preview though):

![image](https://github.com/php/doc-en/assets/2144837/64ea6614-92b2-4af2-8dfa-e600623016f1)

I sent a PR to document the missing behavior

**Comment by damianwadley** [comment]
The live version is actually PHP running in the browser thanks to WASM. And it is 32-bit.
