### ISSUE TITLE
Double check that the value of `CURLOPT_CAINFO_BLOB` is in string section

### ISSUE THREAD

**Issue by Girgias** [php/doc-en#2656]
Double check after #1911 is merged

> The value of `CURLOPT_CAINFO_BLOB` is supposed to be a string, but it is in the integer section.

_Originally posted by @cmb69 in https://github.com/php/doc-en/pull/1911#discussion_r1017855472_

**Comment by ekinhbayar** [comment]
@Girgias looking at the current https://www.php.net/manual/en/function.curl-setopt.php that is live, this constant is appearing under the string section 👍

**Comment by Girgias** [comment]
Cool, thanks for checking I had forgotten I had opened this :')
