### ISSUE TITLE
“Supported Date and Time Formats” is unclear

### ISSUE THREAD

**Issue by alexislefebvre** [php/doc-en#2674]
From manual page: https://www.php.net/manual/en/datetime.formats.php

You can arrive on this page from the `modify()` page: https://www.php.net/manual/en/datetime.modify.php#refsect1-datetime.modify-parameters

---

This page shows a “Table of Contents”, which contains 4 links but no introduction and the page itself doesn't have any heading so I don't understand why there is a TOC.

Then there is a text that apparently explain the content of these 4 pages:

- “The formats are grouped by section”: what formats?
- “For each of the supported formats, one or more examples are given”: this page has no example, so it must refer to the 4 links

And then there are 9 bullets that is hard to read because it mixes all the different cases.

I think that this page should be rewritten, but I don't have any suggestion except that this page should be easier to read.

**Comment by Girgias** [comment]
The different sections where being rendered into their own page, this should no longer be the case after https://github.com/php/doc-en/commit/ce5b00c8ad15389e7c18b5e452a7b89b90ba9756, however the docs need to be re-rendered with said commit which might either happen sometime tonight, or has already happened and thus need to wait longer (or look at the docs.php.net version which is updated more often)

**Comment by alexislefebvre** [comment]
Thanks! This is much better now: https://www.php.net/manual/en/datetime.formats.php
