### ISSUE TITLE
"Include" bug

### ISSUE THREAD

**Issue by Barona1** [php/doc-en#2694]
From manual page: https://php.net/function.include

I read this manual page fully, and I believe the following short program and two includes shows a PHP bug. 
( I had to add spaces in the < ? PHP  first line to make them visible here)
It does not work as expected.  It passes lint and runs.
I get this output:

php -f test1.php
THIS IS A TEST 
this is function_x.php4
this is function_y.php6
this is function_z.php9

What's going on ??
1. I would expect some parsing error in TEST1.php inside function x block
2. I would expect the include in function_x.php to return 0  (zero which is $x-$x is 3-3 == 0)
3. Instead, the 'return $x+1;' actually returns function x and not the return inside the include immediately prior.
??
-Thanks.

===================================================================================================
FILE 1:  test1.php

> 
< ? PHP

function x($x) { include('function_x.php');
				 return $x+1;
				 return $x+2;
				 5+7;
				 dsfadfdsaffa;
			   }

function y($x) { echo "this is function_y.php";
				 return $x+$x;
			   }

include "function_z.php";

echo "THIS IS A TEST \n";

echo x(3)."\n";
echo y(3)."\n";
echo z(3)."\n";
echo "\n";

?>

===================================================================================================

FILE 2:  function_x.php

>
< ? PHP

// function_x.php

echo "this is function_x.php";
return $x-$x;

?>

 ==================================================================================================
 FILE 3:  function_z.php
 

>
< ? PHP

function z($x) { echo "this is function_z.php";
				 return $x+$x+$x;
			   }
?>

**Comment by damianwadley** [comment]
> 1. I would expect some parsing error in TEST1.php inside function x block

Because of the `dsfadfdsaffa;`? PHP can successfully parse that line as trying to reference a constant. The constant doesn't exist, but that's not a parse error.

> 2. I would expect the include in function_x.php to return 0  (zero which is $x-$x is 3-3 == 0)

`return` is returning from inside the included file. Not from the function that included it.

https://www.php.net/manual/en/function.return.php
> If called from the global scope, then execution of the current script file is ended. If the current script file was [include](https://www.php.net/manual/en/function.include.php)d or [require](https://www.php.net/manual/en/function.require.php)d, then control is passed back to the calling file.

**Comment by Barona1** [comment]
As to your reply to 2.
If return is returning from inside the included file, then the echo would be 0 (as in zero) and not 4, which is the return outside the included function.  The return inside the include is completely ignored, but the echo is not.  This is not correct.

**Comment by damianwadley** [comment]
function_x.php does not modify $x. If you were to change it to be
```php
<?php

echo "this is function_x.php";
$x = $x-$x;
return $x;

?>
```
then `x(3)` would return 1.
