### ISSUE TITLE
imagettftext() How to display Unicode Plane 1 characters

### ISSUE THREAD

**Issue by P2T** [php/doc-en#2705]
```
$img = imagecreatetruecolor(240, 240);
imagettftext($img, 60, 0, 48, 192, 0, '/path/to/fonts/NotoSansEgyptianHieroglyphs-Regular.ttf', '&#78143;');`
```

Cannot render anything but a black empty square for all plane 1 Unicode chars.
The documentation states to use html_entities for UTF-8 chars like "&#78143;" (for Egyptian Hieroglyph G001) but it still fails.
It this a documentation issue or a PHP bug?

**Comment by damianwadley** [comment]
According to https://github.com/libgd/libgd/issues/185, gd doesn't currently support characters above U+FFFF (and G001 is U+1313F). I don't think it warrants documentation changes given (a) how infrequently someone is going to encounter this, but more than that (b) this is a recognized bug that should get fixed at some point.

As a workaround, you might be able to find a font with hieroglyphics but in the <FFFF range - how fonts like [Wingdings](https://en.wikipedia.org/wiki/Wingdings) work. But worst case, I don't think it would be hard to create it yourself from Noto Sans.

A more severe workaround would be ImageMagick / imagick, assuming it doesn't have a similar problem.

CC @pierrejoye
