### ISSUE TITLE
CHM Files Are Missing Styles (Release Date 2023-08-26)

### ISSUE THREAD

**Issue by G80** [php/doc-en#2752]
Both chm documentation files', with and without user notes, style/design/layout is broken -- missing colours, fonts, layout broken.
Date on downloads page: 8 Sep 2023.

![chm_broken](https://github.com/php/doc-en/assets/2395110/d1795960-931e-4806-aef3-affda5f85519)

**Comment by mumumu** [comment]
I downloaded the latest English version chms, but cannot reproduced, I'm attaching a screenshot of Windows 11.

![Screenshot_20231001_175158](https://github.com/php/doc-en/assets/26536/12a7bb09-3d7b-47dc-95aa-b92688d9a23c)

**Comment by G80** [comment]
Huh, what?
Page on your screenshot looks exactly the same like what I took.
And you didn't scroll page down to check that content will see through header (header does not have bg colour).
I downloaded now again the English HTML Help file (with user notes), Date: 29 Sep 2023 and still broken and missing styles.
Header bg are headings are missing colours, only the default system font is used, layout is broken etc.

This is how it should look (since there is no older versions for download, I can't use same page):

![image](https://github.com/php/doc-en/assets/2395110/ab9ee5f6-ad2c-4f37-9273-41865b3f8f27)

How come this little fix is taking so long? Can you in mean time atleast publish/replace link to older, working chm file? Many devs use offline version with user comments.

**Comment by iansltx** [comment]
@G80 mind PR'ing a fix for this?
