### ISSUE TITLE
bug in jewishtojd()

### ISSUE THREAD

**Issue by robertlight** [php/doc-en#2775]
From manual page: https://php.net/function.jdtojewish

$jd = jewishtojd( 1,1,5784);// 1st of Tishrei 5784 was on 9/16/2023
echo jdtojulian($jd);           // produces 9/3/2023

---

**Comment by damianwadley** [comment]
If you're looking for a date string according to the standard Gregorian calendar used by most of the world then you need `jdtogregorian`. The Julian calendar is something different.
https://en.wikipedia.org/wiki/Julian_calendar
