### ISSUE TITLE
PHP 8.2 migration guide still "Other changes" of "date format sent cookie"

### ISSUE THREAD

**Issue by youkidearitai** [php/doc-en#2807]
https://www.php.net/manual/en/migration82.other-changes.php#migration82.other-changes.core

> The date format of sent cookies is now 'D, d M Y H:i:s \G\M\T'; previously it was 'D, d-M-Y H:i:s T'.

My understanding is reverted PR: https://github.com/php/php-src/pull/6783. But this statement remains.

**Comment by jimwins** [comment]
This was changed in 8.2 timeframe as a bug fix https://github.com/php/php-src/commit/15e3fcb468d7ef6faddc8f99f8f708fe8c2d8492.
