### ISSUE TITLE
List of functions is not in correct alphabetical order

### ISSUE THREAD

**Issue by jorgsowa** [php/doc-en#2847]
The functions `atan2`, `atan` and `atanh` are not in natural alphabetical order on the list on the page [Math Functions](https://www.php.net/manual/en/ref.math.php).

Correct order should be:
- atan
- atan2
- atanh

I was trying to edit the page, but I saw only note ` &reference.math.entities.functions;`, so at least I raise the issue on the page.

**Comment by Girgias** [comment]
That looks more like a PhD issue

**Comment by haszi** [comment]
The sorting is done in `doc-base` ([on this line](https://github.com/php/doc-base/blob/8b3169819f3598ed6ac14597591d1630be4dff04/scripts/file-entities.php.in#L227)) and it should be producing the correct output. But it doesn't. 

I tried passing different sorting flags to `sort()` and I even tried using `natsort()` instead of `sort()` but I couldn't get it to work.

**Comment by cmb69** [comment]
Is this, perhaps, like https://3v4l.org/P0jIN?

**Comment by haszi** [comment]
Oh! I think I see what you mean.... The semicolon is throwing the sorting off, right?

**Comment by cmb69** [comment]
I haven't debugged, but if XML entity references are sorted, the behavior would be expected. We might need some `usort()` there.

**Comment by haszi** [comment]
Another option would be to add the trailing semicolon right after sorting (instead of [here](https://github.com/php/doc-base/blob/8b3169819f3598ed6ac14597591d1630be4dff04/scripts/file-entities.php.in#L203)).

**Comment by haszi** [comment]
It seems that this sorting issue is fairly widespread as functions such as `curl_setopt()` and `curl_setopt_array()` were all sorted with a trailing semicolon (ie. function names such as `curl_setopt_array()` always came before names like `curl_setopt()`). In `doc-en`, 916 files are affected by this.
