### ISSUE TITLE
GearmanTask::jobHandle() can also return `false`

### ISSUE THREAD

**Issue by cracksalad** [php/doc-en#2859]
From manual page: https://php.net/gearmantask.jobhandle

---

As you can see [in the source code](https://github.com/php/pecl-networking-gearman/blob/master/php_gearman_task.c#L205), this method normally returns a string, but can return `false` on failure. So the return type should be `string|false` but is just `string` on the manual page.

Edit: I just saw, it could also return `null`.

**Comment by Girgias** [comment]
Seems they have stub files we can use to generate the docs, however they also seem to be not totally accurate: https://github.com/php/pecl-networking-gearman/blob/master/gearman.stub.php#L262

**Comment by Girgias** [comment]
> @Girgias I already created a [PR for php/pecl-networking-gearman](https://github.com/php/pecl-networking-gearman/pull/24) to fix/clarify return types. Should I create a PR here to document the changes and fix wrong types in documentation?

That would be great, the way we do it now with a stub file is to use the ``gen_stub`` script in the php-src repo with the following command:
```shell
../php-src/build/gen_stub.php --replace-methodsynopses ../path/to/extension/ ../docs-php/en/reference/gearman/
```
