### ISSUE TITLE
Misleading examples for strrchr()

### ISSUE THREAD

**Issue by tgr** [php/doc-en#2867]
From manual page: https://www.php.net/manual/en/function.strrchr.php

---

These examples are unhelpful:
```
<?php
// get last directory in $PATH
$dir = substr(strrchr($PATH, ":"), 1);

// get everything after last newline
$text = "Line 1\nLine 2\nLine 3";
$last = substr(strrchr($text, 10), 1 );
?>
```
as they fail in ugly ways if $PATH only has one directly / the text only has one line.

A good example use of strrchr is getting the file extension (where you do not want to get the whole thing when there are zero separators):
```
<?php
$ext = strrchr($filename, '.');
$ext = $ext ? strtolower(substr($ext, 1) ) : '';
?>
```

**Comment by Girgias** [comment]
Fixed by #2873
