### ISSUE TITLE
`array_udiff`: Add precision to the comparison function

### ISSUE THREAD

**Issue by homersimpsons** [php/doc-en#3003]
## Issue

In the manual page: https://php.net/function.array-udiff, it is unclear that `value_compare_func` should accept value types from any array. 

## Context

I was comparing 2 arrays with different types using `array_udiff`, and I assumed that the first parameter of my comparison function was used for the first array and the second one was for the second array, so I had something like:

```php
$arrayA = [['value' => 1], ['value' => 2], ['value' => 3]];
$arrayB = [1, 2, 3];

$diff = array_udiff($arrayA, $arrayB, static fn (array $a, int $b) => $a['value'] <=> $b);
```

But this fails with the following message (https://3v4l.org/DrbU9):
```
Fatal error: Uncaught TypeError: {closure}(): Argument #2 ($b) must be of type int, array given
```

This is not mentioned in the documentation.

Furthermore, [the first comment](https://www.php.net/manual/en/function.array-udiff.php#68592) is (now?) wrong about the approach taken by `array_udiff`.
[The second comment](https://www.php.net/manual/en/function.array-udiff.php#119657) mentions "sorting" so it partly explains my issue.
[The third comment](https://www.php.net/manual/en/function.array-udiff.php#80149) mentions how to compare heterogeneous arrays and precise this behaviour in a note:
> Something interesting to note, is that the two arguments to the compare function don't correspond to array1 and array2.  That's why there has to be logic in it to handle that either of the arguments might be pointing to the more complex employee array.  (Found this out the hard way.)

## How to update the documentation ?

I wanted to make a Pull Request to add a caution to this parameter, just like the one that explains the issue with non-integer values. But it seems that this one is defined more generally, so I do not really know where I should add this caution.

The argument seems to be defined in https://github.com/php/doc-en/blob/9e534c19272a88cf031748348d54143f0e3ea413/language-snippets.ent#L791

The caution seems to be defined in https://github.com/php/doc-en/blob/9e534c19272a88cf031748348d54143f0e3ea413/language-snippets.ent#L709-L721

In my case (`array_udiff`) they seems to be referenced in https://github.com/php/doc-en/blob/9e534c19272a88cf031748348d54143f0e3ea413/reference/array/functions/array-udiff.xml#L45

Suggested caution to add:
> **Caution** `value_compare_func` parameters can be any value of any `$array` or `$arrays`. To compare heterogenous arrays ensure the function body and parameters handle any possible value. 

## Implementation details

For the record here is what is happening when using [`array_udiff`](https://github.com/php/php-src/blob/c5c189da341f5ae22368281ed55b2af9806d4b42/ext/standard/array.c#L5419):
1. Sort each array argument: https://github.com/php/php-src/blob/c5c189da341f5ae22368281ed55b2af9806d4b42/ext/standard/array.c#L5548-L5550. Here the compare functions need to handle comparison between 2 elements of the same array
2. Compare one element from an array to one from another array: https://github.com/php/php-src/blob/c5c189da341f5ae22368281ed55b2af9806d4b42/ext/standard/array.c#L5575
3. If values are the same, compare it to the next values in the sorted array: https://github.com/php/php-src/blob/c5c189da341f5ae22368281ed55b2af9806d4b42/ext/standard/array.c#L5633

## Similar functions

I did not check if there were any similar functions where the additional details could be great.

**Comment by Girgias** [comment]
Okay I checked this and expanded the provided test case, and the current behaviour is indeed odd.

https://3v4l.org/l1jLq

**Comment by homersimpsons** [comment]
> the current behaviour is indeed odd

It can definitely be explained with a small complexity analysis.

In fact the lazy solution (with 2 arrays) will lead to `n * m`: i.e. comparing all the elements from the first array to all the elements of the second array

While the optimised (currently implemented) one will lead to something like `nlog(n) + mlog(m) + max(n,m)`: i.e. sorting the first array, sorting the second array, comparing at most max(n, m) times thanks to the previous sortings. Which can effectively be simplified to `nlog(n) + mlog(m)`

Also with the current implementation it is better to optimise for "elements from the same array comparisons" as those are used a lot during sorting and re-used 

> https://3v4l.org/l1jLq

Note that the comparison function provided here looks wrong as it is not "stable" i.e. inverting 2 elements won't give the same (inverted) result (https://3v4l.org/1GLg5):
````php
var_dump(1 <=> (int) ['value' => 1]); // int(0)
var_dump(['value' => 1] <=> (int) 1); // int(1)
var_dump(['value' => 1] <=> (int) ['value' => 1]); // int(1)
```

With a correct function it is easier to understand: https://3v4l.org/k0Aqi
