### ISSUE TITLE
property-exists function should specify that it can return a null value in its declaration?

### ISSUE THREAD

**Issue by hugofintecture** [php/doc-en#3069]
From manual page: https://php.net/function.property-exists

---

![image](https://github.com/php/doc-en/assets/89129201/75cddbb6-1b3d-4616-944e-a15208b82ec5)

![image](https://github.com/php/doc-en/assets/89129201/c08fdd91-4a14-44da-9ce7-f702726d036f)

From what I understand the function can return **null** but the declaration doesn't say so. So in an IDE we don't have the info in the @return part: 

![image](https://github.com/php/doc-en/assets/89129201/85d2a459-37b2-43d5-8df3-d5da1d56b010)

**Comment by Girgias** [comment]
The function cannot return null, this is a bug in the return value section text.
