### ISSUE TITLE
Status flags passed to output handler incomplete

### ISSUE THREAD

**Issue by kkmuffme** [php/doc-en#3080]
From manual page: https://php.net/outcontrol.constants

---

>Status flags passed to output handler

Seem incomplete, since I was able to get other status codes like int 3 and 5 in specific cases, which do not correspond to any of the given constants.

**Comment by damianwadley** [comment]
As mentioned there and on the ob_start() page, the value is a _bitmask_. So 3 indicates `1 | 2` and 5 indicates `1 | 4`.
