### ISSUE TITLE
Update mb_convert_encoding doc to include deprecation notice

### ISSUE THREAD

**Issue by cdevroe** [php/doc-en#3156]
This may be an overreach, forgive me.

PHP 8.2 throws a warning regarding use of `mb_convert_encoding` (albeit with specific things like HTML_ENTITIES). [The doc](https://www.php.net/manual/en/function.mb-convert-encoding.php) does reflect that in the changelog table but should the function itself be marked as deprecated as of 8.2 or is that too broad?

Possible message (pulled from other examples in the docs)

Warning
This function has been DEPRECATED as of PHP 8.2.0. Relying on this function is highly discouraged.

**Comment by Girgias** [comment]
The function is not deprecated.
``HTML_entities`` is a "fake" encoding as far as I know and thus trying to convert to/from it doesn't make sense to my understanding.

@alexdowad could you possibly explain more?

**Comment by alexdowad** [comment]
`mb_convert_encoding` is not deprecated, and I don't think it will ever be deprecated.

What is deprecated is using `mbstring` functions to process HTML entities, UUEncode, and Base64. I think the deprecation messages indicate what the preferred PHP functions for converting HTML entities, UUEncode, and Base64 are.

@Girgias The purpose of the `mbstring` library is for processing *text* strings which use various multi-byte text encodings to represent characters. The library implements operations on *text*, such as counting the number of textual characters in a string, cutting out a range of characters... or converting between various representations of text, such as UTF-8, UTF-16, and so on.

Converting raw bytes to/from Base64 or UUEncode, or interpreting HTML entities, is a inherently different task. These are not 'text encodings' but rather 'byte encodings'. A Base64 string does not encode a sequence of characters, but rather, a sequence of bytes.

Although all the mbstring functions currently allow the user to specify "Base64", "UUEncode", etc. as the 'text encoding' of a string, the operations implemented by most `mbstring` functions do not really make sense in that context. The one `mbstring` operation which does make sense when applied to Base64 strings (for example), is "convert to raw bytes" or "convert from raw bytes". But PHP has other built-in functions which perform those operations, so providing the same functionality in `mbstring` is just duplication.

@cdevroe Probably in PHP 9.0, `mbstring` will no longer feature functionality for processing byte encodings like Base64, UUEncode, etc. There will be no deprecation messages either. But `mb_convert_encoding` will still exist.

Thanks.

**Comment by cdevroe** [comment]
Thanks for the thorough explanation @alexdowad .
