### ISSUE TITLE
Database Driver Not Found

### ISSUE THREAD

**Issue by sjchaneycle** [php/doc-en#3158]
From manual page: https://php.net/faq.databases
---
I am having issues with the Oracle driver (oci8) loading.  The function phpinfo() shows that 20-oci8.ini has loaded and OCI8 Support		 is enabled.  The error I get is:
ERROR: could not find driver
Did not connect to Oracle database

When I run the following code:
echo("<br /><br />Drivers:<br />");
foreach(PDO::getAvailableDrivers() as $driver) {
    echo $driver, '<br />';
}
I get the following:
Drivers:
mysql
sqlite

phpinfo()
PHP Version 8.1.14
System	Linux 5.14.0-362.13.1.el9_3.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Nov 24 01:57:57 EST 2023 x86_64
Build Date	Jan 4 2023 17:23:14
Build System	Red Hat Enterprise Linux release 9.2 (Plow)
Build Provider	Red Hat, Inc.
Compiler	gcc (GCC) 11.3.1 20221121 (Red Hat 11.3.1-4)
Architecture	x86_64
Server API	FPM/FastCGI
Virtual Directory Support	disabled
Configuration File (php.ini) Path	/etc
Loaded Configuration File	/etc/php.ini
Scan this dir for additional .ini files	/etc/php.d
Additional .ini files parsed	/etc/php.d/10-opcache.ini, /etc/php.d/20-bz2.ini, /etc/php.d/20-calendar.ini, /etc/php.d/20-ctype.ini, /etc/php.d/20-curl.ini, /etc/php.d/20-dom.ini, /etc/php.d/20-exif.ini, /etc/php.d/20-fileinfo.ini, /etc/php.d/20-ftp.ini, /etc/php.d/20-gettext.ini, /etc/php.d/20-iconv.ini, /etc/php.d/20-mbstring.ini, /etc/php.d/20-mysqlnd.ini, /etc/php.d/20-oci8.ini, /etc/php.d/20-pdo.ini, /etc/php.d/20-phar.ini, /etc/php.d/20-posix.ini, /etc/php.d/20-shmop.ini, /etc/php.d/20-simplexml.ini, /etc/php.d/20-sockets.ini, /etc/php.d/20-sqlite3.ini, /etc/php.d/20-sysvmsg.ini, /etc/php.d/20-sysvsem.ini, /etc/php.d/20-sysvshm.ini, /etc/php.d/20-tokenizer.ini, /etc/php.d/20-xml.ini, /etc/php.d/20-xmlwriter.ini, /etc/php.d/20-xsl.ini, /etc/php.d/30-mysqli.ini, /etc/php.d/30-pdo_mysql.ini, /etc/php.d/30-pdo_oci.ini, /etc/php.d/30-pdo_sqlite.ini, /etc/php.d/30-xmlreader.ini

extension_dir	/usr/lib64/php/modules

oci8
OCI8 Support		enabled
OCI8 DTrace Support	disabled
OCI8 Version	3.2.1
Oracle Run-time Client Library Version	19.21.0.0.0
Oracle Compile-time Instant Client Version	19.21
Directive				Local Value	Master Value
oci8.connection_class	no value	no value
oci8.default_prefetch	100			100
oci8.events				Off			Off
oci8.max_persistent		-1			-1
oci8.old_oci_close_semantics	Off	Off
oci8.persistent_timeout	-1			-1
oci8.ping_interval		60			60
oci8.prefetch_lob_size	0			0
oci8.privileged_connect	Off			Off
oci8.statement_cache_size	20		20
Statistics	
Active Persistent Connections	0
Active Connections	0

**Comment by damianwadley** [comment]
Sorry, but your problem does not imply a bug in PHP itself.  For a list of more appropriate places to ask for help using PHP, please visit http://www.php.net/support.php as this bug system is not the appropriate forum for asking support questions. Thank you for your interest in PHP.
