### ISSUE TITLE
sodium_crypto_pwhash misleading $salt length requirement

### ISSUE THREAD

**Issue by striker4150** [php/doc-en#3160]
On manual page [https://www.php.net/manual/en/function.sodium-crypto-pwhash.php](https://www.php.net/manual/en/function.sodium-crypto-pwhash.php).

According to the parameters, `$salt` should "have a length of _at least_ `SODIUM_CRYPTO_PWHASH_SALTBYTES` bytes". However, according to my testing on PHP 8.1.15 and 8.2.10, it requires _exactly_ `SODIUM_CRYPTO_PWHASH_SALTBYTES` bytes.

(NOTE: `SODIUM_CRYPTO_PWHASH_SALTBYTES` is currently set to `16` bytes)

Running `bin2hex(sodium_crypto_pwhash(32, "a", str_repeat("a", SODIUM_CRYPTO_PWHASH_SALTBYTES), SODIUM_CRYPTO_PWHASH_OPSLIMIT_MODERATE, SODIUM_CRYPTO_PWHASH_MEMLIMIT_MODERATE));` works, but increasing/decreasing the length of the salt causes it to throw a `SodiumException`.

Even though the underlying algorithms (Argon2i and Argon2id) can accept between `8` to `2^32 - 1` bytes, it seems that this PHP function uses a fixed salt size of `SODIUM_CRYPTO_PWHASH_SALTBYTES`.

Could someone verify this?

**Comment by damianwadley** [comment]
Indeed, the length is enforced to be exactly SALTBYTES long.

https://github.com/php/php-src/blob/php-8.3.2/ext/sodium/libsodium.c#L1466-L1469
```c
	if (salt_len != crypto_pwhash_SALTBYTES) {
		zend_argument_error(sodium_exception_ce, 3, "must be SODIUM_CRYPTO_PWHASH_SALTBYTES bytes long");
		RETURN_THROWS();
	}
```

This is consistent with what libsodium requires in its underlying function, too.

https://doc.libsodium.org/password_hashing/default_phf#key-derivation
> ...and a salt salt whose fixed length is `crypto_pwhash_SALTBYTES` bytes.
