### ISSUE TITLE
FILTER_VALIDATE_BOOL vs FILTER_VALIDATE_BOOLEAN behavior difference not documented

### ISSUE THREAD

**Issue by Aycarambo** [php/doc-en#3175]
From manual page: https://php.net/filter.filters.validate

---

Documentation states that FILTER_VALIDATE_BOOL is simply an alias for FILTER_VALIDATE_BOOLEAN but both do not behave in the same way.

filter_var(NULL, FILTER_VALIDATE_BOOLEAN); // bool(false)
filter_var(NULL, FILTER_VALIDATE_BOOL);        // NULL

Why is that ?

**Comment by kamil-tekiela** [comment]
Am I missing something? https://3v4l.org/Hp37N

**Comment by Girgias** [comment]
This does not seem like a documentation bug.
