### ISSUE TITLE
Incorrect return types(`void` is appended)

### ISSUE THREAD

**Issue by junichi11** [php/doc-en#3197]
From manual page: https://php.net/function.apache-child-terminate

Return type is incorrect:
```php
apache_child_terminate(): voidvoid
```
Other many functions also seem to be appended `void`.
e.g.
- https://www.php.net/manual/en/function.apache-get-modules.php
- https://www.php.net/manual/en/apcuiterator.current.php
- etc.

---

**Comment by Girgias** [comment]
@haszi seems like the type linking change broke something https://github.com/php/phd/commit/45cffd68d3afe5c8be101c66fbb03e5b5909970a

**Comment by haszi** [comment]
> @haszi seems like the type linking change broke something [php/phd@45cffd6](https://github.com/php/phd/commit/45cffd68d3afe5c8be101c66fbb03e5b5909970a)

@Girgias Oof. I just took a quick look and it seems that there is a large number of doc files with this kind of format:

```xml
<methodsynopsis>
 <type>void</type><methodname>apache_child_terminate</methodname>
 <void/>
</methodsynopsis>
```

with the first `<type>void</type>` being all kinds of types in the different methods/functions. While this seems incorrect to me (what do the two `void`s each represent? One is the return type and the other...), there are over a thousand files like this. 

I'll only have time to take a closer look tonight (in 5-6 hours) so if this is urgent, please revert that change and I'll think of a way to suppress the superfluous `<void/>` elements (and I'll also make a script to remove these from the docs, if you agree).

Also, type linking seems to add `.html` at the end of the links which doesn't work, so I'll have to remove those too. `It was working on my machine` ™️

**Comment by Girgias** [comment]
The `</void>` means that the function has no parameters the return type is always before the function name even if it is void :)

**Comment by haszi** [comment]
> The `</void>` means that the function has no parameters the return type is always before the function name even if it is void :)

Of course... What an epic screwup! :-( I don't know how I missed something this obvious but I'll fix this tonight.

**Comment by Girgias** [comment]
It happens :)

**Comment by junichi11** [comment]
Thank you for fixing it :)
