### ISSUE TITLE
PHP 8.0 incompatible changes mistake?

### ISSUE THREAD

**Issue by aruku** [php/doc-en#3231]
I've been going through this docs because I finally had to update to PHP 8.1, and I tested this:
`echo (bool) 42 == "42foo"; // 1`
https://3v4l.org/BlEiF

According to the docs, that should be false for PHP >= 8.0: https://www.php.net/manual/en/migration80.incompatible.php

Am I mistaken?

Thank you.

**Comment by damianwadley** [comment]
Type casts have higher precedence than comparison operators, so you're comparing a boolean with a string.
https://www.php.net/manual/en/language.operators.precedence.php

Wrap the comparison in parentheses and _then_ apply the (pointless) cast.
https://3v4l.org/gfMtJ
