### ISSUE TITLE
Wrong arrow function code example (third example)

### ISSUE THREAD

**Issue by pjotrsavitski** [php/doc-en#3241]
From manual page: https://php.net/functions.arrow

---

Third example has an incorrect arrow function `static fn(): int => $x;` that is missing an argument. The correct code should be `static fn($x): int => $x;`

**Comment by kamil-tekiela** [comment]
Are you sure? It looks like valid code?

**Comment by damianwadley** [comment]
The code is valid, provided you assume there's an integer `$x` defined outside the function, but I think the point is that all the other lines in that example have `$x` as an argument.
```php
fn(array $x) => $x;
static fn(): int => $x; // odd one out
fn($x = 42) => $x;
fn(&$x) => $x;
fn&($x) => $x;
fn($x, ...$rest) => $rest;
```
