### ISSUE TITLE
ini_set('date.sunrise_zenith', 90) has no effect

### ISSUE THREAD

**Issue by userpointfi** [php/doc-en#3262]
From manual page: https://php.net/datetime.configuration

---

Setting date.sunrise_zenith with ini_set has no effect, even though the manual says it can be set at any time.

The code below sets 'date.sunrise_zenith', then gets it to verify it has been set correctly. But the calculation gives the exact same time, regardless of the setting.

$timestamp = 1710192043;
$lat = 64;
$lon = 24;

var_dump(ini_get('date.sunrise_zenith'));
$sun = date_sun_info($timestamp, $lat, $lon);
var_dump($sun['sunrise']);

ini_set('date.sunrise_zenith', 90);
var_dump(ini_get('date.sunrise_zenith'));

$sun = date_sun_info($timestamp, $lat, $lon);
var_dump($sun['sunrise']);

ini_set('date.sunrise_zenith', 95);
var_dump(ini_get('date.sunrise_zenith'));
$sun = date_sun_info($timestamp, $lat, $lon);
var_dump($sun['sunrise']);

Output:

string(9) "90.833333"
int(1710132720)
string(2) "90"
int(1710132720)
string(2) "95"
int(1710132720)

**Comment by derickr** [comment]
This is already documented on that [page](https://www.php.net/manual/en/datetime.configuration.php#ini.date.sunrise-zenith):

> Note: The first four configuration options are currently only used by [date_sunrise()](https://www.php.net/manual/en/function.date-sunrise.php) and [date_sunset()](https://www.php.net/manual/en/function.date-sunset.php).

`date_sun_info()` already returns multiple values for different zeniths, and there is an [issue open](https://github.com/php/php-src/issues/13067) to request a user-configured zenith already too.
