### ISSUE TITLE
array_column parameter issue

### ISSUE THREAD

**Issue by Hemanth-VSR** [php/doc-en#3304]
From manual page: https://php.net/function.array-column

--

when I send extra more parameter inside the array_column it is not printing the correct form of data think so it is misbehaving for that..
eg : $first_names = array_column($records, 'first_name' , 'last_name');

**Comment by damianwadley** [comment]
Looks fine to me. https://3v4l.org/XsDch

Read the documentation carefully and check that you're calling the function correctly.
