### ISSUE TITLE
trigger_error with E_USER_ERROR will terminate script processing

### ISSUE THREAD

**Issue by theking2** [php/doc-en#3309]
From manual page: https://php.net/function.trigger-error

Missing is the special meaning of passing a parameter E_USER_ERROR which terminates the script.
---

**Comment by cmb69** [comment]
Literally the first sentence on that page is: "trigger_error — Generates a user-level error/warning/notice message"

And the constants (like `E_USER_ERROR`) are linked to their description.

I'm not sure what to improve on this page in this regard.

**Comment by Girgias** [comment]
Yes, I am not sure what else there is to say here, especially as this constant in deprecated as of PHP 8.4.

**Comment by theking2** [comment]
I was indeed unclear in my comment. 
What I mean is that the function will issue an exit(1) under the conditions of E_USER_ERROR. 
Also it will _not_ do so if a custom error handler is registered.

**Comment by theking2** [comment]
> Yes, I am not sure what else there is to say here, especially as this constant in deprecated as of PHP 8.4.

Is E_USER_ERROR deprecated in 8.4?

**Comment by cmb69** [comment]
@theking2, yes, see https://github.com/php/php-src/blob/ebee8df27edf7ecfbdc7ff87662f2f0d30859120/UPGRADING#L499-L500.

**Comment by theking2** [comment]
You are right although is rather hard to find (google didn't give results on E_USER_ERROR deprecated). But if that is the case why isn't this mentioned in the article?

**Comment by cmb69** [comment]
Because PHP 8.4.0 is not yet released, and apparently nobody updated the PHP user manual yet.

**Comment by theking2** [comment]
Ok fair. What I'm struggling with now is if for compelling reasons exiting scrips is not recommended what _would_ be the proper behavior in fatal conditions? Would this custom errorhandler deal with it in a proper way? 

```php
set_error_handler( function ($errno, $errstr, $errfile, $errline) {
	// error was suppressed with the @-operator
	if( 0 === error_reporting() ) {
		return false;
	}
	switch($errno) {
		default:
			LOG->error( "Unknown error type: [$errno] $errstr", [ 'file' => $errfile, '@' => $errline ] );
			throw new ErrorException( $errstr, 0, $errno, $errfile, $errline );
		case E_USER_ERROR: // fall through
		case E_WARNING: // PHP Warnings are errors
			LOG->error( $errstr, [ 'file' => $errfile, '@' => $errline ] );
			throw new ErrorException( $errstr, 0, $errno, $errfile, $errline );
		case E_USER_DEPRECATED:
		case E_DEPRECATED:
			LOG->error( "DEPRECATED $errstr", [ 'file' => $errfile, '@' => $errline ] );
			break;
		case E_USER_WARNING: // fall through
		case E_NOTICE: // PHP Notices are warnings
			LOG->warning( $errstr, [ 'file' => $errfile, '@' => $errline ] );
			break;
		case E_USER_NOTICE:
			LOG->notice( $errstr, [ 'file' => $errfile, '@' => $errline ] );
			break;
		case E_ERROR: // fall through
		case E_RECOVERABLE_ERROR:
			LOG->critical( $errstr, [ 'file' => $errfile, '@' => $errline ] );
			throw new ErrorException( $errstr, 0, $errno, $errfile, $errline );

	}
	/* Don't execute PHP internal error handler */
	return true;
} );
```

BTW I added this as notes (for myself primarily) to the `trigger_error()` article
