### ISSUE TITLE
Report a bug

### ISSUE THREAD

**Issue by hiep1312** [php/doc-en#3373]
From manual page: https://php.net/reserved.variables.server

---
I'd like to inform the developers that while learning PHP on your website, I noticed that when accessing the $_SERVER variable, some values are missing or incomplete. However, when I switch to Spanish, the values of the $_SERVER variable are complete, whereas they are incomplete in other languages. I hope you can fix this issue. Thank you.
---
![Screenshot (23)](https://github.com/php/doc-en/assets/98216285/d8076ba0-eeca-46c8-8f2a-528ded2bb79b)
![Screenshot (26)](https://github.com/php/doc-en/assets/98216285/e65ec3cb-3439-486e-8ed8-97f90f93a217)

**Comment by Girgias** [comment]
The Spanish doc is the one outdated and is incorrect, as the English doc used to have them, but it as those are set by the server they might not be available and others might also be.
