### ISSUE TITLE
RFC: Disjunctive Normal Form Types - invalid intersection example

### ISSUE THREAD

**Issue by RyanFarrah67** [php/doc-en#3378]
## Environment

Last version at this day : 8.3.7

## Documentation concerned 

DNF RFC, covariance part : https://wiki.php.net/rfc/dnf_types#return_co-variance

## Problem

It seems that the example and the code are not valid for one class implementation shown in the manual.

Indeed this is the base interface : 

```
interface ITest {
  public function stuff(): (A&B)|D;
}
```

The part we're interested in is the intersection type `(A&B)`, we don't care about `D` here.

This class below extends the previous interface : 

```
// Acceptable, since C is a subset of A&B,
// even though it is not identical.
class TestThree implements ITest {
  public function stuff(): C|D {}
}
```
Given these definitions from the RFC : 

```
interface A {}
interface B {}
interface C extends A {}
```

**We see that `C` is a child interface of `A` only but not `B` so the `A&B` contract doesn't pass**. 
It will produces a compile fatal error. 

## Sample

Here's a full example of the problematic type declaration : 

```
<?php

interface A {}
interface B {}
interface C extends A {}
interface D {}

interface ITest {
  public function stuff(): (A&B)|D;
}

// Not Acceptable, since C is not a subset of A&B,
// it's just a subset of A
class Test implements ITest {
  public function stuff(): C|D {}
}
```
### Output 

`Fatal error: Declaration of Test::stuff(): C|D must be compatible with ITest::stuff(): (A&B)|D`

**Comment by Girgias** [comment]
The text of an RFC is not part of the documentation, so this is not a doc bug.

This is minor issue in the RFC text that got unnoticed but doesn't really have any importance so I'm just going to close this.

**Comment by RyanFarrah67** [comment]
> The text of an RFC is not part of the documentation, so this is not a doc bug.
> 
> This is minor issue in the RFC text that got unnoticed but doesn't really have any importance so I'm just going to close this.

Ok.

For the doc bug part, yes I didn't know where to submit it and didn't want to directly communicate to the mailing list.
