### ISSUE TITLE
ob_start PHP_OUTPUT_HANDLER_FLUSHABLE wrong ob_end_flush instead of ob_flush

### ISSUE THREAD

**Issue by kkmuffme** [php/doc-en#3399]
https://www.php.net/manual/en/function.ob-start.php

In the table
>Constant	Functions
>PHP_OUTPUT_HANDLER_FLUSHABLE	ob_end_flush()

Should be
>PHP_OUTPUT_HANDLER_FLUSHABLE	ob_flush()

Since `ob_end_flush` only depends on `PHP_OUTPUT_HANDLER_REMOVABLE` - it's correctly documented here https://www.php.net/manual/en/outcontrol.constants.php#constant.php-output-handler-flushable

**Comment by Girgias** [comment]
@haszi can you have a look at this as you rewrote the output buffering docs recently.

**Comment by haszi** [comment]
> @haszi can you have a look at this as you rewrote the output buffering docs recently.

That should indeed be `ob_flush()` instead of `ob_end_flush()`. I've opened a PR.
