### ISSUE TITLE
Support more than parameter attributes attributes

### ISSUE THREAD

**Issue by TimWolla** [php/doc-en#3405]
since #3402 / php/phd#127 parameter attributes are supported, but other types of attributes are not yet.

Support should be added for all types of attribute. Class attributes are already in use (the `#[\Attribute]` attribute) and function / method attributes might be added with php/php-src#11293.

**Comment by haszi** [comment]
@Girgias Based on the current class, function and method markup, and the new markup for parameter attributes, would the below markup work for class and function/method attributes?

```xml
<ooclass>
  <modifier role="attribute">AttributeName</modifier>
  <classname>DateTime</classname>
</ooclass>
```

```xml
<methodsynopsis>
  <modifier role="attribute">AttributeName</modifier><modifier>public</modifier> <type>string</type><methodname>CURLFile::getFilename</methodname>
  <void/>
</methodsynopsis>
```

**Comment by Girgias** [comment]
I think the proposed markup makes sense, and is compliant with DocBook 5.2

**Comment by haszi** [comment]
The class attribute on the class synopsis and function/method attribute on the function/method pages could look like this:

![class_attribute](https://github.com/php/doc-en/assets/13745441/fe6f7d55-59bb-48ce-8436-3e9e1a5e594d)

![function_method_attribute](https://github.com/php/doc-en/assets/13745441/9940e067-14c3-403a-8745-f1c23c6909f6)

**Comment by haszi** [comment]
How should the method listings on class synopsis pages be handled? Attributes on above the method signature or on the same line?

![method_list_attribute_1](https://github.com/php/doc-en/assets/13745441/e1a0aab7-dfa9-4c35-b22d-c5f3b86f00f2)
![method_list_attribute_2](https://github.com/php/doc-en/assets/13745441/c95e892c-f78c-4c04-afa6-0cc2a4e9f693)

**Comment by Girgias** [comment]
I think for methods it probably should be above the method signature, @TimWolla @kocsismate what do you think?

**Comment by TimWolla** [comment]
I agree. Putting it above the method would match the common userland style guides and it would better scale with a larger number of attributes (e.g. both `#[\Deprecated]` and `#[\Override]`).

Please also add the leading backslash for copy-and-paste safety with regard to namespaces.

**Comment by kocsismate** [comment]
Yes, above please! :)
