### ISSUE TITLE
Empty `id` attribute in the `Examples` section

### ISSUE THREAD

**Issue by MaximePinot** [php/doc-en#3428]
First and foremost, I'm sorry if this is not the right place to report this issue. I do not know if this is related to `doc-en`, `doc-base`, `phd` or something else. 😬 

If you go to any function's documentation ([here, for example](https://www.php.net/manual/en/function.forward-static-call)) and inspect the `Examples` section, you can see that the example `div` element is `<div class="example" id=“”>...</div>` (empty `id` attribute) while it should be `<div class="example" id=“example-XXX”>...</div>`.

![image](https://github.com/php/doc-en/assets/13469986/955a2e45-f5d9-4851-8f96-bae82690dbe3)

I generated the documentation on my computer following [these steps](https://github.com/php/phd/blob/master/README#L27) and the issue is not occurring. The IDs are not empty. So, I do not know how to fix this.

If I can help, please let me know what I can do. 😃

**Comment by Girgias** [comment]
This looks like a PhD issue, the `xml:id` is specified in the source but somehow got lost... this *used* to work. @haszi any idea what could cause this?

**Comment by haszi** [comment]
The `xml:id`s for examples are mostly autogenerated. Because the [example listing](https://www.php.net/manual/en/indexes.examples.php) is generated but only the first example actually links to the appropriate example, I think indexing and rendering are generating the IDs in a slightly different way.

**Comment by haszi** [comment]
I've just opened a PR in PhD with a test for this. Unfortunately I can also not reproduce this issue locally.

Looking at `php.net`, I can see that Indexing is working correctly (the example listing and its links are generated correctly) but after the first one the `xml:id`s of the examples are off. All these `xml:id`s contain a sequential number which would match their example listing # but all these are 3 times what they're supposed to be + 1.

**Comment by Girgias** [comment]
Right, seem like a possible issue in the build system there then @derickr how are the docs on the website currently built?

**Comment by haszi** [comment]
@Girgias I've just managed to reproduce this issue by rendering 3 formats with PhD at the same time. And I've also found the static variable that was used, swapped it with a non-static property and the issue is gone. I'll open a PR in PhD as soon as I figure out how to write a test for this.
