### ISSUE TITLE
in_array

### ISSUE THREAD

**Issue by Phantom2** [php/doc-en#3435]
From manual page: https://php.net/function.in-array
Please note, that a request from a database under windows requires  "\r\n" for explode!
---

**Comment by damianwadley** [comment]
What?

**Comment by Girgias** [comment]
This is not an issue with PHP

**Comment by Phantom2** [comment]
Please excuse my english.

 

I started to use php after 15 years again. 

I spent a lot of time to find out, that the mysql linefeed of windows is \r\n.

 

Perhaps you can leave an example or note. 

 

                $row = mysqli_fetch_assoc($res);

                $Zugang = str_replace("\r\n", "\n", $row["zugang"]);

                $arrZugang = explode("\n",$Zugang);

 

Best Klaus

 

 

Von: Damian Wadley ***@***.***> 
Gesendet: Dienstag, 4. Juni 2024 16:06
An: php/doc-en ***@***.***>
Cc: Phantom2 ***@***.***>; Author ***@***.***>
Betreff: Re: [php/doc-en] in_array (Issue #3435)

 

What?
