### ISSUE TITLE
docs fail to load

### ISSUE THREAD

**Issue by williamoferreira** [php/doc-en#3452]
From manual page: https://php.net/function.str-replace

---

just made a search from global search for the function "str-replace" and hit `enter`;

Header bar, footer, breadcrumb and some other structural elements loads fine but the page content no.

i think my personal notebook and my work computer has nothing special to justify. Both browses from same IPS but on diferent cities. My Work computer have a dlp software but my Windows 11 notebook no.

Need some extra info?

**Comment by cmb69** [comment]
Works fine for me. Is this still an issue for you, or has it been an intermittent error.

Also note that this ticket doesn't belong into this repository. It should be either moved to https://github.com/php/web-php, or possibly to somewhere else.

**Comment by jimwins** [comment]
Works now for me, too, it may have been a transient issue. Feel free to open a new issue in the https://github.com/php-web-php repository if it crops up again.
