### ISSUE TITLE
PHP 8.2.18

### ISSUE THREAD

**Issue by richardsyeo** [php/doc-en#3453]
Using AWS Amazon Linux 2023.
Recent upgrade from PHP 8.2.15 to 8.2.18
When PHP 8.2.18 responds to HEAD request but returns body with content-length header the client receives the body but the content-length header is missing.
Our code has not changed. Isolated to after the dnf upgrade.

**Comment by damianwadley** [comment]
If you're responding to a HEAD with a body then you need to fix that: it's incorrect to return any body at all, and clients are supposed to ignore it. That aside, a body without a Content-Length is valid.

I don't see anything in the PHP changelog between those two versions. Are you sure you didn't upgrade, say, your web server software as well?

**Comment by richardsyeo** [comment]
There was a apache httpd update recently but the change in behaviour I describe does not appear to be cause by the httpd update as we checked that.

I understand that HEAD request shouldn't result in a body but this (stripped Content-length header) appears to be a change of behaviour that is not documented. It makes me wonder whether it was intentional or unintentional and whether any other change that we have not discovered could be present. Seems odd to strip the header but not the body and surely should be able to return whatever without it being stripped.
