### ISSUE TITLE
YetiForce CRM 7.0.1 LDAP Integration issues

### ISSUE THREAD

**Issue by thejaykansara** [php/doc-en#3555]
![aaaa](https://github.com/user-attachments/assets/8d9fdfc3-e2a8-4cc7-9792-de32b7e5cc9a)
![image](https://github.com/user-attachments/assets/26800732-d4ff-434c-b0ba-ff4e7d6ecf5b)

As a beginner working with YetiForce, I couldn't find the LDAP settings or LDAP map options in version 7.0.1. Could you guide me on how to configure LDAP for this latest version?

**Comment by damianwadley** [comment]
We do not maintain that application.

You can find their documentation [here](https://doc.yetiforce.com/).
