### ISSUE TITLE
uopz_compose is not listed as `deprecated` in the sidebar

### ISSUE THREAD

**Issue by leander-hass** [php/doc-en#3573]
From manual page: https://php.net/function.uopz-compose

---

Hey there, the red box indicates it should be in the deprecated section of the corresponding navigation.

**Comment by cmb69** [comment]
Indeed, the repective `deprecated` attribute is missing:

https://github.com/php/doc-en/blob/d73dfcdcebcffe220074597f82c2478ed5dea572/reference/uopz/versions.xml#L17
