### ISSUE TITLE
MariaDB support in documentation

### ISSUE THREAD

**Issue by robertsilen** [php/doc-en#3628]
Hello, any particular reason MariaDB is not mentioned or explained in any of the mysql extensions at https://www.php.net/manual/en/mysql.php ? I mean, that's what people are probably running in practise, right? Thank you for any comments on this. 

This is part of my efforts I describe in my blog [Improving MariaDB Support in Open Source Projects](https://mariadb.org/improving-mariadb-support-in-open-source-projects/).

**Comment by robertsilen** [comment]
> Does it have to be? Where and why would you see it mentioned?

I was looking at (non-official) instructions on how to install MyBB, and it advised on installing MySQLi, and then later in the in instructions you could see the terminal was MariaDB. I know MyBB supports MariaDB, and I know many Linux run MariaDB by default, and I know MySQL and MariaDB are diverging, and I prefer MariaDB - so I was trying to figure out if also MySQLi support MariaDB, and the documentation doesn't mention anything about MariaDB. It's a bit odd that [MySQLi's Wikipedia article](https://en.wikipedia.org/wiki/MySQLi) says it supports MariaDB/MySQL/Percona, but the reference is another non-official instructions, again, not the official documentation. 

So, could the documentation mention MySQLi and others support MariaDB to save time of the next person who wonders about this? Or is there a reason not to?

**Comment by kamil-tekiela** [comment]
We could do that, but I am not convinced this is a good idea. 

I am not even sure if the documentation says anywhere that MySQL is supported. The only information I see is about the MySQL 5.1 features which is a bit ambiguous. 

I can see how from the perspective of a novice this is a perfectly valid question.  Maybe we should have a page dedicated to this topic in the PHP manual. The only thing I am worried about is whether we actually officially support these DB vendors. Right now, it works on the basis of the mutual adherence to the MySQL protocol. Is it a good idea to step out of this boundary and state which vendors are officially supported?

**Comment by kamil-tekiela** [comment]
Or we could say that PDO_mysql and mysqli use mysqlnd which adheres to the MySQL protocol and then list **examples** of vendors that implement it.

**Comment by jimwins** [comment]
Another example of a database server that uses the MySQL protocol is [TiDB](https://www.pingcap.com/tidb/).

I think the best place to clarify that these extensions support the MySQL protocol and not just the MySQL Server, and mention these other servers, would be in `reference/mysqlinfo/concepts.xml` and `reference/mysqlinfo/set.xml`.

Reviewing all of the MySQL APIs to make them less tied to Oracle's MySQL Server would probably be a pretty large task.

**Comment by robertsilen** [comment]
Thanks @jimwins @kamil-tekiela , I can put together a PR to reflect the suggestions: 

In [/manual/en/set.mysqlinfo.php](https://www.php.net/manual/en/set.mysqlinfo.php), i.e. [/reference/mysqlinfo/set.xml](https://github.com/php/doc-en/blob/master/reference/mysqlinfo/set.xml) add to the intro: "The extensions listed support the MySQL protocol. Examples of compatible servers are [MariaDB Server](https://mariadb.org), [MySQL Server](https://www.mysql.com/), [Percona Server for MySQL](https://www.percona.com/mysql/software/percona-server-for-mysql) and [TiDB](https://www.pingcap.com/tidb/)."

For [/manual/en/mysqlinfo.concepts.php](https://www.php.net/manual/en/mysqlinfo.concepts.php) i.e. [/reference/mysqlinfo/concepts.xml](https://github.com/php/doc-en/blob/master/reference/mysqlinfo/concepts.xml) a whole section is needed? Perhaps something like the following would be enough to get started? 

**Section title:** Examples of compatible servers 
The MySQL extensions support the MySQL protocol. Examples of compatible servers are: 
* [MariaDB Server](https://mariadb.org)
* [MySQL Server](https://www.mysql.com/)
* [Percona Server for MySQL](https://www.percona.com/mysql/software/percona-server-for-mysql)
* [TiDB](https://www.pingcap.com/tidb/)

**Comment by kamil-tekiela** [comment]
@cmb69 Do we have any rules about adding examples of external products like this? Has there ever been a precedent?

**Comment by cmb69** [comment]
See e.g. https://www.php.net/manual/en/dba.requirements.php.

**Comment by jimwins** [comment]
Another one: ProxySQL, https://proxysql.com

A similar case of adding examples about 'external products' in the documentation is the installation instructions for different cloud providers.

**Comment by robertsilen** [comment]
I created a [PR](https://github.com/php/doc-en/pull/3639) now. I hope I got the XML formatting right. As I originally intended, I included database servers as examples (MariaDB, MySQL, Percona, TiDB). I wasn't sure about ProxySQL as it isn't strictly a database server - it can of course be added.
