### ISSUE TITLE
Potential deprecated list of "Experimental Extensions"

### ISSUE THREAD

**Issue by iszmais** [php/doc-en#3643]
From manual page: https://php.net/extensions.state

---

Hello,

I stumbled upon this manual page and was quite irritated about the list of experimental extensions (also that there are no deprecated extensions at all).
Since I could not find any other source that states these extensions to be experimental, im not sure if this data is still valid.

Could it be that this documentation itself is deprecated?

Greetings,
@iszmais

**Comment by cmb69** [comment]
Indeed, this page is grossly out-dated. There is https://github.com/php/doc-base/blob/master/scripts/qa/extensions.xml.php which is able to update https://www.php.net/manual/en/extensions.alphabetical.php and https://www.php.net/manual/en/extensions.membership.php, but https://www.php.net/manual/en/extensions.state.php is apparently not yet supported. A PR would be welcome.
