### ISSUE TITLE
extract(): argument #1 is not passed by reference

### ISSUE THREAD

**Issue by claudepache** [php/doc-en#3676]
From manual page: https://php.net/function.extract

The documented function signature is:

```php
extract(array &$array, int $flags = EXTR_OVERWRITE, string $prefix = ""): int
```

It should be:

```php
extract(array $array, int $flags = EXTR_OVERWRITE, string $prefix = ""): int
```

i.e., the first argument is not passed by reference.

Test case:

```php
extract([ 'answer' => 42 ]);
```

If the argument were passed by reference, an Error (“Argument \#1 ($array) cannot be passed by reference”) would have be thrown. It has never been the case.

**Comment by cmb69** [comment]
See https://github.com/php/php-src/blob/7e45e57d8f85f8d1fa2521028f394da30268187d/ext/standard/basic_functions.stub.php#L1643-L1644; `$array` is prefer-ref, i.e. if possible the variable is passed by-ref, and only otherwise by-val.

So the documentation is correct regarding the implementation.
