### ISSUE TITLE
Documentation says is_file() returns true for regular files but it also returns true for symlinks pointing to regular files

### ISSUE THREAD

**Issue by ohyeaah** [php/doc-en#3719]
From manual page: https://php.net/function.is-file

It says "Tells whether the filename is a regular file".
But it also returns true for symlinks pointing to regular files. And symlinks are not regular files.

It should instead say "Tells whether the given file is a regular file or a symlink pointing to a regular file".

**Comment by cmb69** [comment]
It's basically like [`stat()`](https://www.php.net/manual/en/function.stat.php):

> If filename is a symbolic link, statistics are from the file itself, not the symlink.

In other words, unless explicitly mentioned, symlinks are resolved transparently.
