### ISSUE TITLE
ZipArchive::EXCL wrong behavior

### ISSUE THREAD

**Issue by chaar123** [php/doc-en#3736]
```
function openArchive($name) : string 
{	
 $archive = new ZipArchive();
 $rc = $archive->open($name, ZipArchive::EXCL);
 if ($rc !== true) {
	 return match($rc) {
				 ZipArchive::ER_EXISTS => __FUNCTION__.' error: File exists already',
				 ZipArchive::ER_NOENT => __FUNCTION__.' error: No such file',
				default => 'failed',
			};
 } 
 return __FUNCTION__.'  succes';
}
	
 $file = '/tmp/notexists.txt';
 echo openArchive($file).PHP_EOL;

 $file = '/tmp/exists.txt';
 file_put_contents($file, 'ok');
 echo openArchive($file).PHP_EOL;
```
Resulted in this output:
```
openArchive error: No such file
openArchive error: File exists already
```
But I expected this output instead:
```
openArchive success
openArchive error: File exists already
```

**Comment by damianwadley** [comment]
https://www.php.net/manual/en/zip.constants.php#ziparchive.constants.create
> ZipArchive::EXCL (int)
> Error if archive already exists.

The archive does not exist (in the first call to openArchive) so the `EXCL` flag will not make a difference.

open() expects to open an existing archive. If you want to allow "opening" a file that does not exist then use the `CREATE` flag:

> ZipArchive::CREATE (int)
> Create the archive if it does not exist.

```php
$rc = $archive->open($name, ZipArchive::CREATE | ZipArchive::EXCL);
```

You may want to use `OVERWRITE` too.
