### ISSUE TITLE
Document what the manual considers as a "scalar" type

### ISSUE THREAD

**Issue by Girgias** [php/doc-en#3939]
This comes up quite often but the manual does not have any place where it defines what a scalar type is.

Would integrate note https://www.php.net/manual/en/function.is-scalar.php#55813 and could simplify the `is_scalar()` docs.

**Comment by ekinhbayar** [comment]
Would the [types.intro](https://www.php.net/manual/en/language.types.intro.php) page be a good candidate for mentioning this?

**Comment by cmb69** [comment]
Yes. Maybe we should have two lists of types (scalar vs. non-scalar) there. Could then simplify the `is_scalar()` page to link to types.intro instead of mentioning there which types are scalar, and which are not.

**Comment by ekinhbayar** [comment]
If nobody has started on this, I can take some time to prep a first draft over the weekend.

**Comment by ekinhbayar** [comment]
Browsing around a bit, I also noticed that there's actually a mention of scalar types as part of [types.type-system](https://www.php.net/manual/en/language.types.type-system.php) 🤔
