### ISSUE TITLE
There is a low-level error in the document where 2024 was written as 2021

### ISSUE THREAD

**Issue by BQ97** [php/doc-en#4022]
![222222](https://github.com/user-attachments/assets/30c813c1-d963-4e3d-b91d-b5bb5847dacc)

**Comment by Girgias** [comment]
@NattyNarwhal did you mess up part of the announcement?

**Comment by BQ97** [comment]
I opened the PHP official website and saw this issue, which is why I gave you feedback
&nbsp;


?　&nbsp;&nbsp;Ohh
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Gina Peter ***@***.***&gt;; 
发送时间: 2024年11月8日(星期五) 下午5:44
收件人: ***@***.***&gt;; 
抄送: "♚　  ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [php/doc-en] There is a low-level error in the document where 2024 was written as 2021 (Issue #4022)














 
@NattyNarwhal did you mess up part of the announcement?

**Comment by nielsdos** [comment]
Looks like this already got fixed.
