### ISSUE TITLE
Extend documentation that bcrypt is limited to 72 bytes

### ISSUE THREAD

**Issue by thbley** [php/doc-en#4027]
### Description

Please extend documentation that bcrypt is limited to 72 bytes and/or raise a warning/error/exception if input length is >72 bytes.

The following code:

https://3v4l.org/Q3Q43

Resulted in this output:
```
1
```

But I expected this output instead:
```
0
```

### PHP Version

php 8.1-8.3, maybe 8.4

**Comment by Girgias** [comment]
I am not exactly sure what else should be done, a caution has existed in the manual for ages on https://www.php.net/manual/en/function.password-hash.php

![image](https://github.com/user-attachments/assets/f0052dd5-3f66-42e3-a267-b62ad37ac10f)

**Comment by thbley** [comment]
Sorry, I missed the yellow box.

Any opinions on raising E_WARNING on truncated password input?

**Comment by Girgias** [comment]
This is something that needs to be raised on the internals mailing list, as this is a language change.

I will close this issue because there is nothing else to do here, but do feel free to email the mailing list.
