### ISSUE TITLE
Validation Filter documentation is gone

### ISSUE THREAD

**Issue by kevin-j-morse** [php/doc-en#4141]
Sometime after September 25, the documentation page for Validation Filters https://www.php.net/manual/en/filter.filters.validate.php has disappeared as well as the link to this documentation on the Types of filters page https://www.php.net/manual/en/filter.filters.php

**Comment by Girgias** [comment]
Yes, this is an intended change from #3941 

The whole objective is to move all the sanitization filters into the constant page aswell, as it was outdated, had rendering issues (and still has) and a bunch of other issues.

**Comment by kamil-tekiela** [comment]
This section has now been completely removed in #4158

**Comment by Girgias** [comment]
Closing, as this is not really applicable.
