### ISSUE TITLE
The `final` modifier to methods coming from traits

### ISSUE THREAD

**Issue by mmalferov** [php/doc-en#4189]
Can someone explain what the last code example on the [Trait](https://www.php.net/manual/en/language.oop5.traits.php#language.oop5.traits.final-methods) page means? This example works down to PHP 5.4.0:

```php
<?php

trait ConstantsTrait
{
    public function method()
    {
        echo 'Hello';
    }
}

class ConstantsExample
{
    use ConstantsTrait;

    final public function method()
    {
        echo 'Hello World';
    }
}
```

What exactly was allowed to do with traits and the `final` modifier in PHP 8.3.0?

**Comment by alexandre-daubois** [comment]
Indeed, I made a mistake in this example. Sorry for that and thanks for spotting it!

The changelog says "The final modifier may now be used when using a method from a trait.". I'm not 100% sure what it means, then... 🤔

**Comment by mmalferov** [comment]
This is a common documentation problem, or rather the problem of the word `use`, which seems to say something that actually says literally nothing.

I would forbid using (!)… I would forbid writing (!) this word *at all.* It is always better to write a specific action instead: call a method, specify a modifier, declare a function, pass a value rather than use a method, use a modifier, use a function, use a value…

"The final modifier may now be used…" — how exactly?! :)

**Comment by Girgias** [comment]
The problem a lot of the times is the people writing the entry in UPGRADING in a way which is kinda useless, so one is just "guessing" what the hell it means.

I think for PHP next I am going to push a migration guide and force people to write the entry in it properly on doc-en instead of minimal text in the `UPGRADING` file of php-src.

**Comment by mmalferov** [comment]
Take a look at this sample code:

https://3v4l.org/EkGgI#v8.3.0

And try switch to lower PHP version; prior to PHP 8.3.0, You'll get: `Fatal error: Cannot use 'final' as method modifier`

It seems that it is now clear how the `final` modifier was allowed to be *used*.

I have propose changes in the last code example in https://github.com/php/doc-en/pull/4188, correct it if necessary

**Comment by alexandre-daubois** [comment]
Great finding, I wasn't aware of `as final` at all 😄
