### ISSUE TITLE
Optional parameter before required ones are deprecated

### ISSUE THREAD

**Issue by boan-jfm** [php/doc-en#4230]
From manual page: https://php.net/migration84.deprecated

![image](https://github.com/user-attachments/assets/e84d3627-8791-4a27-8e88-aa1346303d22)

**Comment by boan-jfm** [comment]
Okay in this example the optional one is changed to a required one... I assume both works, but it would be a breaking.

**Comment by Girgias** [comment]
Yes, optional parameters before required ones are deprecated as of 8.0.0. It just that an automatic/dummy fix for the implicitly nullable type problem may change the deprecation.
