### ISSUE TITLE
HTTP_USER_AGENT undefined array key

### ISSUE THREAD

**Issue by james-langille** [php/doc-en#4254]
From manual page: https://www.php.net/manual/en/tutorial.useful.php

Examples in this page don't work (Android/Chrome). Errors like the following:

Warning: Undefined array key "HTTP_USER_AGENT" in php-wasm run script on line 2
Deprecated: str_contains(): Passing null to parameter #1 ($haystack) of type string is deprecated in php-wasm run script on line 2

**Comment by sy-records** [comment]
which does not exist in the current environment because it uses WASM.

<img width="879" alt="image" src="https://github.com/user-attachments/assets/2ba72731-20ec-4567-ad30-0987c7389fc3">
