### ISSUE TITLE
Inaccurate caution note on pack()

### ISSUE THREAD

**Issue by nielsdos** [php/doc-en#4266]
From https://www.php.net/manual/en/function.pack.php:

> Note that PHP internally stores [int](https://www.php.net/manual/en/language.types.integer.php) values as signed values of a machine-dependent size (C type long).

No it doesn't. The C type long is 32 bits on 64 bit Windows, even though PHP's int is 64 bits on 64 bit Windows. I think it would be good to just drop the "C type long" part.

**Comment by Ankush1oo8** [comment]
Shall I fix this

**Comment by nielsdos** [comment]
Feel free to give this a shot
