### ISSUE TITLE
Bug in examples

### ISSUE THREAD

**Issue by denispsr** [php/doc-en#4302]
From manual page: https://php.net/gmp.examples

---
Fatal error: Uncaught Error: Call to undefined function gmp_strval() in php-wasm run script:11
Stack trace:
#0 {main}
  thrown in php-wasm run script on line 11

**Comment by sy-records** [comment]
Thank you for your feedback.

php-wasm does not enable this extension, so it won't work.

**Comment by shaedrich** [comment]
Is it planned to define which examples are _runnable_ as a follow-up to php/web-php#1097?

**Comment by damianwadley** [comment]
@shaedrich See #4353

**Comment by shaedrich** [comment]
@damianwadley Oh, thanks a lot! 👍🏻
