### ISSUE TITLE
gettext function 

### ISSUE THREAD

**Issue by kranack** [php/doc-en#4352]
From manual page: https://php.net/function.gettext

---

When clicking "run code" button, this exception appears:
```
Fatal error: Uncaught Error: Call to undefined function bindtextdomain() in php-wasm run script:7
Stack trace:
#0 {main}
  thrown in php-wasm run script on line 7
```

**Comment by sy-records** [comment]
Thank you for your feedback.

php-wasm does not enable this extension, so it won't work.

**Comment by kranack** [comment]
Shouldn't the "run code" button be disabled in that case ?

**Comment by sy-records** [comment]
see https://github.com/php/doc-en/issues/4353
