### ISSUE TITLE
DateInterval: weeks and days can be combined since 8.0

### ISSUE THREAD

**Issue by gharlan** [php/doc-en#633]
From manual page: https://php.net/dateinterval.construct

---

> W | weeks. These get converted into days, so can not be combined with D.

The "so can not be combined with D" part is no longer true since php 8.0: https://3v4l.org/RNqK8
https://github.com/derickr/timelib/pull/85

**Comment by kamil-tekiela** [comment]
Thanks for the issue. We also encourage making pull requests. There's a lot of things pending to be updated in the manual and we appreciate any help.
