### ISSUE TITLE
SplDoublyLinkedList::__construct() does not exist

### ISSUE THREAD

**Issue by porthd** [php/doc-en#640]
From manual page: https://php.net/class.spldoublylinkedlist

---
The documentation describe a constructor.
https://www.php.net/manual/de/spldoublylinkedlist.construct.php
https://www.php.net/manual/en/spldoublylinkedlist.construct.php

I think, there is no constructor. (or misunderstand I something?)

I tried to extend 'SplDoublyLinkedList' in an own class and got the unexpected fatal error (see comment in code) 

```
<?php
        
        class Liste extends SplDoublyLinkedList 
        {
            public function __construct() {
                parent::__construct(); //<b>Fatal error</b>:  Uncaught Error: Cannot call constructor in [...][...]:6
                $this->push('klaus');
                
            }
            
            public function liste() {
                $this->push('herbert');
            }
        }

$hallo = new Liste();
$hallo->push('padina');
$hallo->push('doof');
$hallo->liste();
foreach($hallo as $key=>$item) {
    echo($key.' => '.$item."\n");
```

**Comment by cmb69** [comment]
Right, [`SplDoublyLinkedList` has no contructor](https://3v4l.org/J3aER). The page should be removed.
