### ISSUE TITLE
Ncurses documentation section missing

### ISSUE THREAD

**Issue by radosslav** [php/doc-en#645]
Hello.

I just find that the Ncurses documentation section on the php.net site return 404:

[https://www.php.net/manual/en/ref.ncurses.php](https://www.php.net/manual/en/ref.ncurses.php)

The section still pop up in Google search result and from archive.org I can see its ok and online at least to 20 May this year, but currently is gone.

**Comment by cmb69** [comment]
The documentation has been recently removed from the PHP manual, because the extension is unmained (last release was 9 years ago).

**Comment by nikic** [comment]
Maybe worth mentioning that there is a mirror for legacy docs at https://php-legacy-docs.zend.com/manual/php5/en/book.ncurses, in case you were specifically looking for those docs, and didn't just find the dead link by accident.

**Comment by radosslav** [comment]
> Maybe worth mentioning that there is a mirror for legacy docs at https://php-legacy-docs.zend.com/manual/php5/en/book.ncurses, in case you were specifically looking for those docs, and didn't just find the dead link by accident.

Thank you @nikic ! Yes, I just want to take a general look, because I currently work on one CLI tool and this type of GUI is interesting for me, no matter what Ncurses implementation is used.
