### ISSUE TITLE
Link to ICU locale explorer broken

### ISSUE THREAD

**Issue by pierre-H** [php/doc-en#669]
From manual page: https://php.net/intl.configuration

---

The link http://demo.icu-project.org/icu-bin/locexp doesn't exist.

**Comment by cmb69** [comment]
Thank you! However, I think that should be reported to the ICU project, since they're [linking to that demo](https://icu4c-demos.unicode.org/icu-bin/icudemos) as well.

**Comment by Girgias** [comment]
This was fixed upstream, and now properly redirects to https://icu4c-demos.unicode.org/icu-bin/locexp.
