### ISSUE TITLE
you shocked me :) NO PAGE https://www.php.net/manual/ru/refs.creditcard.php

### ISSUE THREAD

**Issue by aliskinr** [php/doc-en#678]
From manual page: https://www.php.net/manual/ru/refs.creditcard.php
you shocked me :) https://linux.org.ua/index.php?topic=11756.msg203780#msg203780
![Screenshot_20210609_210255](https://user-images.githubusercontent.com/82435321/121406738-2f75dd00-c967-11eb-8486-2527e6bd2b21.png)

---

**Comment by nikic** [comment]
Please see https://php-legacy-docs.zend.com/manual/php5/en/refs.creditcard for deep end legacy documentation.

**Comment by tiffany-taylor** [comment]
> This extension has been moved to the » PECL repository and is no longer bundled with PHP as of PHP 5.1.0.
Note that this was removed from the manual because it was in PHP 5, but not PHP 7.x. See https://news-web.php.net/php.doc/969387609
