### ISSUE TITLE
Issue with Tiff & Custom size Images

### ISSUE THREAD

**Issue by sprabhakar93** [php/doc-en#699]
From manual page: https://php.net/book.imagick

---
Hi 
We are using ImageMagick plugin for Print2Metal website and we have encountered an issue when we upload a Tiff image on the website with a custom size. The saved image is of incorrect size. 
Example: 
We uploaded a tiff image with a custom size of 22 x 17.5 inch, but the saved image is not of the requested size (Please check the attached image). 
Can you please let us know if you have any solution for this issue?
Thank you. 
Kind regards, 
![TestImage](https://user-images.githubusercontent.com/79486075/122509963-13013100-d048-11eb-94a6-6fd11e40c5fd.JPG)

Sandhya Prabhakar
Client Service Coordinator

**Comment by nikic** [comment]
This does not look like an issue with the PHP documentation, you probably want to file this as an issue for the imagick extension (at https://github.com/Imagick/imagick). Though I can already tell you that you'll need to provide more information, in particular a minimal code example is a must.
