### ISSUE TITLE
No documentation for STREAM_CRYPTO_METHOD_TLSv1_3_CLIENT

### ISSUE THREAD

**Issue by Geompse** [php/doc-en#701]
From manual page: https://php.net/function.stream-socket-enable-crypto
---
Constant is not referenced, but exists since 7.4/8.0 : https://3v4l.org/3W5bn

Side notes :
- It is uncommon for constants not to be listed in the dedicated manual page : https://www.php.net/manual/en/stream.constants.php
- The case is weird (lower "v"), I think it would be nicer without it : STREAM_CRYPTO_METHOD_TLS_1_3_CLIENT

**Comment by Girgias** [comment]
Indeed this is a duplicate now
