### ISSUE TITLE
MIght as well update this info right away; the filename is `php7apache2_4.dll` (all PHP 7 versions) and `php8apache2_4.dll` (for PHP 8), respectively.

### ISSUE THREAD

**Issue by Angie3120** [php/doc-en#702]
MIght as well update this info right away; the filename is `php7apache2_4.dll` (all PHP 7 versions) and `php8apache2_4.dll` (for PHP 8), respectively.

_Originally posted by @cmb69 in https://github.com/php/doc-en/pull/661#discussion_r646188643_

**Comment by sy-records** [comment]
Thank you for your feedback, it has been modified here.

https://github.com/php/doc-en/blob/8e732e84a1425cf0ab3a5b0da8fe113c7a6da85e/install/windows/apache2.xml#L59-L63
