### ISSUE TITLE
ClassName::class is magic constant

### ISSUE THREAD

**Issue by amritpalnagrame** [php/doc-en#707]
1. Every magic method starts with `__` and magic constants even ends with `__`, except `ClassName::class `i.e. specified as [magic constant in docs](https://www.php.net/manual/en/language.constants.magic.php).
2. Isn't this `ClassName` referring to any replaceable values followed by [scope resolution operator `::` ](https://www.php.net/manual/en/language.oop5.paamayim-nekudotayim.php) and [class keyword](https://www.php.net/manual/en/language.oop5.basic.php#language.oop5.basic.class.class).

So, is it magic constant composed of keyword and operator or is it mistake in [Magic constants docs](https://www.php.net/manual/en/language.constants.magic.php)?

**Comment by kamil-tekiela** [comment]
I agree calling `class` a constant is misleading, but it does fit the definition of a magic constant. To make things clearer I would keep it on the page for magic constants, but remove `ClassName`, so just leave it as `::class`, i.e. the operator and the keyword together. 

On the dedicated page for that keyword I would replace 

>As of PHP 8.0.0, the ::class constant may also be used on objects.

With 

>As of PHP 8.0.0, the ::class keyword may also be used on objects.

**Comment by Crell** [comment]
Fixed via #2112
