### ISSUE TITLE
Is the return type of ReflectionProperty::getType missing?

### ISSUE THREAD

**Issue by chatii** [php/doc-en#713]
From manual page: https://php.net/reflectionproperty.gettype

---

see: https://3v4l.org/lld3D

PHP >= 8.0
The PHP manual says `ReflectionType|null`, but `ReflectionNamedType` is returned.

**Comment by schrosis** [comment]
If the type of the property is not annotated, `null` will be returned.
https://3v4l.org/pcqnR

**Comment by mumumu** [comment]
ReflectionType become abstract type as of PHP 8.0.0 [*1].
And ReflectionNamedType is subclass of it [*2], so it seems that `ReflectionType|null` signature is correct.

[*1] https://www.php.net/manual/en/class.reflectiontype.php
[*2] https://www.php.net/manual/en/class.reflectionnamedtype.php

**Comment by cmb69** [comment]
Yes, the [docs are correct](https://heap.space/xref/php-src/ext/reflection/php_reflection.stub.php?r=fccb7274#437). Thanks for the PR anyway!

**Comment by chatii** [comment]
Okay, I understand! thanks!
