### ISSUE TITLE
Clearer wording in second paragraph for ucfirst

### ISSUE THREAD

**Issue by shahovkit** [php/doc-en#720]
"The definition of a word is any string of characters that is immediately **after** any character listed"
not only after the character, but also the first word in the string

because ucwords('lorem-ipsum-dolor', '-') isn't lorem-Ipsum-Dolor, but Lorem-Ipsum-Dolor

From manual page: https://php.net/function.ucwords

---

**Comment by tiffany-taylor** [comment]
This is explained in the first paragraph:
> Returns a string with the first character of each word in string capitalized

However, the wording in the second paragraph could be a little clearer, probably.
