### ISSUE TITLE
Wrong statement about errno passed to error handler

### ISSUE THREAD

**Issue by php4fan** [php/doc-en#744]
From manual page: https://php.net/function.set-error-handler

> Warning
> Prior to PHP 8.0.0, the errno value was always 0 if the expression which caused the diagnostic was prepended by the @ error-control operator.

That's not true. The value of `errno` is always that of the actual error regardless of the `@` operator, both in PHP 7 (and lower) and in PHP 8.

What was always zero before PHP 8 and is not always zero in PHP 8, is the value returned by `error_reporting()` inside the error handler.

In PHP 8 the value returned by `error_reporting()` inside the error handler **CHANGES SOMEHOW** if the expression that triggers the error has `@` error suppression. How exactly it changes is utterly undocumented.

https://3v4l.org/vT9J2

The same wrong statement is also present here:
https://www.php.net/manual/en/language.operators.errorcontrol.php

> Warning
Prior to PHP 8.0.0, the value of the **severity** passed to the custom error handler was always 0 if the diagnostic was suppressed. This is no longer the case as of PHP 8.0.0.

Note that here it is more confusing because it says "the severity"; one can only guess that it refers to `err_no`

**Comment by Girgias** [comment]
Fixed via https://github.com/php/doc-en/commit/14a60fad6edabd3384c434cc6257255798453e87
