### ISSUE TITLE
sign of default_longitude

### ISSUE THREAD

**Issue by SteveAllen-UCOLick** [php/doc-en#745]
`From` manual page: https://php.net/datetime.configuration

documentation for default_longitude must explicitly state that west longitude is negative
---

**Comment by cmb69** [comment]
That appears to be the common definition anyway. @derickr, thoughts?

**Comment by SteveAllen-UCOLick** [comment]
please make it explicit so that nobody has to stop and wonder

**Comment by derickr** [comment]
This function and setting is being deprecated in 8.1 most likely. Use date_suninfo instead.

**Comment by derickr** [comment]
But yes, negative is west.

**Comment by SteveAllen-UCOLick** [comment]
thanks.  also, ob been there done that https://www.ucolick.org/~sla/sunset/

**Comment by cmb69** [comment]
And noon is 12pm – should we explicitly state that as well? ;)

**Comment by derickr** [comment]
Yes, because I never know whether it's 12pm or 12am.

**Comment by cmb69** [comment]
Fair enough. But we should address the latitude as well.
