### ISSUE TITLE
stats_dens_normal formula available in Romanian 

### ISSUE THREAD

**Issue by codecru** [php/doc-en#778]
From manual page: https://php.net/function.stats-dens-normal

---
https://www.loom.com/share/3abac0feda2e401e8016b9417017127d

I can see stats_dens_normal formula on the website is only the Romanian language, not in any other language but when I try to use this function I get an error of undefined function.

**Comment by kamil-tekiela** [comment]
Not all translations are up to date. Some may contain inaccurate information or pages that were since removed from PHP manual. There are legacy docs hosted here https://php-legacy-docs.zend.com/manual/php5/en/book.stats

**Comment by codecru** [comment]
> Not all translations are up to date. Some may contain inaccurate information or pages that were since removed from the PHP manual. There are legacy docs hosted here https://php-legacy-docs.zend.com/manual/php5/en/book.stats

https://php-legacy-docs.zend.com/manual/php5/en/function.stats-dens-normal
stats_dens_normal is this formula depreciated in PHP 7?

**Comment by cmb69** [comment]
The [stats extension](https://pecl.php.net/package/stats) is unmaintained, so the documentation has been removed. If a new maintainer steps up, we can restore the docs.
