### ISSUE TITLE
Always put __construct first in class method list

### ISSUE THREAD

**Issue by othercorey** [php/doc-en#799]
Is it possible to sort the class methods where `__construct` is first? It looks very odd when it's shorted alphabetically without the `__`.

Example:

https://www.php.net/manual/en/class.recursiveiteratoriterator.php

```
public beginChildren(): void
public beginIteration(): void
public callGetChildren(): RecursiveIterator
public callHasChildren(): bool
public __construct(Traversable $iterator, int $mode = RecursiveIteratorIterator::LEAVES_ONLY, int $flags = 0)
public current(): mixed
```

**Comment by cmb69** [comment]
That requires the constructor to be marked up with `<constructorsynopsis>` instead of `<methodsynopsis>`. PR #624 would fix this for RecursiveIteratorIterator (and likely some others).

**Comment by othercorey** [comment]
Thanks for the explanation. 

I don't want to request someone do a lot of work, but its it difficult to verify any construct.xml contains the constructorsynopsis version?

It's just patch it as you find it then so be it. Will do.
