### ISSUE TITLE
random_bytes should include a note that it can generate null bytes

### ISSUE THREAD

**Issue by tiffany-taylor** [php/doc-en#800]
_Assuming_ this is correct, the `random_bytes` page should include a note or warning stating null bytes can be generated.

https://www.php.net/manual/en/function.random-bytes.php

(If I can find the rights words, I'll do this, but creating the issue as a reminder.)

**Comment by tiffany-taylor** [comment]
FWIW, I'm hesitant to make it a warning because I don't want to discourage usage of `random_bytes`, but I believe it should be noted in some form so that it doesn't come as a surprise.

**Comment by kamil-tekiela** [comment]
Why should this be a warning? Doesn't "bytes" already mean "all bytes"? If you feel a need to clarify this in the manual then I don't it needs to be a warning.

**Comment by tiffany-taylor** [comment]
Removed the "warning" wording because, agreed, it shouldn't be a warning, but I think it should be noted at least.

**Comment by salathe** [comment]
Can you elaborate on why null bytes deserves special mention for this function?  We don't ordinarily do that for other functions whose return value can contain null bytes.

**Comment by gnif** [comment]
I also agree with other replies here, there is no need to document that null bytes are possible, this is implied by the type "byte" being an 8-bit value from 0-255. All values in this range are valid byte values, including 0.
