### ISSUE TITLE
documentation: dom_import_simplexml incorrect return value.

### ISSUE THREAD

**Issue by KevinVanSonsbeek** [php/doc-en#804]
From manual page: https://php.net/function.dom-import-simplexml

--- Return value is mentioned to be `The DOMElement node added or false if any errors occur.`
While the actual return type is `DOMElement|null`

**Comment by KevinVanSonsbeek** [comment]
I did just notice in the source code, that going from PHP 7.4.* to PHP 8.*, that the return in the method has changed from `RETURN_NULL();` to `RETURN_THROWS();`.

**Comment by cmb69** [comment]
Well, if the [stub](https://heap.space/xref/php-src/ext/dom/php_dom.stub.php?r=1602db2d#680) is wrong, it should be fixed in php-src.

**Comment by nikic** [comment]
Stub fixed in https://github.com/php/php-src/commit/a0893865b31c2f3af81861608b2b3f07ec0545b8.
