### ISSUE TITLE
English language returns 404 for manual page mongocollection.batchinsert.php

### ISSUE THREAD

**Issue by ptheofan** [php/doc-en#808]
From manual page: https://php.net/mongocollection.batchinsert

---

The following link produces 404
https://www.php.net/manual/en/mongocollection.batchinsert.php

Google search results as such gave me the Romanian version
https://www.php.net/manual/ro/mongocollection.batchinsert.php

except I do not speak Romanian

**Comment by nikic** [comment]
Docs for this legacy extension are available at https://php-legacy-docs.zend.com/manual/php5/en/book.mongo or https://mongodb.github.io/mongo-php-driver-legacy/. Please use the mongodb extension instead.
