### ISSUE TITLE
Union return types are missing | delimiter

### ISSUE THREAD

**Issue by othercorey** [php/doc-en#819]
Looks like all the union return types are missing the `|` delimiter. Other union types such as parameters are not missing `|`.

https://www.php.net/manual/en/class.intldateformatter.php

> public getCalendar(): intfalse

**Comment by cmb69** [comment]
This has been [fixed](https://github.com/php/phd/commit/a80bb2837945bfa94d1d18b536a6ec45c10c5728) in the meantime. New builds may take some hours to be rolled out to the Website.
