### ISSUE TITLE
preg_replace() doesn't work if a string cointains "<" symbol

### ISSUE THREAD

**Issue by KillTomer** [php/doc-en#835]
From manual page: https://php.net/function.preg-replace

---
Remove all whitespaces doesn't work below.
preg_replace('/\s+/', '', 'a < b  < c');

Returns 'a'

instead of 'a<b<c'

**Comment by cmb69** [comment]
Use view:source to see the `<` characters.

**Comment by cmb69** [comment]
Also note that this repo is about *documentation* issues.

**Comment by KillTomer** [comment]
> Use view:source to see the `<` characters.

It strips unwanted letters from the string. It's not just it doesn't show '<'.

**Comment by cmb69** [comment]
No, [it does not](https://3v4l.org/sAbnd). It's just because the browser treats the rest as tags, and doesn't show them.

**Comment by KillTomer** [comment]
> No, [it does not](https://3v4l.org/sAbnd). It's just because the browser treats the rest as tags, and doesn't show them.

You are right genius. htmlspecialchars() solved that! Thank you very much.
