### ISSUE TITLE
proc_get_status() return type

### ISSUE THREAD

**Issue by tored** [php/doc-en#845]
Seems like the return type for `proc_get_status()` changed in PHP 8, previously it could return `array|false` but with PHP 8 only `array` , stubs says `array` and documentation below **Return Values** says _An array of collected information on success, and false on failure_

Was this because in PHP 8 you get a proper type error if you pass in a bogus argument?

If my assumption about this change in return type is true perhaps we should add either  Changelog directive or a Note.

**Comment by cmb69** [comment]
`proc_get_status()` only returned `false` under PHP 7 when called with a wrong parameter type (non-resource, or wrong or closed resource); this is actually covered by the note on https://www.php.net/manual/en/functions.internal.php, so there was no need to document this; as such, no need for a changelog entry.
