### ISSUE TITLE
array_combine throws ValueError since PHP 8 

### ISSUE THREAD

**Issue by olsavmic** [php/doc-en#849]
From manual page: https://php.net/function.array-combine

---

Since PHP 8, array_combine function throws ValueError instead of returning `false` and E_WARNING.

This behaviour is not documented anywhere on the PHP 8 migration guide (https://www.php.net/manual/en/migration80.php) nor the array_combine documentation.

Perhaps a change log should be added similarly to https://www.php.net/manual/en/function.round.php.

**Comment by sy-records** [comment]
Thank you for your feedback.
