### ISSUE TITLE
Deprecated trader.so: undefined symbol: add_next_index_zval

### ISSUE THREAD

**Issue by adsonvinicius** [php/doc-en#854]
From manual page: https://php.net/book.trader

---

PHP 7.4+ has not this symbol anymore, so it raises the exception: _**trader.so: undefined symbol: add_next_index_zval**_

**Comment by cmb69** [comment]
That doesn't look like a documentation issue, though; please file a bug report at https://bugs.php.net/report.php?package=trader.
