### ISSUE TITLE
Callback is seen as string and not as callable 

### ISSUE THREAD

**Issue by spoofghost** [php/doc-en#855]
From manual page: https://php.net/recursivecallbackfilteriterator.construct

---

**Comment by cmb69** [comment]
Can you please clarify what you regard as bug here?

**Comment by spoofghost** [comment]
CallbackFilterIterator's second parameter is stated as being a callable but when parsing in a callable in the form of an anonymous function it says it should be a string. 

So it seems the callback parameter only accepts a string type and a callable type.

**Comment by cmb69** [comment]
> but when parsing in a callable in the form of an anonymous function it says it should be a string.

> That said parsing in an anonymous functions does however runs just fine.

Arent't these statements contradictory? Can you please post a small example that fails?

**Comment by spoofghost** [comment]
Sure, To clarify my IDE PHPstorm is bugging me that the second parameter should be of the type string: 

`Expected parameter of type 'string', '\Closure' provided `

Code example: 

```        
$filter = new RecursiveCallbackFilterIterator($directory, function ($current, $key, $iterator){
              ...
            });```

Perhaps its an IDE problem though.

**Comment by kamil-tekiela** [comment]
If the IDE tells you it's wrong but the code works then it's probably IDE fault. I am closing this PR as I don't see any problem in PHP manual. If you do see something that needs to be improved then please clearly explain it.

**Comment by nikic** [comment]
The PhpStorm issue has been fixed by https://github.com/JetBrains/phpstorm-stubs/commit/9916e7af34e90e6f26a59b04983355ddb7bba646 a few months ago.
