### ISSUE TITLE
Error in `PDO::setAttribute()` documentation

### ISSUE THREAD

**Issue by Alexis-ROYER** [php/doc-en#866]
From manual page: https://php.net/pdo.setattribute

---

The type given in the method signature for the `$value` parameter is `array|int`.

But it said later, for the `PDO::ATTR_EMULATE_PREPARES` attribute, that it "Requires bool".

Should not the type of `$value` be `array|int|bool`?

**Comment by cmb69** [comment]
According to [the stub](https://github.com/php/php-src/blob/b3b16584928503b814bc83439cb85208fa6e1935/ext/pdo/pdo_stmt.stub.php#L62), the type should be `mixed`.

**Comment by kamil-tekiela** [comment]
@cmb69 That is for `PDOStatement`. For `PDO`: https://github.com/php/php-src/blob/b3b16584928503b814bc83439cb85208fa6e1935/ext/pdo/pdo_dbh.stub.php#L53

**Comment by cmb69** [comment]
Ah, right, thanks! Then the stub needs to be fixed first.

**Comment by nikic** [comment]
Stub fixed in https://github.com/php/php-src/commit/2e343fcb422a130ebc9b7d396ad692bc4ec3ce15.
