### ISSUE TITLE
DateTime::diff error? Discrepancy from Excel

### ISSUE THREAD

**Issue by gtrachier** [php/doc-en#873]
From manual page: https://php.net/datetime.diff

---

Hello,

There is a discrepancy between a date calculation in Excel and in PHP.  The short of it is that Excel treats 1900-02-29 as a leap day, whereas PHP does not.  Wikipedia has the following on the subject:
"These extra days occur in each year which is an integer multiple of 4 (except for years evenly divisible by 100, but not by 400)."

It appears there is a flaw in the way PHP (at least this version) determines a leap year.  What do you think?

Please see attached Excel spreadsheet.

Regards,

-Gary

PHP: 
PHP 7.3.27-1~deb10u1 (cli) (built: Feb 13 2021 16:31:40) ( NTS )

Microsoft Excel:
Version 16.52 (21080801)

[Excel PHP Date Difference Disparity.xlsx](https://github.com/php/doc-en/files/7028301/Excel.PHP.Date.Difference.Disparity.xlsx)

**Comment by Girgias** [comment]
> From manual page: https://php.net/datetime.diff
> 
> Hello,
> 
> There is a discrepancy between a date calculation in Excel and in PHP. The short of it is that Excel treats 1900-02-29 as a leap day, whereas PHP does not. Wikipedia has the following on the subject:
> "These extra days occur in each year which is an integer multiple of 4 (except for years evenly divisible by 100, but not by 400)."

1900 is divisible by 100 and not 400 meaning that it is *not* a leap year.
Excel is the one having a bug here not PHP.

(Just to make sure, 1700, 1800, and 1900 were not leap years, but 1600 and 2000 were because they are divisible by 400.)

**Comment by gtrachier** [comment]
Right you are!  Additional on-line research confirms your answer.  My apologies for misinterpreting the rule described in the Wikipedia article.  Now to take on the Microsoft behemoth...  Cheers!
