### ISSUE TITLE
Using a negative offset always returns false

### ISSUE THREAD

**Issue by dabbmedia** [php/doc-en#874]
From manual page: https://php.net/function.strpos

---
Using a negative offset always returns false, instead of the position of the last occurrence of the string.

Steps to reproduce (tested on PHP 7.3.27-1~deb10u1 (cli), PHP 7.3.24-(to be removed in future macOS) (cli) and Docker images 7.1-4):

docker run -it --rm php:7.4 bash

php -r "echo strpos('A string with spaces in it.', ' ', -1) . PHP_EOL;"
Expected output: 23 (manually counted)
Actual output: (false, so empty string)

php -r "echo strpos('A string with spaces in it.', 's', -1) . PHP_EOL;"
Expected output: 19 (manually counted)
Actual output: (false, so empty string)

php -r "echo gettype(strpos('A string with spaces in it.', 's')) . PHP_EOL;"
Output: integer
php -r "echo gettype(strpos('A string with spaces in it.', 's', -1)) . PHP_EOL;"
Output: boolean

Immense apologies if I misunderstand the docs.

**Comment by salathe** [comment]
The description for negative offsets is:

>  If the offset is negative, the search will start this number of characters counted from the end of the string.

In your examples, using offset `-1`, the search will start at one character from the end of the string and then search forward towards the end (not backwards towards the beginning): in other words, at the `.` character.  There is no ` ` (space) or `s` character there, so `false` is returned.  

If your offset were `-11`, then the search would start at the 11th character from the end of the string: i.e. the `a` of `spaces`.  If you were searching for ` ` (space) then it would be found after the end of the word `spaces` to give a return value of `20`:

```php
<?php
var_dump(strpos('A string with spaces in it.', ' ', -11));
?>
```

Outputs:

```
int(20)
```

Finally, there is a different function available for finding the position of the last occurrence of a substring within a string: [`strrpos()`](https://www.php.net/strrpos).

**Comment by dabbmedia** [comment]
Thank you Peter! And apologies, I searched for such a function, but completely missed it. Used a negatively incremented for loop instead, but strrpos is better.

Thanks,
Brent

**Comment by nikic** [comment]
@dabbmedia It may be useful to look at the "See Also" section in the manual, which lists related functions that may be useful (in this case including strrpos): https://www.php.net/manual/en/function.strpos.php#refsect1-function.strpos-seealso

**Comment by dabbmedia** [comment]
@nikic ;)
