### ISSUE TITLE
InternalIterator class is reserved as of PHP 8.0.0

### ISSUE THREAD

**Issue by mumumu** [php/doc-en#896]
We cannot instantiate or extend global scope class `InternalIterator` which is introduced as of PHP 8.0.0 ( https://github.com/php/php-src/commit/ff19ec2df3ef0dca8c29be83eddcde58234f4095 ) and seems to be reserved as internal iterator classname, but this fact is Undocumented.

https://3v4l.org/OKO6a

We should document it in [appendices/migration80/incompatible.xml](https://github.com/php/doc-en/blob/master/appendices/migration80/incompatible.xml)?

**Comment by cmb69** [comment]
See #896. I think documenting the new class in new-features.xml is sufficient.
