### ISSUE TITLE
error_reporting default value description is wrong

### ISSUE THREAD

**Issue by mumumu** [php/doc-en#928]
https://www.php.net/manual/en/ini.list.php

As of PHP 8.0.0, the default `error_reporting` level is now E_ALL, but in `error_reporting` description, its value is `NULL`.

In php-src, `ZEND_INI_ENTRY` sets NULL as default value of it [*1], it seems to be correct.
On the other hand, `ZEND_INI_MH` returns `E_ALL` [*2].

Is this a bug of PHP Manual? 

[*1] https://github.com/php/php-src/blob/php-8.0.0/Zend/zend.c#L183
[*2] https://github.com/php/php-src/blob/php-8.0.0/Zend/zend.c#L98-L106

**Comment by Girgias** [comment]
This was fixed with b9d5dcd7821e4337cd15e83a82ba6d07a39360dc
