### ISSUE TITLE
PHP8: Undefined symlink() function

### ISSUE THREAD

**Issue by azmanabdlh** [php/doc-en#929]
From manual page: https://php.net/function.symlink
---
After following the PHP documentation (symlink) which is still included in **PHPv8**, I'm still having issues with undefined function call symlink() on **PHPv8.0.10** version.

<img width="1274" alt="Screen Shot 2021-09-08 at 08 04 51" src="https://user-images.githubusercontent.com/71063565/132424732-27ac413d-843e-4a33-b474-4dad5d23fbfb.png">

**Comment by sy-records** [comment]
see https://3v4l.org/WNj1X

You seem to be missing the ext-standard
