### ISSUE TITLE
Table style - bug

### ISSUE THREAD

**Issue by hcastillodev** [php/doc-en#943]
From manual page: https://php.net/resource

---
![php-resource-table-style-bug](https://user-images.githubusercontent.com/82906228/132995459-61f7f584-f838-4879-886b-eecfd57d2f6a.png)

Here i just found a style bug on table. Nothing more

**Comment by kamil-tekiela** [comment]
Thank you. We are aware of this bug, but so far nobody has proposed a solution to fix it. We appreciate any ideas you might have on how to fix this.

**Comment by hcastillodev** [comment]
I will try some stuff and  if a have success, I gonna create the PR

**Comment by cmb69** [comment]
Just don't use a table for this. :)

**Comment by Girgias** [comment]
Duplicate of #792
