### ISSUE TITLE
Usage of `class` keyword unclear

### ISSUE THREAD

**Issue by jiyongcheng** [php/doc-en#944]
Hi folks,
I'm reading the PHP documentation section `List of Keywords` here https://www.php.net/manual/en/reserved.keywords.php

and there is a sentence `They are, however, allowed as property, constant, and method names of classes, interfaces and traits, except that class may not be used as constant name.` confuses me a lot. I understand the first half, and tried by myself, indeed the keyword can be used as property, constant, method names of classes. but I don't understand this exception `except that class may not be used as constant name.`

what does this exception talk about?  is there any code example can help me to understand what the author is talking here?

Thanks

**Comment by salathe** [comment]
That refers specifically to the `class` keyword, which cannot be used as a class/interface constant.

For example:
```
class Example {
    const class = 123;
}
```
Which will give the Fatal Error:
```
Fatal error: A class constant must not be called 'class'; it is reserved for class name fetching
```

**Comment by jiyongcheng** [comment]
> That refers specifically to the `class` keyword, which cannot be used as a class/interface constant.
> 
> For example:
> 
> ```
> class Example {
>     const class = 123;
> }
> ```
> 
> Which will give the Fatal Error:
> 
> ```
> Fatal error: A class constant must not be called 'class'; it is reserved for class name fetching
> ```

Thank you so much! 👍 I understand it now :)

**Comment by jiyongcheng** [comment]
By the way, I checked the PHP 8, `match` is now a reserved keyword. and I tried these two ways to define a constant.
For example: 
```php
define("MATCH", 2);
const MATCH = 2;
```
The first one doesn't cause error in PHP8, but the second one give the Syntax Error:
```
Parse error</b>:  syntax error, unexpected token 'match', expecting identifier
```

if the keyword cannot be used as constants, how to understand this case?  I'm using PHP online editor http://sandbox.onlinephpfunctions.com/code/77f3ab71cd62944dbd879b9e363ff9e98a858c5a and choose version 8 to try to confirm my understanding.

Thanks

**Comment by sy-records** [comment]
match was added as a keyword (reserved_non_modifiers). This means it can’t be used in the following contexts anymore:

- namespaces
- class names
- function names
- global constants

Note that it will continue to work in method names and class constants.

see https://wiki.php.net/rfc/match_expression_v2

**Comment by cmb69** [comment]
@jiyongcheng, you can [use `constant`](https://3v4l.org/0tcj5).
