### ISSUE TITLE
(feature request) performance marks for function descriptions

### ISSUE THREAD

**Issue by Morgunov-Vitaly** [php/doc-en#962]
Hey!
Is it possible to add performance marks (speed, memory usage ...) to the PHP functions manual? This can be very helpful for developers.
As an example - https://wp-kama.ru/function/the_title
The author uses colored labels (green, yellow, red) and a description of the performance of WordPress functions. And this is very useful information for development!

**Comment by cmb69** [comment]
I don't think this makes much sense.

**Comment by kamil-tekiela** [comment]
Possible - maybe. Helpful to developers - very debatable. Good idea - rather not. 
I'm not even clear on what kind of information we would want to share this way. Execution time depends on a lot of factors and most the of the time it doesn't matter how long it takes to execute a function one time. With OPCache, there's a lot of optimizations that would make it very difficult to meaningfully describe the performance of a given function without comparing it to something. Jit makes it even more pointless to show such information. 

Maybe it looks cool, but this would not be feasible and useful. There are a lot of other problems/missing information in the manual and we would appreciate your contributions if you want to help us maintain PHP manual with up-to-date information.
