### ISSUE TITLE
session_set_save_handler and SessionHandlerInterface::read() returns do not match

### ISSUE THREAD

**Issue by othercorey** [php/doc-en#970]
https://www.php.net/manual/en/sessionhandlerinterface.read.php

`SessionHandlerInterface::read()` documents the return type as `string|false` where false represents no data for a given `$id`.

https://www.php.net/manual/en/function.session-set-save-handler.php

The read callback is documented as returning an empty string on failure (as SessionHandlerInterface used to).

One of these is wrong. When we updated our database session handler to return `false`, it causes `session_start()` to fail saying unable to read session data. Reverting back to an empty string resolves the problem on PHP 8.0.10.

I was not able to fix the problem by testing with PHP 8.1.0 RC2.

**Comment by nikic** [comment]
Both empty string and false are valid return values here: An empty string means that an empty string was read successfully. False means that the read failed.

**Comment by othercorey** [comment]
https://www.php.net/manual/en/sessionhandlerinterface.read.php

> If the record was not found, return false.

So, this should still read `return an empty string` and another note saying return false on a real error like missing storage?

**Comment by othercorey** [comment]
Can you clarify if returning an empty string when starting the session is expected over false? It doesn't seem like returning false when the id doesn't exist is valid and breaks behavior.

**Comment by othercorey** [comment]
Closing since doesn't seem like more info will be added.
