### ISSUE TITLE
PHP will not always accept the usage of a closure

### ISSUE THREAD

**Issue by fasttrackhost** [php/doc-en#988]
From manual page: https://php.net/parallel-runtime.run

---

Using PHP 7.4.23 TS on Windows 2016

So lets say we use this closure
```
$my_closure = function ( Channel $channel, $var1 ){

    /*
    My long code. Code tested outside paralel and free of bugs.
    */

}
```

And we have a class that trigers parallel execution. This will sometimes execute fine. But not always. It complains about the closure, not being of type closure.

```
class my_parallel {
	private $runtime;
	private $future;
	private $channel;
	private $message_holder;

	public function __construct(){
  
		//Create runtime
		$this->runtime = new Runtime();
  
		// Create buffered channel.
		$this->channel = new Channel(Channel::Infinite);
  
	}

	public function send($var1) {

		global $my_closure;
		// This only executes at random times
		$this->runtime->run( $my_closure, [ $this->channel, $var1 ] );

	}
}
```

But if we change the code a bit. It will always execute fine.

```
	// Let's just skip everything else

	public function send($var1) {

		global $my_closure;
		// This always executes fine
		$this->runtime->run( function( Channel $channel, $var1 ){
			$my_closure( $channel, $var1 );
		}, [ $this->channel, $var1 ] );

	}
```

Tried everything to get the closure to be accepted as a closure. It will sometimes execute ok, untill a server restart, when it compiles again and everything breaks.
I supose it is not the desired behaviour.

**Comment by cmb69** [comment]
This doesn't look like a documentation problem. Please report this at https://github.com/krakjoe/parallel/issues.
